commercetools/ui-kit

.travis.yml
package.json

Aight, this is my very first attempt to travis ci... ever! 😓 
I simply chose nodejs 8, since there was no engine requirement in `package.json`. Shall we set this to nodejs10 ([ref](https://docs.npmjs.com/files/package.json#engines))
closes #1

chore(travis): add config

---

package.json

If we have too many big dependancies, our bundle size will be very big. This PR aims to start this movement by moving some "easy decision" deps to peer and dev.
Feel free to suggest others that could follow similar treatment.

chore: move dependancies to peer and dev deps

---

src/components/typography/text/README.md
src/components/typography/text/text.js
src/components/typography/text/text.mod.css
src/components/typography/text/text.spec.js
src/components/typography/typography.story.js

This pull request adds the ability to specify an `isItalic` prop on our `Text.Detail` and `Text.Body` component. Sometime a recent design requires. 
I don't anticipate headings having a need for italic text soon.
In the mean time I fixed the default messages which got escaped (since a recent version of React storybook).

Add `isItalic` to `Text.Detail` and `Text.Body`

---

CHANGELOG.md
package.json
yarn.lock

Ref #8 
This is a first attempt on having a process to work with releases and changelog.
The idea is that **before** tagging a release, you update the changelog so that the changes are included in the release.
Personally, I like to have a mix of "auto-generated" changelogs and manual content. Having only an auto-generated list of commits does not help much in giving the **context** to the release. Often times you also want to include some tips, examples, migration instructions and so which you can only do manually.
So my proposal is to use `convention-changelog` to **get the changelog** and then manually add some more info (if necessary).
The script `yarn changelog` will output to the terminal the missing changelog, including the unlreleased commits.
Then you would manually copy-paste the …

Setup changelog using conventional changelog

---

package.json
src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
src/components/inputs/async-creatable-select-input/async-creatable-select-input.spec.js
src/components/inputs/async-select-input/async-select-input.js
src/components/inputs/async-select-input/async-select-input.spec.js
src/components/inputs/creatable-select-input/creatable-select-input.js
src/components/inputs/creatable-select-input/creatable-select-input.spec.js

Making `react-select` a peer dependency requires that the consumer uses the latest version `2.0.0` of the library.
I think it's fine to make it a package dependency for now.

chore: react-select not as a peer dependency

---

.travis.yml
README.md
package.json
scripts/publish-docs.js

Closes #2 
See readme for documentation.
In short:
- the production website is triggered now from the `docs-production` branch (not `master`)
- publish only when a tag is created
- travis does the publishing to npm (token already encrypted)
- after publishing, the `docs-production` branch is updated (which triggers a netlify deployment)
- github token is saved in the travis ui
PS: I haven't tested this yet, so I can only assume it works. After this is merged, I will try a test release.
Refs:
- https://docs.travis-ci.com/user/deployment/npm/
- https://docs.travis-ci.com/user/encryption-keys/

Setup release scripts 🚀

---

package.json

Woops. Sorry @qmateub.
We were missing mc-scripts dep so the command `yarn i18n:build` didn't work.
Closes [46](https://github.com/commercetools/ui-kit/issues/46#issuecomment-421257153)

fix: i18n build by adding missing dep

---

scripts/publish-docs.js

The current way of publishing the docs was not working well because of the way travis checks out the git repo.
This new approach is more "_brutal_" but it should do its job

chore: new approach for publishing docs

---

src/index.js

This component is documented in our storybook but not exported. We so far only use it internally in UIKit through components taking a `horizontalConstraint`-prop. However, sometimes this can also be helpful to consumers of UIKit. As a result I would like to re-export it.

Re-export `HorizontalConstraint` component

---

i18n/index.js

As discovered last week, we had a problem with our i18n exports, where the i18n data was being exported in the following form:
```javascript
{
en: default: {
'UIKit.Blah': 'Foo'
}
}
```
I think this was happening due to us not properly using [rollup-plugin-json](https://github.com/rollup/rollup-plugin-json). 
I built my fix and copy pasted the dist files into MC-FE and the exports look correct now. Plus, if you check the compiled code, it looks better.
Compiled code now looks like 
```javascript
...lots of stuff
var index = /*#__PURE__*/Object.freeze({
en: en,
de: de$1,
es: es
});
```
where as before it looked like
```javascript
...lots of stuff
var es$1 = /*#__PURE__*/Object.freeze({
default: es
});
var index = /*#__PURE__*/Object.freeze({
en: en$1,
de: de$2,
es: es$1
});
```

fix: fix i18n exports

---

src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
src/components/inputs/async-select-input/async-select-input.js
src/components/inputs/creatable-select-input/creatable-select-input.js
src/components/inputs/select-input/select-input.js

Let user override pre-styled components in `*SelectInput`-family of components.
My use case for that is to show `SearchIcon` in `AsyncSelectInput` instead of default `DropdownIndicator`.

feat(select-inputs): let user override customized components

---

CHANGELOG.md
package.json

Update to 2.0.0-rc.6.
Changelog is:
* fix i18n exports ([#68](https://github.com/commercetools/ui-kit/issues/68)) ([f299ea6](https://github.com/commercetools/ui-kit/commit/f299ea6))
* use correct token for selected input background ([#67](https://github.com/commercetools/ui-kit/issues/67)) ([bad8992](https://github.com/commercetools/ui-kit/commit/bad8992))
* **select-inputs:** let user override customized components ([#70](https://github.com/commercetools/ui-kit/issues/70)) ([bc7d2f0](https://github.com/commercetools/ui-kit/commit/bc7d2f0))

chore: bump version to 2.0.0-rc.6, update changelog

---

.storybook/config.js

The forms examples got lost when we extracted the UI-Kit into its own repo. This PR readds them.

Readd forms example

---

examples/form-fields.md
examples/form-fields.story.js
examples/form-inputs.md
examples/form-inputs.story.js
i18n/core.json
i18n/de.json
i18n/en.json
i18n/es.json
src/components/field-errors/field-errors.js
src/components/field-errors/messages.js
src/components/fields/number-field/messages.js
src/components/fields/text-field/text-field.js

**Storybook**
- docs: add form fields example
**Features**
- feat(field-errors): add 'fractions' and 'negative' errors
**Fixes**
- fix(text-field): safely check for errors

Improve form examples, add errors to FieldErrors, fix TextField

---

src/components/fields/number-field/number-field.js
src/components/fields/number-field/number-field.spec.js
src/components/fields/text-field/README.md
src/components/fields/text-field/text-field.form.story.js
src/components/fields/text-field/text-field.js
src/components/fields/text-field/text-field.spec.js

The `id` generation when no `id` prop is provided was broken in `NumberField` and `TextField`. The tests were not detecting this either.
This PR fixes the generation, the tests and introduces `do` expressions to replace the iife.

Fix id generation in NumberField and TextField

---

src/index.js

It is already avialable as Constraints.Horizontal.
BREAKING CHANGE: HorizontalConstraint export is no longer available.

break: remove HorizontalConstraint export

---

src/components/inputs/money-input/money-input.form.story.js
src/components/inputs/money-input/money-input.js
src/components/inputs/money-input/money-input.story.js

There is a bug in Formik which would result in MoneyInput's currency code update being lost when the amount was reformatted because of the currency code change.
The consequence of the bug is that the validation runs with the wrong `values` in case the change of the currency leads to the amount being reformatted (happens when user enters an unformatted amount before selecting a currency - and then selecting a currency). This leads to the wrong validation errors being shown and the form not being submittable.
We can remove the `setTimeout` workaround once the PR to Formik is merged: https://github.com/jaredpalmer/formik/pull/939
CodeSandbox: https://codesandbox.io/s/pk7mk0nny0

fix(money-input): add formatting workaround

---

i18n/core.json
i18n/de.json
i18n/en.json
i18n/es.json
src/components/fields/money-field/messages.js
src/components/fields/money-field/money-field.form.story.js
src/components/fields/money-field/money-field.js
src/components/fields/money-field/money-field.spec.js
src/components/fields/money-field/money-field.story.js

- Removes the ability to pass in a badge manually
- Adds the `showHighPrecisionBadge` prop which will show the "high precision price" badge in case a high-precision price was entered.

feat(money-field): add high-precision price badge

---

src/components/inputs/money-input/money-input.js
src/components/inputs/money-input/money-input.spec.js

Validation was still being called with invalid values in case the user enters a perfectly formatted amount before selecting a currency.
<a href="https://cl.ly/81ddf56d1348" target="_blank"><img src="https://dzwonsemrish7.cloudfront.net/items/1k2v0P1X0t0J020S1W2f/Screen%20Recording%202018-09-28%20at%2009.49%20AM.gif" style="display: block;height: auto;width: 100%;"/></a>
This workaround can also be removed once https://github.com/jaredpalmer/formik/pull/939 is released.

Fix lost updates of MoneyInput for Formik validation

---

materials/tokens/backgrounds.mod.css
materials/tokens/borders.mod.css
materials/tokens/shadows.mod.css
materials/tokens/sizes.mod.css
src/components/internals/select.css
src/components/tag/tag.mod.css

As a followup to https://github.com/commercetools/ui-kit/pull/112, here we get rid of the plural naming and follow the singular standard

renames all `Tag` tokens from plural to singular

---

src/components/inputs/async-select-input/README.md
src/components/inputs/async-select-input/async-select-input.js
src/components/inputs/async-select-input/async-select-input.story.js
src/components/inputs/select-input/select-input.story.js

- explicitly declares props of `AsyncSelectInput`
- moves `AsyncSelectInput` out of beta
- fixes an issue in `SelectInput` which was still using `autoFocus` instead of `isAutofocussed`
See #119 for more information. This is basically the same change, but for `AsyncSelectInput`.

AsyncSelectInput: explicitly declare props

---

src/components/inputs/creatable-select-input/README.md
src/components/inputs/creatable-select-input/creatable-select-input.js
src/components/inputs/creatable-select-input/creatable-select-input.story.js

- Explicitly declares props of `CreatableSelectInput`
- Moves `CreatableSelectInput` out of beta
- Adapts story and README

CreatableSelectInput: explicitly declare props

---

src/components/inputs/async-creatable-select-input/README.md
src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
src/components/inputs/async-creatable-select-input/async-creatable-select-input.story.js

- move `AsyncCreatableSelectInput` out of beta
- explicitly declare props
- adapt docs and spec
Same as #119 but for `AsyncCreatableSelectInput`.

AsyncCreatableSelectInput: explicitly declare props

---

.storybook/webpack.config.js
rollup.config.js

Icons are completely broken in master at the moment. Check [storybook](https://uikit.commercetools.com/?selectedKind=Icons&selectedStory=All%20Icons&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel) and try to change the colour. You should notice that the colours don't actually change.
If you look at the output of the pre a few weeks ago build, you'll notice that the svg output was slightly different, and wasn't including the stroke and the fill. So I added removeAttr for it.

fix(bundling): add svg config for icons

---

src/components/typography/text/text.js
src/components/typography/text/text.mod.css
src/components/typography/text/text.spec.js
src/components/typography/typography.story.js

The `isInline` prop is currently broken for `Text` components. 
Inline seems to be some sort of reserved word in `stage 2` of `postcss-preset-env`. That's as far as my investigation got. If you switch to stage 3, then this doesn't happen. However, this doesn't happen in our webpack build, only in our rollup build.
when we build ui-kit with webpack (for storybook), it takes the following css
```
.inline {
display: inline-block;
}
```
and it turns it into something like this
```
{
inline: 'inline_mod_blah'
}
```
when we build ui-kit with webpack (for production), it takes the following css
```
.inline {
display: inline-block;
}
```
and it turns it into something like this
```
{
inline-left: 'inline_mod_blah',
inline-right: 'inline_mod_blah',
}
```
It must be some sort of reserved word or …

fix: fix inline text 

---

package.json
src/components/buttons/icon-button/icon-button.js
src/components/buttons/secondary-button/secondary-button.js
src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
src/components/icons/with-theme-prop.js
src/components/inputs/money-input/money-input.js
src/components/inputs/number-input/number-input.js
src/components/panels/collapsible-panel/collapsible-panel.spec.js
src/components/switches/checkbox/checkbox.spec.js
src/components/switches/radio/radio-group.js
src/components/switches/radio/radio-group.spec.js
src/components/switches/radio/radio-option.spec.js
src/utils/localized.js
yarn.lock

This pull request replaces `invariant` with [`tiny-invariant`](https://github.com/alexreardon/tiny-invariant). A simpler, more lightweight solution. Not the biggest of our problems but it was on my list. Essentially `tiny-invariant` as the same API but does not allow placeholders in the string. Something we never used an if would use template literals for anyway.

refactor: replace invariant with tiny-invariant

---

package.json
rollup.config.js

Now we are treating every single dependancy as a peer dep. This isn't sustainable, since users don't want to install a small lodash module everytime we add one. It only makes sense to treat large dependencies as peer dependencies. 
`flatpickr`, `react-select`, `react-textarea-autosize`, `react-virtualized` and `styled-components` are moved to peer deps, the rest stay as deps, and remove the rollup config that treats all deps as peer deps.
This increases the bundle size from 614kb -> 813kb, but I think the trade off is worth it.

feat: bundle small deps, explicitly peer dep others.

---

.storybook/decorators/intl/intl.js
src/components/fields/async-creatable-select-field/async-creatable-select-field.form.story.js
src/components/fields/async-select-field/async-select-field.form.story.js
src/components/fields/creatable-select-field/creatable-select-field.form.story.js
src/components/fields/money-field/money-field.form.story.js
src/components/fields/multiline-text-field/multiline-text-field.form.story.js
src/components/fields/number-field/number-field.form.story.js
src/components/fields/select-field/select-field.form.story.js
src/components/fields/text-field/text-field.form.story.js
src/components/inputs/async-creatable-select-input/async-creatable-select-input.form.story.js
src/components/inputs/async-creatable-select-input/async-creatable-select-input.story.js
src/components/inputs/async-select-input/async-select-input.form.story.js
src/components/inputs/async-select-input/async-select-input.story.js
src/components/inputs/creatable-select-input/creatable-select-input.form.story.js
src/components/inputs/creatable-select-input/creatable-select-input.story.js
src/components/inputs/date-input/date-input.story.js
src/components/inputs/date-time-input/date-time-input.story.js
src/components/inputs/money-input/money-input.form.story.js
src/components/inputs/number-input/number-input.form.story.js
src/components/inputs/select-input/select-input.form.story.js
src/components/inputs/select-input/select-input.story.js
src/components/inputs/time-input/time-input.story.js

So far we've been redefining `IntlProvider` for almost every story. Sometimes we added a knob to be able to change the locale. This is repetitive, cumbersome and in some cases unnecessary as we already have global `intl` decorator which wraps all stories in `IntlProvider` anyways.
I now refactored our global `intl` decorator to include a knob for selecting a locale. This means all stories now have a "global locale" selector and they don't need to define `IntlProvider` anymore.
Check out `.storybook/decorators/intl/intl.js` for the changed setup. The other changes are removing the unnecessary `IntlProvider` from all stories.
<sup>Intermediate loss of functionality: One thing to note is that `DateInput`, `DateTimeInput` and `DateRangeInput` were accessing the selected locale directly and …

docs: add global locale knob

---

.eslintrc.yaml

Specifies React version for `eslint-plugin-react` in `.eslintrc.yaml` to avoid a warning.
We use `detect` so that we don't need to upgrade the settings every time we upgrade React. The `detect` option was added to  `eslint-plugin-react` in https://github.com/yannickcr/eslint-plugin-react/pull/1978.
**Before**
see https://travis-ci.org/commercetools/ui-kit/builds/442629522?utm_source=github_status&utm_medium=notification
**After**
see https://travis-ci.org/commercetools/ui-kit/builds/442636937?utm_source=github_status&utm_medium=notification

chore: specify React version for eslint-plugin-react

---

package.json
rollup.config.js
yarn.lock

While working on #170, I found a quick way to improve our bundle.
We are using [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) to import css variables from other files. This is a common approach in most of our `mod.css`
```
@import '../../../../materials/colors/base-colors.mod.css';
h1.my-class {
color: var(--color-green);
}
```
and the current output is as follows.
```
/* stylelint-disable comment-empty-line-before */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
This file is created by 'scripts/generate-base-color.js' script. The real
colors's values should be updated in '../materials/colors/decisions/base-colors.json';
Also, This file is transformed to JSON version in order to list the colors
in the UIKit. Color groups are indicated …
```

feat(bundling): lower bundle size by discarding comments 

---

src/components/inputs/money-input/currency-dropdown.js
src/components/inputs/money-input/dropdown-chevron.js
src/components/inputs/money-input/money-input.mod.css

Fixes the alignment of the caret in `MoneyInput` when no currency is selected. Further makes the whole left side clickable.
**Before**
**After**
Follow-up of #171

Fix MoneyInput caret alignment & clickable area

---

examples/form-fields.story.js
examples/form-inputs.story.js
src/components/fields/money-field/money-field.form.story.js
src/components/fields/money-field/money-field.js
src/components/fields/money-field/money-field.spec.js
src/components/inputs/money-input/README.md
src/components/inputs/money-input/currency-dropdown.js
src/components/inputs/money-input/currency.spec.js
src/components/inputs/money-input/money-input.form.story.js
src/components/inputs/money-input/money-input.js
src/components/inputs/money-input/money-input.spec.js
src/components/inputs/money-input/money-input.story.js

The old `MoneyInput` was capable of displaying an error either on the currency dropdown or the amount input:
| `hasCurrencyError` | `hasAmountError` |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1765075/47153443-f54ffc80-d2df-11e8-9d8e-3c0cee19daae.png) | ![image](https://user-images.githubusercontent.com/1765075/47153457-faad4700-d2df-11e8-8493-facb69476762.png) |
After talking to @filippobocik we agreed to drop the individual error states from `MoneyInput`. `MoneyInput` will now only accept `hasError` (and `hasWarning`)  instead of  `hasCurrencyError` and `hasAmountError`.
```diff
<MoneyInput
- hasAmountError={true}
- hasCurrencyError={true}
- hasAmountWarning={true}
- hasCurrencyWarning={true}
+ hasError={true}
+ hasWarning={true}
/>
```
This makes the code …

Redo MoneyInput (better UX, less error cases)

---

package.json
scripts/get-babel-preset.js
src/components/collapsible-motion/README.md
src/components/collapsible-motion/collapsible-motion.js
src/components/collapsible-motion/collapsible-motion.spec.js
src/components/collapsible-motion/collapsible-motion.story.js
yarn.lock

As described in #21 we were including all of  `styled-components` and making it a peer dependency just for the sake of one single component called `CollapsibleMotion`.
The task of `CollapsibleMotion` is not an easy one, as it needs to animate a components height from `0` to `auto` and vice versa. This is a really difficult animation, as browsers don't allow to animate to `auto` - because it is really expensive. There is [one long article](https://css-tricks.com/using-css-transitions-auto-dimensions/) which goes into detail of different approach to this problem and their downsides. None of them are pretty.
`CollapsibleMotion` solves this problem in a clever way as it dynamically injects keyframes to be able to animate. It also sets the height to the measured height and then, only on the …

Drop styled-components peerDep (Redo CollapsibleMotion)

---

.storybook/config.js
src/index.js

To fulfill the **intermediate suggestion** of #185, we propose importing the global css (`reset.mod.css` and `grid.mod.css`) in the `index.js` file.
Then, we can move on to a more permanent solution.
This way regression testing can be introduced before the permanent solution.
**Release notes** Consumers of ui-kit no longer need to `import '../materials/internals/reset.mod.css';` and `import '../materials/internals/grid.mod.css';`.

chore: self contain styles intermediate solution

---

materials/internals/reset.mod.css

Before #186 , we had
```
import '../materials/internals/reset.mod.css';	
import './main.mod.css';	
```
This meant that the `overflow: auto` took precedence over `overflow: hidden` in `reset.mod.css`. 
By importing `reset.mod.css` in `index.js`, this order of precedence changed.
Remove overflow: hidden in `reset.mod.css` because this shouldn't be in UI-Kit anyways.
**Release notes** Consumers which were relying on `overflow: hidden` on `body` now need to define this themselves.

fix: allow scrolling in icon story

---

src/components/internals/clear-indicator/clear-indicator.js
src/components/internals/create-select-styles.js
src/components/internals/dropdown-indicator/dropdown-indicator.js

Fixes alignment of indicator icons in `SelectInput`, `CreatableSelectInput`, `AsyncSelectInput` & `AsyncCreatableSelectInput`  after it broke in #182.
Before
After
I also changed both icons to have size `medium`. Previously one was `small` and the other was `medium`.

fix(*-select-input): align indicator icons of clearable select-inputs

---

package.json
playground/.babelrc
playground/.eslintrc.yaml
playground/README.md
playground/src/index.js
playground/src/playground.js
playground/webpack.config.js
yarn.lock

Adds a playground which allows testing the final build manually.
The playground can be started with `yarn playground`. It will test the production bundle of `ui-kit` - which needs to be built with `yarn build` or `yarn build:watch` first.
The playground contents themselves are currently pretty minimal. We can render more components, make the components interactive or add routing there at some point. For now I'm happy just having a place where we can try components out without on their own.
In the future, we might use the playground setup to export the UI Kit to Sketch using [`html-sketchapp`](https://github.com/brainly/html-sketchapp). We had a working proof-of-concept a while back but we didn't merge it back then because there were some problems with it still.
This relates to #187.

Add playground

---

.eslintrc.yaml
.travis.yml
jest.bundle.config.js
package.json
src/index.bundlespec.js
test/replace-module-paths.js
test/transform-babel-jest.js
yarn.lock

So far it was not possible to test the produced ui-kit bundle. This left us blind when errors happened within the bundling process (e.g. when updating the rollup config).
This PR adds a way to test the produced `dist/ui-kit.esm.js` bundle.
There are now two types of tests, which can both be placed anywhere in the code-base:
- `*.spec.js`: The regular tests for the sources
- `*.bundlespec.js`: Tests for the produced bundle
- These tests use Jest to transpile the source code of the file-under-test
- It is possible to mock other source files in these tests
- These tests can not catch errors in the build process
- These tests can not test the final bundle
- These tests use the produced final bundle (they don't need transpilation on modern envs)
- It is **not** possible to mock parts of ui-kit …

Add bundle tests setup

---

src/components/typography/text/README.md
src/components/typography/text/text.js
src/components/typography/text/text.spec.js
src/components/typography/typography.story.js

`Text.*` components provides a way to truncate long texts by setting `truncate` prop to true. And when using this feature it's a very common scenario to show full version of truncated text in a tooltip on hover. Which leads to code like this all around the place:
```js
<div titile={longText}>
<Text.Detail truncate>{longText}</Text.Detail>
</div>
```
I suggest to add `tooltip` prop to all the `Text` component to prevent adding unnecessary markup elements. So that example above would look like:
```js
<Text.Detail truncate title={longText}>{longText}</Text.Detail>
```
The only thing I am not sure about is whether it worth adding `title` prop to `Text.Wrap` component, as it not provide truncation behaviour. But I added it to make API across all the `Text.*` components consistent.

feat(typography): add `title` prop to all typography components

---

src/components/inputs/money-input/money-input.js
src/components/inputs/money-input/money-input.mod.css
src/components/inputs/money-input/money-input.spec.js

A few CSS fixes to fix the problems `ellipses are shown for the currency code even for short currencies like EUR` and `inputs look different in Safari`.
However, due to Firefox limitations, it's not possible to have a correct format on blur functionality on firefox, as firefox number inputs don't allow extra zeros. So the input has been changed to type "text"
* Fixes #205 
* Fixes focus so that the input acts as one input with regards to focus and error states.

Money Input Fixes

---

materials/media-queries.mod.css

To make our media queries compatible with version 7 of postcss-custom-media.
After this is merged and released, we will update our webpack-config in `merchant-center-application-kit` to 
```js
postcssCustomMediaQueries({
preserve: false,
importFrom: [
require.resolve(
'@commercetools-frontend/ui-kit/materials/media-queries.mod.css'
),
],
}),
```
and update `postcss-custom-media` to version 7.0.6 (important), and remove the resolution for version 6 in the MC.
and then we can remove all of the @import's of media queries in the MC.

fix: remove root from media queries

---

src/components/inputs/money-input/money-input.js
src/components/inputs/money-input/money-input.spec.js
src/test-utils.js

Adds thousand-separator formatting to `MoneyInput`.
This is still missing tests and coordination with UX.
Makes it easier to read big amounts by adding thousand-separators.
Parsing
- Since most users are not careful about how they enter values, we will parse both `.` and `,`
- When a value is `1.000,00` we parse it as `1000`
- When a value is `1,000.00` we also parse it as `1000`
- This means the highest amount always wins
- We do this by checking comparing the last position of `.` and `,`. Whatever is later is used as the decimal separator
**Breaking change** The `MoneyInput.parseMoneyValue` now requires callers to pass a `locale` as the second argument, so that the value can be formatted according to the users locale initially.
Closes #215

feat: add MoneyInput value formatting

---

src/components/inputs/money-input/money-input.js
src/components/inputs/money-input/money-input.spec.js

When users selected the currency EUR (or any other with 2 fraction digits) and typed certain numbers like `2.49`, the `MoneyInput.convertToMoneyValue` would determine an incorrect `centAmount` due to rounding errors as @adnasa hinted at in https://github.com/commercetools/ui-kit/pull/221#issuecomment-437869330.
This PR fixes that by ensuring `centAmount` is an integer.

fix(money-input): avoid rounding errors

---

.prettierignore
src/index.js

As discussed in https://github.com/commercetools/ui-kit/pull/232#discussion_r233530478, this removes the exclusion of `src/index` from prettier.

chore: stop excluding src/index.js from prettier

---

.travis.yml
CHANGELOG.md
README.md
materials/internals/tokens/README.md
package.json
src/components/inputs/money-input/README.md

So far our releases were not following semver and it was cumbersome to test new releases. This PR changes that by releasing to `next` from CI. Check the changed documentation in this PR to find out more.

Release v3.0.0 & establish release practices

---

package.json
yarn.lock

Moves peer deps to regular deps, so apps don't need to explicitly list our deps as their deps.

fix: move peer deps to deps

---

.storybook/manager-head.html

#261 introduced a syntax error to the document head. I wanted to fix it in https://github.com/commercetools/ui-kit/commit/f0e333e805ae05c5f6db398e0f81ecc785de18f4 which I pushed directly onto `master` (by accident).
I now set up branch protection rules so this doesn't happen again. For some reason prettier automatically added the final semi-colon which this PR removes. It might be a bug in prettier when used with an html file.
This PR removes the semi colon.

fix(storybook): set title (remove semi colon error)

---

src/index.js

Looks like we forgot to include this export 🙈

chore: add avatar export

---

src/index.js

This pull request proposes to remove the `Icons.*` export.
The export has been creating great confusion recently and I suggest to remove it for the following reasons:
1. It breaks tree shaking as all icons are imported (in case of SVG causing some unexpected bundle weight to consumers)
2. It's convenient but not really needed in most cases
- Currently a mapping could be implemented by switching on strings and returning a specifically imported icon
Future work could entail adding a generic component to UIKit which looks like `<Icon name='circle' />` which does the mapping. However that will also break tree shaking for consumers.

Remove `Icons.AX` export

---

rollup.config.js

At some point between v3.0.0 and v4.0.2, we moved some deps from peer deps to regular deps. We assumed all of our deps were being externalized, since we had included `dependencies: true` in our rollup config of [rollup-plugin-peer-deps-external](https://www.npmjs.com/package/rollup-plugin-peer-deps-external). However, this was a typo because it should be `includeDependencies: true`.
Please don't git blame this because I'm 100% sure I'm guilty of introducing this 🙈 
Fix typo.

fix: typo in rollup config

---

.travis.yml

If the tests fail on CI, the apps still build. See [here](https://travis-ci.org/commercetools/ui-kit/builds/462944149) for an example.
Add `set -e` to the beginning of our scripts (instructs bash to quit if there is an error), and add `set +e` to unset the flag at the end of our scripts, as travis can sometimes have internal scripts that exit with a non zero code that we wouldn't result in our build failing.
Check [here](https://travis-ci.org/commercetools/ui-kit/builds/463355886) for an example of this PR resulting in a fail fast.
[https://github.com/travis-ci/travis-ci/issues/1066](https://github.com/travis-ci/travis-ci/issues/1066)

Fail Fast on Travis CI

---

CHANGELOG.md
package.json

Bumps version to 4.0.3 to release next with [rollup config fix](https://github.com/commercetools/ui-kit/pull/279).

chore: bump version to 4.0.3 and update changelog

---

src/components/switches/checkbox/checkbox.mod.css
src/components/switches/checkbox/checkbox.percy.js
src/components/switches/radio/radio-option.mod.css
src/components/switches/radio/radio.percy.js

We were using SVG ids to apply css styling to some of our svgs in the components `checkbox` and `radio`. However, at some point in the last period of time since we last checked to see if this worked, SVGO moved to making SVG id's unique, by prepending them with the file name.
We give id="borderAndContent", and SVGO outputs id="radio-option-default_react_svg__borderAndContent". 
Use regex to target the id. [ref](https://stackoverflow.com/questions/8903313/using-regular-expression-in-css)
Add VRT tests for the two components.

Fix for Checkbox and Radio hovered, disabled states

---

.travis.yml

Snapshots are precious. If we run `yarn percy` on every CI build, we will run out of snapshots. 😢 
Skip percy on non PRs.

chore: skip percy on non prs

---

src/components/inputs/date-input/date-input.form.story.js
src/components/inputs/date-input/date-input.js
src/components/inputs/date-time-input/date-time-input.form.story.js
src/components/inputs/date-time-input/date-time-input.js
src/components/inputs/time-input/time-input.form.story.js
src/components/inputs/time-input/time-input.js
src/components/internals/calendar-menu/calendar-menu.mod.css

| ------- | ----- |
| ![image](https://user-images.githubusercontent.com/1765075/49732280-5f50a680-fc7e-11e8-9183-1c4b30cce8d2.png) | ![image](https://user-images.githubusercontent.com/1765075/49732301-6c6d9580-fc7e-11e8-9cbb-99b1d98a81dc.png) |
Previously it wasn't possible to format the initial value of `TimeInput`. The `toLocaleTime` function was moved to a static method to allow using it in `docToForm`.
There as a problem where the calendar would open on the current date instead of the date of the currently selected value. This was caused as we were using the logic of the date-range-input by accident. I removed it now.
When the `DateInput` / `DateTimeInput` was blurred, the blur event did not contain `target.id` or `target.name` which result in Formik printing a …

Multiple smaller fixes for date related inputs

---

src/components/typography/text/README.md
src/components/typography/text/text.js
src/components/typography/text/text.spec.js
src/components/typography/typography.story.js

Adding `data-test` prop to every `Text` component.
Adding `data-test` prop to avoid wrapping `Text` components for E2E tests

Typography (Text): adding data test prop to text components

---

.travis.yml
scripts/run-percy.sh

If `renovate` opens an average of 6 PRs per week, that means, 24 PRs per month.
24 * ~50 snapshots = 1200, or almost 25% of our current percy snapshot allowances.
These robots must be stopped.
🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖

Don't run `yarn percy` when PR is opened by 🤖

---

src/components/inputs/multiline-text-input/multiline-text-input.spec.js
src/components/inputs/text-input/text-input.spec.js

Refactors `multiline-text-input` to use `react-testing-library`.
I couldn't figure out how to work out how to test the open / closed states of the component, mostly due to `react-textarea-autosized` not being able to calculate the nodeHeight in the js-dom environment. Do you have any ideas @pa3 ?

chore: refactor multiline-text-input to use rtl

---

examples/form-fields.story.js
src/components/fields/async-creatable-select-field/README.md
src/components/fields/async-creatable-select-field/async-creatable-select-field.js
src/components/fields/async-select-field/README.md
src/components/fields/async-select-field/async-select-field.js
src/components/fields/creatable-select-field/README.md
src/components/fields/creatable-select-field/creatable-select-field.js
src/components/fields/localized-multiline-text-field/README.md
src/components/fields/localized-multiline-text-field/localized-multiline-text-field.js
src/components/fields/localized-text-field/README.md
src/components/fields/localized-text-field/localized-text-field.js
src/components/fields/money-field/README.md
src/components/fields/money-field/money-field.form.story.js
src/components/fields/money-field/money-field.js
src/components/fields/money-field/money-field.spec.js
src/components/fields/money-field/money-field.story.js
src/components/fields/multiline-text-field/README.md
src/components/fields/multiline-text-field/multiline-text-field.form.story.js
src/components/fields/multiline-text-field/multiline-text-field.js
src/components/fields/multiline-text-field/multiline-text-field.spec.js
src/components/fields/number-field/README.md
src/components/fields/number-field/number-field.form.story.js
src/components/fields/number-field/number-field.js
src/components/fields/number-field/number-field.spec.js
src/components/fields/select-field/README.md
src/components/fields/select-field/select-field.js
src/components/fields/text-field/README.md
src/components/fields/text-field/text-field.form.story.js
src/components/fields/text-field/text-field.js
src/components/fields/text-field/text-field.spec.js

We were reexporting the static methods of input elements on field elements for convenience. This caused more confusion and overhead than just forcing consumers to use the statics of the input elements instead.
BREAKING: Removes reexported static methods from fields. Use the static methods of the respective inputs instead.
Closes #315

feat(fields): remove reexport of static methods

---

src/components/fields/date-field/README.md
src/components/fields/date-field/date-field.js
src/components/fields/date-field/date-field.percy.js
src/components/fields/date-field/date-field.spec.js
src/components/fields/date-field/date-field.story.js
src/components/fields/date-field/index.js
src/components/inputs/date-input/README.md
src/components/inputs/date-input/date-input.js
src/index.js

Add `DateField` component.
*I did not add Visual Regression Tests yet as we're awaiting #293.*
- Documentation
- Props
- Design
- Testing
- Accessibility (optional)

Add DateField component

---

src/components/tag/tag.mod.css
src/components/tag/tag.percy.js

Fixes #323 
* Sets min height
* Adds padding so that multiline tags have a consistent appearance with single line tags.
Check the VRT diff

Allow tags to be flexible in height

---

.travis.yml

We ran over the limit now
> $ react-percy
> Compiling...
> Uploading 48 snapshots to Percy
> Error: This organization has exceeded the limits of the (unactivated) plan. Administrators can upgrade here: https://percy.io/organizations/commercetools-GmbH/billing
We can't upgrade using their UI as we are one a custom plan at the moment (since we signed up through GitHub). I already reached out to their support and requested to be moved to a different plan. We will reenable Percy once the bigger plan is activated or when the next month starts and the budget is reset in case we were not upgraded in the meantime.
cc @montezume FYI

Temporarily disable percy

---

.travis.yml

This reactivates percy after we had to temporarily disable it in #343.
We are now on a plan where we're allowed to run over the number of monthly snaps so the situation that we need to open a PR and disable Percy won't happen again 🙏

Revert "chore: temporarily disable percy (#343)"

---

src/components/fields/date-range-field/README.md
src/components/fields/date-range-field/date-range-field.js
src/components/fields/date-range-field/date-range-field.percy.js
src/components/fields/date-range-field/date-range-field.spec.js
src/components/fields/date-range-field/date-range-field.story.js
src/components/fields/date-range-field/index.js
src/index.js

Add DateRangeField

---

src/components/inputs/async-creatable-select-input/async-creatable-select-input.spec.js
src/components/inputs/async-select-input/async-select-input.spec.js

Convert `AsyncSelectInput` and `AsyncCreatableSelectInput` to `react-testing-library`.
I copied the tests of `SelectInput` and `CreatableSelectInput` and converted them to work with async values. It was pretty straightforward. The biggest "gotcha" was that I had to add a `defaultOptions={true}` to make `react-select` load the default options without having to type anything first.

Convert AsyncSelectInput and AsyncCreatableSelectInput tests

---

src/components/fields/money-field/money-field.js
src/components/fields/money-field/money-field.percy.js
src/components/fields/money-field/money-field.spec.js
src/components/fields/money-field/money-field.story.js
src/components/inputs/money-input/money-input.js
src/components/inputs/money-input/money-input.mod.css
src/components/inputs/money-input/money-input.percy.js
src/components/inputs/money-input/money-input.spec.js
src/components/inputs/money-input/money-input.story.js

Closes #330 
* Adds `isAutofocussed` prop to `<MoneyInput>` and `<MoneyField>`
* Adds `isReadOnly` prop  to `<MoneyInput>` and `<MoneyField>`
* `<MoneyInput>`: Wraps `SingleValue` of react-select with a label pointing at the currencyCode input, so that it can be targeted using RTL.

Add `isAutofocussed` and `isReadOnly` to `MoneyInput` and `MoneyField`

---

src/components/field-errors/README.md
src/components/field-errors/field-errors.js
src/components/field-errors/field-errors.spec.js
src/index.js

- exports the `FieldErrors` component
- adds `FieldErrors.errorTypes` constants which aim to make code of consumers easier to follow by avoiding "magic" keys like `missing` in the errors object by showing the constants instead (non-breaking change)
- adds `react-testing-library` tests for the public API
- adds `README`
I didn't add a story as this component doesn't have any visuals itself (apart from rendering `ErrorMessage` which is already tested separately).
Closes #246

Export FieldErrors component

---

scripts/get-babel-preset.js

@tdeekens made a good write up about the problem [here](https://github.com/commercetools/merchant-center-application-kit/issues/228).
TL;DR: It will be easier for our consumers to use `ui-kit` if they get prop-types warnings during development.
Use mode `wrap` from [babel-plugin-transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types).
Which transforms our propTypes into 
```js
var nonEmptyString = process.env.NODE_ENV !== "production" ? function (props, propName, componentName) {
var value = props[propName];
if (typeof value === 'string' && !value) return new Error("Invalid prop '".concat(propName, "' supplied to '").concat(componentName, "'. Expected it to be nonempty string, but it was empty."));
return null;
} : {};
// more …
```

chore: keep prop-types if mode is not production

---

package.json
yarn.lock

Rollup v1 is [released](https://github.com/rollup/rollup/releases/tag/v1.0.0).
Update rollup. Run tests. Run VRT tests. If VRT tests pass, we should be good.

chore: update rollup to v1

---

package.json
yarn.lock

😆 
In #373 we removed `@react/percy`, which had a dev dependency on webpack 3, which has `json-loader`, so  `json-loader` was removed as well.. Storybook couldn't be built because of this. Here I readded json-loader.

chore: fix storybook

---

src/components/panels/collapsible-panel/collapsible-panel.js
src/components/panels/collapsible-panel/collapsible-panel.spec.js

This has bugged me for awhile. You should be able to toggle the `CollapsiblePanel` by clicking anywhere in the header.

chore(collapsible-panel): move onClick in header

---

src/components/internals/calendar-menu/calendar-menu.mod.css

Make z-index of open datepickers to be the same as flatpickrs, to make old behaviour of ui-kit datepickers.
[ref](https://github.com/flatpickr/flatpickr/blob/7012a3b025c6aea05e955004082d160ea7f67535/src/style/flatpickr.styl#L50)

fix(date-inputs): make date-input have large z-index

---

src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
src/components/dropdowns/primary-action-dropdown/primary-actions-dropdown.mod.css

Use font-color gray-60 when input is disabled (when all options are disabled) as requested by @filippobocik.
| ---- | --- |
| ![image](https://user-images.githubusercontent.com/1765075/50836678-131a8400-135a-11e9-8f29-401da02cdad9.png) | ![image](https://user-images.githubusercontent.com/1765075/50836687-19106500-135a-11e9-8fa1-12bda3c3a7d7.png) |

fix(primary-action-dropdown): use secondary tone when disabled

---

src/components/inputs/money-input/money-input.js
src/components/internals/clear-indicator/clear-indicator.js
src/components/internals/create-select-styles.js
src/components/internals/dropdown-indicator/dropdown-indicator.js

Change caret size in select inputs and avoid jumping of clear icon.
| Before | After | 
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/1765075/50839414-8a531680-1360-11e9-9f6e-29101902b644.png) |  ![image](https://user-images.githubusercontent.com/1765075/50839449-a060d700-1360-11e9-9d93-89a4b3e7422e.png) |
Fixes `SelectInput` `CreatableSelectInput` `AsyncSelectInput` `AsyncCreatableSelectInput`
Also fixes `MoneyInput`
| Before | After | 
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/1765075/50840242-52e56980-1362-11e9-80fb-d297486e75ba.png) | ![image](https://user-images.githubusercontent.com/1765075/50840214-4a8d2e80-1362-11e9-85f9-d7e628c5a0fa.png) |

Change caret size in select inputs and MoneyInput

---

src/components/inputs/money-input/money-input.mod.css

Use narrow styling when no currencies are passed
| --- | --- |
| ![bildschirmfoto 2019-01-08 um 16 39 27](https://user-images.githubusercontent.com/1765075/50841076-31857d00-1364-11e9-990d-654cdaeac904.png) | ![bildschirmfoto 2019-01-08 um 16 39 09](https://user-images.githubusercontent.com/1765075/50841075-30ece680-1364-11e9-8f94-f4ef8abc4a6e.png) |
There are two modes the `MoneyInput` can be used in:
- letting users select currency and amount (`currencies` prop is passed, even when it only contains one currency)
- letting users select an amount only (`currencies` prop is not passed, but `value` already has `value.currencyCode` set to a currency)
Previously, we were setting a min-width for the case where the currency can't be selected. @filippobocik has requested to …

fix(money-input): use narrow styling when no currencies are passed

---

src/components/typography/text/text.js

Is leading to some prop-type warnings in mc-fe now.

fix(text): add missing inverted prop to prop-types of text-detail

---

src/components/switches/radio/radio-group.js
src/components/switches/radio/radio-option.js

To make the Radio more inline with how our consumers are using it, we should update the proptype "value" to accept either booleans or strings. 
This is how it's currently being used by the PCM team

chore: update proptype of Radio

---

src/components/inputs/async-creatable-select-input/async-creatable-select-input.spec.js
src/components/inputs/async-select-input/async-select-input.spec.js
src/components/inputs/creatable-select-input/creatable-select-input.spec.js
src/components/inputs/date-range-input/date-range-input.js
src/components/inputs/date-time-input/date-time-input.js
src/components/inputs/localized-money-input/localized-money-input.spec.js
src/components/inputs/select-input/select-input.spec.js
src/components/inputs/time-input/time-input-body.js
src/components/internals/calendar-body/calendar-body.js
src/components/internals/calendar-menu/calendar-menu.js
src/components/switches/checkbox/checkbox.js
src/components/switches/radio/radio-option.js
src/components/switches/toggle/toggle.js

If you run `yarn lint` on the master branch, we get a bunch of errors.
This PR fixes those errors.
It also moves the `filter-data-attributes` on `Switch`, `RadioOption` and `Checkbox` to the underlying input.

fix(radio-option, checkbox, switch): move data-attributes to input

---

src/components/messages/error-message/error-message.js
src/components/messages/error-message/error-message.spec.js

@amine-benselim reported that `ErrorMessage` didn't support data-foo attributes.
Make it support data-attributes.

fix(error-message): support data-attributes

---

src/components/inputs/time-input/time-input.js
src/components/inputs/time-input/time-input.spec.js

If `TimeInput` is used without an `id` prop, we should call onChange with the generated sequential id.

fix(time-input): call onChange with generated ID if none passed

---

src/components/inputs/localized-money-input/README.md
src/components/inputs/localized-money-input/localized-money-input.js
src/components/inputs/localized-money-input/localized-money-input.spec.js
src/components/inputs/localized-money-input/localized-money-input.story.js
src/components/inputs/localized-money-input/localized-money-input.visualroute.js

- Re-define component values as object of `{amount, currencyCode}`
This PR re-defines the `values` prop expected by the `LocalizedMoneyInput` as an object of `{amount, currencyCode}`. This PR changes the required values 
**from**:
```
{EUR: '12.00', USD: '25.00'}
```
**to**:
```
{EUR: {
amount: '12.00',
currencyCode: 'EUR',
},
USD: {
amount: '25.00',
currencyCode: 'USD',
}}
```
This is required to keep the change event signature consistent with the event from the contained `MoneyInput` components.
| Before  | After   |
| :------ | :------ |
|![localized-money-input-onchange-before](https://user-images.githubusercontent.com/3065138/50902344-e67a7100-141a-11e9-8467-143cdc27116c.gif)|![localized-money-input-onchange-v2-after](https://user-images.githubusercontent.com/3065138/50902355-ef6b4280 …

fix(localizedmoneyinput): remove 'amount/currencyCode' from event name

---

src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.visualroute.js
src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.visualspec.js
src/components/fields/async-creatable-select-field/async-creatable-select-field.visualroute.js
src/components/fields/async-creatable-select-field/async-creatable-select-field.visualspec.js
src/components/fields/async-select-field/async-select-field.visualroute.js
src/components/fields/async-select-field/async-select-field.visualspec.js

Adds interaction VRT tests for `PrimaryActionDropdown`, `AsyncSelectField` and `AsyncCreatableSelectField`. 
I could use some feedback for these tests and the approach before we go on and add interaction VRT tests for more components.

chore: adds a few interaction based VRT tests

---

.eslintrc.yaml
.travis.yml

Currently, we **aren't** running our linters on CI.
We had some lint errors make their way into master awhile ago, and they had to be fixed in #423.
Make travis run our linters again.

chore: have ci run lint

---

src/components/icons/icons.visualroute.js
src/components/icons/icons.visualspec.js

Currently we are taking one percy snapshot for all of our icons in all of their states, leading to a webpage with a ridiculous height, and when percy snapshots it, it gets cut off.
Take one snapshot per `theme`. This way we use 8 snapshots for icons, but we can ensure that all icons are included in the snapshot.
Closes #437

chore: update vrt tests for icons

---

src/components/inputs/money-input/money-input.js
src/components/inputs/money-input/money-input.spec.js

Certain values get rounded on blur:
We run into JavaScript floating point number problems with our current calculations.
We are executing `amountAsNumber * 10 ** fractionDigitsOfAmount` which boils down to e.g. `8.066652 * 10 ** 6` for a high-precision price. However this is where we're running into floating point problems:
The function above converts `8.066652` into `8066652`
We avoid floating point math problems by using string manipulation to get the `preciseAmount` instead.
---
Affects: `MoneyInput`, `MoneyField`, `LocalizedMoneyInput`, `LocalizedMoneyField`

fix(money-input): avoid messing with floating point numbers

---

.storybook/webpack.config.js
package.json
yarn.lock

I noticed that when we build storybook, it's including all the moment locales and (I think), slowing it down a bit. So I added the plugin to strip out unused locales.

chore: speed up storybook build

---

package.json
src/components/buttons/icon-button/icon-button.js
src/components/buttons/secondary-button/secondary-button.js
src/hocs/with-mouse-down-state/with-mouse-down-state.js
src/hocs/with-mouse-over-state/with-mouse-over-state.js
src/hocs/wrap-display-name/index.js
src/hocs/wrap-display-name/wrap-display-name.js
src/hocs/wrap-display-name/wrap-display-name.spec.js
yarn.lock

This pull request removes the dependency on `recompose` and refactors all HoCs to work without while using `flowRight` from lodash instead of `compose`.
While playing with TypeScript I noticed that `recompose` HoCs are a bit hard to type. Then I saw that we only use recompose for two rather simple HoCs. I think it's not really worth to keep recompose just for them. This should reduce bundle size a bit (if not at least simplify the code).

Refactor to remove `recompose`

---

src/components/buttons/flat-button/README.md
src/components/buttons/flat-button/flat-button.js
src/components/buttons/flat-button/flat-button.spec.js
src/components/buttons/icon-button/README.md
src/components/buttons/icon-button/icon-button.js
src/components/buttons/icon-button/icon-button.spec.js
src/components/buttons/link-button/README.md
src/components/buttons/link-button/link-button.js
src/components/buttons/link-button/link-button.spec.js
src/components/buttons/primary-button/README.md
src/components/buttons/primary-button/primary-button.js
src/components/buttons/primary-button/primary-button.spec.js
src/components/buttons/secondary-button/README.md
src/components/buttons/secondary-button/secondary-button.js
src/components/buttons/secondary-button/secondary-button.spec.js
src/components/buttons/secondary-icon-button/secondary-icon-button.js
src/components/buttons/secondary-icon-button/secondary-icon-button.spec.js

While working on the `Tooltip` implementation, I realized that we should use `aria-describedby` on the wrapped component. So our buttons (and perhaps our `inputs`) should support this attribute.
If we are okay with this approach, I can add it to `inputs` as well.
From talking to @filippobocik , it seems like we mostly use `Tooltips` with `Buttons` and a bit with disabled inputs like RadioInputs. 🤔

chore: support aria attributes on buttons

---

src/components/inputs/money-input/money-input.styles.js

Fixes background colour for MoneyInput

fix: fix background colour for money input

---

scripts/get-babel-preset.js

Since refactoring to using `emotion`, the ui-kit bundle size bloated from ~600kb to ~2.1mb. This is due to `babel-plugin-emotion` created code that looks like this.
```css("padding:", getPadding$1(props.scale), ";" + (process.env.NODE_ENV === "production" ? "" : "/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImluc2V0LXNxdWlzaC5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFxQlkiLCJmaWxlIjoiaW5zZXQtc3F1aXNoLmpzIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0JztcbmltcG9ydCBQcm9wVHlwZXMgZnJvbSAncHJvcC10eXBlcyc7XG5pbXBvcnQgeyBjc3MgfSBmcm9tICdAZW1vdGlvbi9jb3JlJztcbmltcG9ydCB2YXJzIGZyb20gJy4uLy4uLy4uLy4uL21hdGVyaWFscy9jdXN0b20tcHJvcGVydGllcyc7XG5pbXBvcnQgZmlsdGVyRGF0YUF0dHJpYnV0ZXMgZnJvbSAnLi4vLi4vLi4vdXRpbHMvZmlsdGVyLWRhdGEtYXR0cmlidXRlcyc7 …
```

chore: disable emotion source maps in production builds

---

src/components/inputs/select-input/select-input.visualroute.js
src/components/internals/create-select-styles.js
src/components/internals/tag-remove/tag-remove.js

When `SelectInput`s are set to `isMulti`, then when they are disabled, the labels should look disabled.
I updated the VRTs as well, which should illustrate the fix.

fix(select-input): fix for disabled state with multi values selected

---

CHANGELOG.md
package.json

I want to release version `8.3.1` to get the SelectInput fix in, so I can close the JIRA ticket.

chore: changelog and package.json for v8.3.1

---

src/components/tooltip/README.md
src/components/tooltip/tooltip.js
src/components/tooltip/tooltip.spec.js
src/components/tooltip/tooltip.story.js
src/components/tooltip/tooltip.styles.js
src/components/tooltip/tooltip.visualroute.js

Allows customizing the tooltip body by passing in a custom body component. This way the consumer can apply the styles they want to the tooltip.

feat(tooltip): allow passing in custom `BodyComponent`

---

src/components/tooltip/README.md
src/components/tooltip/tooltip.js
src/components/tooltip/tooltip.spec.js

Adds the prop `isEnabled` to the tooltip. It sort of mirrors the old "display" prop from the core tooltip.
While refactoring the MC and adding the new tooltip, I found a lot of cases when I had to make code like this 
```js
const Button = props =>
props.isDisabled ? (
<Tooltip title="Disabled">
<button disabled>Submit</button>
</Tooltip>
) : (
<button>Submit</button>
);
```
This prop should make it a bit cleaner.
```js
const Button = props => (
<Tooltip title="Disabled" off={!props.isDisabled}>
<button disabled={props.isDisabled}>Submit</button>
</Tooltip>
);
```

feat(tooltip): Add `off` prop

---

src/components/spacings/inline/README.md
src/components/spacings/inline/inline.js
src/components/spacings/inline/inline.story.js
src/components/spacings/inline/inline.styles.js
src/components/spacings/spacings.visualroute.js
src/components/spacings/stack/README.md
src/components/spacings/stack/stack.js
src/components/spacings/stack/stack.story.js
src/components/spacings/stack/stack.styles.js

Fixes #552
I also deprecated the `alignItems` values written in camelCase, which I found weird as we should simply pass the normal css values. So the "old" values are still supported for backwards compatibility.

feat(spacings): support justify-content prop for Inline/Stack components

---

src/components/table/table.story.js
src/components/tooltip/README.md
src/components/tooltip/tooltip.js
src/components/tooltip/tooltip.spec.js

Adds another `component` prop to the `Tooltip` component, `TooltipWrapperComponent`. This can be used along with `ReactDOM.renderPortal` to render the Tooltip to another place inside of the document. This is useful when dealing with virtualized items, like our table.
The following example uses a simple `TooltipWrapperComponent` that renders the portal as a descendent of `document.body`.

feat(tooltip): add option for tooltip wrapper

---

src/components/inputs/money-input/money-input.form.story.js
src/components/inputs/money-input/money-input.js

While fixing previouse issue https://github.com/commercetools/ui-kit/issues/538 another issue was added :( 
Which makes incorrect value rendered in the german locale German.
Will walk you through the issue
|-|-|
| ![if-fix-parse-money-value-before](https://user-images.githubusercontent.com/7680511/54355234-cf454300-4658-11e9-82ca-8f3b7cbef3aa.gif) | ![money-input after](https://user-images.githubusercontent.com/7680511/54355233-cf454300-4658-11e9-8a6f-b2a2440489b1.gif) |
Let's say that the output from `getAmountAsNumberFromMoneyValue` was `14.55`
1. When we get the formatted amount in `parseMoneyValue`,  we stringify the amount first using `String` function. (which doesn't consider the locale ) so the output of `String(getAmountAsNumberFromMoneyValue(moneyValue))` in …

Fix parse money value in MoneyInput

---

src/components/table/sortable-header/sortable-header.js

On tables with a sortable header, the column title jumps on hover because it aligns differently when the arrow shows up.
This PR fixes this bug.

fix(table): to remove jumpy effect on hover

---

package.json
src/components/fields/localized-multiline-text-field/localized-multiline-text-field.visualroute.js
src/components/fields/multiline-text-field/multiline-text-field.visualroute.js
src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.visualroute.js
src/components/inputs/multiline-text-input/multiline-text-input.visualroute.js
yarn.lock

Rebuilding yarn.lock on master leads to CI failing due to converting \n to <br>. Can't figure out why. Easier just to use "real" multiline text.

chore: update visual routes, add missing dep

---

src/components/panels/collapsible-panel/collapsible-panel.js
src/components/panels/collapsible-panel/collapsible-panel.styles.js

- adds `min-height` of `32px` on CollapsiblePanel's header section
This is done to anticipate use cases that renders `{Secondary|Primary}Button` on the header
With this, we can experience that the header's height "jumps" when `{Secondary|Primary}Button` are conditionally rendered

refactor(collapsible-panel): add `min-height`

---

.circleci/config.yml

On CircleCI we currently attempt to release from `master` without a tag. Which fails as the previous version already exists.
Given this configuration:
```yml
workflows:
version: 2
build-n-deploy:
jobs:
- build:
filters:  # required since `deploy` has tag filters AND requires `build`
tags:
only: /.*/
- deploy:
requires:
- build
filters:
tags:
only: /^v.*/
branches:
ignore: /.*/
```
- The build job runs for all branches and all tags.
- The deploy job runs for no branches and only for tags starting with ‘v’.

fix(circleci): releasing to next

---

src/components/buttons/link-button/link-button.js
src/components/typography/text/README.md

This PR:
- Updates documentation of `Text.Body` and `Text.Detail` to include the `isInline` prop.
- Fixes #588 by using the aforementioned prop.
There is still a problem with the `LinkButton` rendering a `div` (from the `Spacings.Inline` wrapper), which inside a `p` is also an invalid DOM nesting. I shall address this in a follow-up PR.

fix: LinkButton to use inline TextBody

---

src/components/spacings/inline/inline.js

Following #627 and related to #588: 
Since the `Spacings.Inline` component may often be used as an inline element itself, it shouldn't render a `div` but a `span` instead (which is inherently _inline_).
For instance, if used inside of a `p` it causes an invalid DOM nesting warning because a `p` shouldn't have a nested `div`.
This is already happening when using a `LinkButton` within a paragraph, as shown in #588.
This doesn't affect the layout itself because the way the element is styled, but only the HTML semantic.

chore: Spacings.Inline to render a span instead of div

---

src/components/inputs/localized-text-input/localized-text-input.js
src/components/inputs/localized-text-input/localized-text-input.styles.js
src/components/inputs/localized-text-input/localized-text-input.visualroute.js

Uses design tokens in `LocalizedTextInput`, and supports custom theming.

feat(localized-text-input): support custom theming, use design tokens

---

src/components/inputs/password-input/password-input.js
src/components/inputs/password-input/password-input.visualroute.js

feat(password-input): support theming

---

src/components/fields/async-creatable-select-field/async-creatable-select-field.story.js
src/components/fields/async-select-field/async-select-field.story.js
src/components/fields/creatable-select-field/creatable-select-field.story.js
src/components/fields/select-field/select-field.story.js
src/components/inputs/async-creatable-select-input/async-creatable-select-input.story.js
src/components/inputs/async-select-input/async-select-input.story.js
src/components/inputs/creatable-select-input/creatable-select-input.story.js
src/components/inputs/select-input/select-input.js
src/components/inputs/select-input/select-input.story.js
src/components/inputs/select-input/select-input.visualroute.js
src/components/internals/create-select-styles.js

This is an alternative solution to solving the problem faced by #617. Instead of modifying the scrollbar, we change the `SelectInputs` height so that it shows cut off menu items.
I have updated the visual regression tests to illustrate the fix. They know illustrate how options get cut off.
Closes #617

fix: change default menu height

---

src/components/buttons/flat-button/flat-button.js

When you navigate to a `FlatButton` using tab, currently there is no indication that this element is focused. I added the same effect that we have for hover now for focus. Also, I coloured the SVG element the same colour as the text on hover and focus.
After

fix(flat-button): focus fixes

---

src/components/tag/tag.js

Fixes #638 
(GIF compression messing those colours 🧐)
Using a regular `border` doesn't fit the design because the border takes space and would add a little edge or a flicker between the tag and the removal button.
The easiest alternative would be using `box-shadow` to emulate the border, just on the right side, but when the tag has an onClick prop, it has a box-shadow of its own when hovered, so this new box-shadow border would have to be merged with the current box-shadow and added to the design tokens.
I didn't like where this was going so I tried another approach:
So I used an absolutely positioned `:after` pseudo-element, and it does the job.

fix: Right border of removable tag

---

.storybook/webpack.config.js
package.json

I emailed netlify support about our build time issues.
They noticed that our builds have a lot of console logs. They suggested removing them.
`ProgressPlugin` spits out a lot of console logs. So let's disable it.

fix: storybook build times

---

.circleci/config.yml

This pull request aims to fix the release issue we're experiencing.
We currently can't manage to get the general release config suggested by CircleCI to work:
```yaml
filters:
tags:
only: /^v.*/
branches:
ignore: /.*/
```
Never runs. While
```yaml
filters:
tags:
only: /^v.*/
```
Always runs - even without a tag. Leaving us in a state of confusion. 
We can however attempt to replicate the filters with the new CircleCI 2.1 config without much bloat.

chore(circleci): use manual env variable checks for releae

---

package.json
src/components/field-label/README.md
src/components/field-label/field-label.js
src/components/field-label/field-label.spec.js
src/components/field-label/field-label.visualroute.js

@adnasa informed me that the desired behaviour is to force the 'medium' save for field labels. As such, I'm reverting all the changes made in #669

chore: revert changes in field label pr

---

src/components/fields/async-creatable-select-field/async-creatable-select-field.js
src/components/fields/async-select-field/async-select-field.js
src/components/fields/creatable-select-field/creatable-select-field.js
src/components/fields/money-field/money-field.js
src/components/fields/select-field/select-field.js
src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
src/components/inputs/async-select-input/async-select-input.js
src/components/inputs/creatable-select-input/creatable-select-input.js
src/components/inputs/money-input/money-input.js
src/components/inputs/select-input/select-input.js
src/utils/get-element.js
src/utils/helpers/exenv.js
src/utils/helpers/safeHTMLElement.js

We can't use `PropTypes.element` because that defines a react element.
We can't use `Element` because it's undefined in node and crashes the MC at compile time.
More info [here](https://github.com/reactjs/react-modal/issues/15)

fix(select-input): fix for prop type

---

src/components/internals/create-select-styles.js

Currently, `cursor: not-allowed` doesn't work with SelectInputs. 
This fixes that.

fix: select-input cursor when disabled

---

src/components/inputs/checkbox-input/checkbox-input.js
src/components/inputs/checkbox-input/checkbox-input.styles.js
src/components/inputs/checkbox-input/checkbox.js

This PR makes two changes to the `CheckboxInput`. Neither change affects the design of the component.
1. When the `Input` is focused, we treat it the same as the hovered state. This matches the behaviour in most of our `Input` components, including (but not limited to) `TextInput`, `LocalizedTextInput`, `MoneyInput`, etc, etc.
2. When the `CheckboxInput` is in an indeterminate state, we render it with this HTML property, to help screenreaders.

refactor(checkbox-input): accessibility concerns

---

src/components/inputs/checkbox-input/checkbox.js
src/components/internals/accessible-hidden-input.styles.js

As we will be using these styles in `RadioOptions`, `Checkbox` and `Toggle`, it makes sense not to reinvent the wheel 3 times.

refactoring(css): move `accessible-input-styles` to internals

---

src/components/inputs/checkbox-input/checkbox-input.js
src/components/inputs/checkbox-input/checkbox.js

Follow up to #721. Based on discussion with @mariabarrena 
Now when a checkbox has error state, we still give it the green hover, and same for "focus".

refactor(checkbox-input): accessibility fix

---

src/components/inputs/radio-input/radio-option.js
src/components/inputs/radio-input/radio-option.styles.js

Better visual feedback for `RadioOptions`. Also makes them accessible with the keyboard.
Changes
* Focus when input is in `hasWarning` or `hasError` states does a green underline
Design changes come from discussion with @mariabarrena

refactoring(RadioInput): hovered and focus state changes

---

src/components/buttons/flat-button/flat-button.js
src/components/buttons/icon-button/icon-button.js
src/components/buttons/link-button/link-button.js
src/components/buttons/primary-button/primary-button.js
src/components/buttons/secondary-button/secondary-button.js
src/components/buttons/secondary-icon-button/secondary-icon-button.js
src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
src/components/field-label/README.md
src/components/field-label/field-label.js
src/components/icons/README.md
src/components/icons/create-styled-icon.js
src/components/icons/icon.story.js
src/components/icons/icons.visualroute.js
src/components/icons/icons.visualspec.js
src/components/inputs/money-input/money-input.js
src/components/inputs/time-input/time-input-body.js
src/components/internals/calendar-body/calendar-body.js
src/components/internals/clear-indicator/clear-indicator.js
src/components/internals/dropdown-indicator/dropdown-indicator.js
src/components/notifications/content-notification/content-notification.js
src/components/panels/collapsible-panel/header-icon.js
src/components/table/sortable-header/sortable-header.js

As we discussed on slack, in order to make the icons themeable, we need to do something about the `theme` prop. When you use a styled component in emotion, it injects its `theme` prop, which we were overwriting since we had an identically named prop. 
* Renames the prop `theme` to `color`. Renames it's possible values from being our old colour decisions (white, green, etc) to our new colour decisions (surface, primary, etc).
Components that use icons, like for example, the `TimeInput` need this to maintain consistency. 
😭 
This will be merged into the `10.0.0` branch. The PR is set to master now so that Percy runs.

feat(icons): make icons themeable (breaking change)

---

src/components/inputs/time-input/time-input-body.js
src/components/inputs/time-input/time-input-body.styles.js
src/components/inputs/time-input/time-input.js
src/components/inputs/time-input/time-input.story.js
src/components/inputs/time-input/time-input.visualroute.js

This PRd does two things
* Properly support the `isReadOnly` prop for the `TimeInput` component.
* Refactor `TimeInput` component to use design tokens and to be themeable. 
NOTE: Until we merge `10.0.0`, a themed TimeInput looks a bit weird because the icons aren't themable. 
Closes #723

fix(time-input): readonly fix

---

src/components/inputs/checkbox-input/checkbox-input.js
src/components/inputs/checkbox-input/checkbox-input.styles.js
src/components/inputs/checkbox-input/checkbox-input.visualroute.js

* Use design tokens for `CheckboxInput`
* Make `CheckboxInput` theme-able

feat(checkbox-input): use design tokens / add theming

---

src/components/buttons/link-button/link-button.js

Fixes two bugs
* When the `LinkButton` is hovered, both the text and the icon should change color.
* When the `LinkButton` is disabled and hovered, the text should not change color.

fix(link-button): add hover effect for icon

---

src/components/tooltip/tooltip.styles.js

As reported by @filippobocik.
Currently, our tooltip margins are being overridden by our spacing components, as those use !important. 
Closes #753

fix(tooltip): margin specificity fix

---

src/components/links/link/README.md
src/components/links/link/index.js
src/components/links/link/link.js
src/components/links/link/link.spec.js
src/components/links/link/link.story.js
src/components/links/link/link.visualroute.js
src/components/links/link/link.visualspec.js
src/index.js
src/utils/get-pass-through-props.js
src/utils/get-pass-through-props.spec.js

Adds new `<Link />` component.
This component is a very thin wrapper over the [react-router link component](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md)
However, if you pass in the `isExternal` prop as true, instead it will render a regular <a> tag.

feat: add new `<Link>` component.

---

src/components/tooltip/tooltip.styles.js

* Closes #763 
I tested it in the MC locally with @islam3zzat's reproduction case and now the tooltip is no longer hidden by the card.

fix: tooltip z-index fix

---

.storybook/decorators/formik-box/formik-box.js
examples/form-fields.example.story.js
examples/form-inputs.example.story.js
src/components/buttons/link-button/link-button.js
src/components/grid/grid.story.js
src/components/internals/calendar-header/calendar-header.js
src/components/panels/collapsible-panel/collapsible-panel-header.js
src/components/spacings/inline/inline.story.js
src/components/spacings/inset-squish/inset-squish.story.js
src/components/spacings/inset/inset.story.js
src/components/spacings/spacings.visualroute.js
src/components/spacings/stack/stack.story.js
src/components/tag/tag.js
src/components/typography/text/README.md
src/components/typography/text/text.js
src/components/typography/text/text.spec.js
src/components/typography/text/text.styles.js
src/components/typography/text/text.visualroute.js
src/components/typography/typography.story.js

This PR adds a `as` prop to the Text components, as suggested by @tdeekens in https://github.com/commercetools/ui-kit/issues/588#issuecomment-469685493.
Deprecates `elementType` prop of `Text.Headline` and `Text.Subheadline` components.
Deprecates `isInline` prop of `Text.Body` component.
- **Which element types should we allow to render for the `Body` component?** (currently just `span` and `p`)

feat(text): Add `as` prop while deprecating `elementType`

---

src/components/panels/collapsible-panel/collapsible-panel.styles.js

When `CollapsiblePanel` is disabled, the header should look the same as when it's not disabled.
Thanks to @adnasa for catching this one 👍

fix(collapsible-panel): height of panel header while disabled

---

README.md

This pull request fixes the readme advising to use a deprecated custom property.
Please just merge once approved and CI passed.

docs(readme): fix spacings in readme

---

src/components/buttons/flat-button/flat-button.js
src/components/buttons/flat-button/flat-button.spec.js

I believe that the use of the `withMouseOverState` HOC is unnecessary. We can achieve the same effect with pure css, with better performance, and (marginally) more readable code.
If this is acceptable to yall, I'll make PRs to remove from the other components as well.

refactor(flat-button): simplify code, remove mouseover

---

src/components/inputs/checkbox-input/checkbox-input.js

This PR fixes a bug where the input would still visually respond to hovering even when disabled.

fix(checkbox): hovered state when disabled

---

src/components/panels/collapsible-panel/header-icon.js

When `CollapsiblePanel` is disabled, we should have the proper background colour for the icon button.
Should just be able to review the Percy diff.

fix(collapsible-panel): disabled state fix

---

src/components/buttons/link-button/README.md
src/components/buttons/link-button/link-button.js
src/components/buttons/link-button/link-button.story.js
src/components/links/link/link.js

Adds `isExternal` prop to `LinkButton`
Some use cases in the MC (discount predicates for one) have this sort of external link, and this would make their code cleaner.

feat(link-button): support isExternal prop

---

src/components/buttons/icon-button/icon-button.js

@franzi-t reported this bug in the MC. It's weird because our VRTs don't catch it, and I can't recreate the bug in storybook or in our visual testing app 🤔 
However, I manually tested the MC with this fix (by building the library, and then copy pasting it into `node_modules` in the MC, and it worked.
🤷‍♂ CSS is weird sometimes I guess 🤔 
(screenshot from MC)

fix(icon-button): misaligned icon fix

---

src/components/tooltip/README.md

We missed to rename to `title` on doc.

docs(tooltip): rename label to title

---

src/components/inputs/money-input/money-input.js
src/components/inputs/money-input/money-input.spec.js

In this PR we set the `minimumFractionDigits` to the value's `fractionDigits` when converting to string in `MoneyInput.parseMoneyValue`
Fixes #793 
More details on the issue, and reproduce steps can be found on the issue https://github.com/commercetools/ui-kit/issues/793

Fix MoneyInput.parseMoneyValue to respect the fraction digits

---

src/components/inputs/localized-multiline-text-input/translation-input.styles.js
src/components/inputs/multiline-text-input/multiline-text-input.styles.js

The `MultilineTextInput` expand behaviour is currently broken. This PR restores the functionality.

fix(multiline-input): Expand behaviour not working

---

src/components/panels/collapsible-panel/collapsible-panel.styles.js

Currently when you have a <SelectInput> above a CollapsiblePanel, the menu list is hidden by the CollapsiblePanel due to z-index setting. I don't believe we need to set a z-index here.

fix(collapsible-panel): remove z-index

---

.size-snapshot.json
package.json
rollup.config.js
yarn.lock

Second attempt of #576, now that the bug seems to be fixed in the last version (https://github.com/TrySound/rollup-plugin-size-snapshot/issues/24#issuecomment-496010479)

chore(rollup): output size snapshot of esm build

---

visual-testing-app/webpack.config.js

Thanks to first class CSS in JS support in @percy/agent, we can remove this webpack workaround.

chore: use prod in vrt

---

src/components/table/base-table/base-table.js
src/components/table/base-table/base-table.spec.js

This fixes `onSortChange` being called even if not passed as a prop (it's not required). As a result the component tree unmounts. This error occured 38 times to 3 users in our error logging.

fix(base-table): onSortChange being called without being passed

---

src/components/inputs/toggle-input/toggle-input.js

Fixes the following reported bugs on the ToggleInput component for when it is `disabled`:
> - The handler (thumb-color) should be grey instead of white 
> - The track shadow (the inner part) should be NONE. Right now there is a shadow.
Also fixes the styles for when the input is `disabled` and `checked`.

fix(toggle-input): toggle input disabled styles

---

src/components/internals/create-select-styles.js

Hopefully this fixes the warning that was failing CI

fix: use first-of-type instead of first-child

---

.size-snapshot.json
src/components/buttons/icon-button/icon-button.js
src/components/buttons/icon-button/icon-button.spec.js
src/components/buttons/icon-button/icon-button.styles.js
src/components/buttons/icon-button/icon-button.visualroute.js

Fixes a bug with hovering IconButtons with "green" theme. Also, refactors the component to remove the usage of the HOC.

fix(icon-button): hover state fix, and remove HOC

---

src/components/table/sortable-header/sortable-header.js

Refactors the `Table` component to remove usage of `withMouseOverState`

refactor(table): remove HOC

---

.storybook/configs/contexts.js
.storybook/configs/theme-context.js
.storybook/decorators/section/section.js

As theming is still a beta feature, we don't have much documentation about it. Not all components support theming. Most inputs do at the moment. 
This PR adds the ability in storybook to change to a (very basic) dark theme.
```js
const darkTheme = {
colorSolid: vars.colorSurface,
colorSurface: vars.colorSolid,
};
```

feat(storybook): add context add for theme

---

src/components/field-label/field-label.js
src/components/field-label/field-label.visualroute.js

Currently, when there is a long hint text, the icon scales to become tiny.
You can check the Percy diff for the new version

fix(field-icon): do not scale icon when long hint

---

package.json
src/components/table/base-table/base-table.js
src/components/table/base-table/base-table.spec.js
yarn.lock

We were only using the `classnames` dep in one file. Here I remove that package, and replace it with the usage of `cx` from `@emotion`.
See the [emotion docs](https://emotion.sh/docs/class-names) for more info.

chore: remove classnames

---

package.json

Since App Kit will be requiring React 16.8 in it's next major release, we should do the same. [ref](https://github.com/commercetools/merchant-center-application-kit/issues/748)

feat: require react 16.8

---

.size-snapshot.json
src/components/buttons/secondary-icon-button/README.md
src/components/buttons/secondary-icon-button/secondary-icon-button.js
src/components/buttons/secondary-icon-button/secondary-icon-button.story.js
src/components/buttons/secondary-icon-button/secondary-icon-button.styles.js
src/components/buttons/secondary-icon-button/secondary-icon-button.visualroute.js

Adds new `color` props to the SecondaryIconButton. The defaults are the same as before, to avoid breaking changes.
The size can be adjusted directly by the `Icon` element prop that is passed to the button.
Fixes #879

[UIKIT-879] feat(buttons): Add color prop to SecondaryIconButton

---

.size-snapshot.json
src/components/links/link/README.md
src/components/links/link/link.js
src/components/links/link/link.story.js
src/components/links/link/link.visualroute.js

Previously we did not set `text-decoration: underline` in the `Link` component. This was an oversight, as consumers who have competing global styles could inadvertently disable the underline. 
I also added a `hasUnderline` prop in the rare case that consumers want to remove the underline.

fix(link): apply underlined styles

---

src/components/inputs/date-time-input/date-time-input.js

We found a bug where the Today button in `DateTimeInput` would not highlight today's date, but the last day of the month instead.
This fixes that, and also for `DateTimeField`, as it is built with the input component.

fix(date-time-input): Today button not highlighting today's date

---

package.json
yarn.lock

`jest-runner-stylelint` has made `stylelint` a peer dep in version 2. So we can dump our resolutions.
https://github.com/keplersj/jest-runner-stylelint/issues/23

chore: update jest-runner-stylelint to v2

---

src/components/fields/password-field/password-field.js
src/components/fields/password-field/password-field.story.js
src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
src/components/inputs/async-select-input/async-select-input.js
src/components/inputs/creatable-select-input/creatable-select-input.js
src/components/inputs/localized-money-input/currency-control.js
src/components/inputs/localized-multiline-text-input/languages-control.js
src/components/inputs/localized-text-input/languages-button.js
src/components/inputs/select-input/select-input.js

Refactors the `select` components to use hooks, as well as `PasswordField` and some smaller components.

refactor: use hooks

---

src/components/inputs/localized-text-input/localized-text-input.js
src/components/inputs/localized-text-input/localized-text-input.story.js

Refactors the `LocalizedTextInput` container to use react hooks

refactor(localized-text-input): use hooks

---

src/components/inputs/date-input/date-input.js
src/components/internals/calendar-header/calendar-header.js

Refactors the `DateInput` component to use hooks.

refactor(date-input): use hooks

---

src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.spec.js
src/hooks/index.js
src/hooks/use-toggle-state/index.js
src/hooks/use-toggle-state/use-toggle-state.spec.js
src/index.js

Refactors the component `PrimaryActionDropdown` to use hooks

refactor(primary-action-dropdown): use hooks

---

src/components/inputs/money-input/money-input.js

Refactors the `MoneyInput` component to use react hooks.

refactor(money-input): use hooks

---

.circleci/config.yml
.yarnrc
yarn.lock

Following what we did in appkit: https://github.com/commercetools/merchant-center-application-kit/pull/786#discussion_r296618584
TL;DR: now we ensure that yarn runs on the specified version, no matter which version we have globally installed.

chore: instruct yarn to always use the given release

---

src/components/inputs/localized-money-input/localized-money-input.js
src/components/inputs/localized-money-input/localized-money-input.spec.js
src/components/inputs/localized-text-input/localized-text-input.js

Refactors the `LocalizedMoneyInput` component to use hooks.

refactor(localized-money-input): use hooks

---

src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
src/components/fields/password-field/password-field.js
src/components/inputs/money-input/money-input.js
src/components/internals/calendar-body/calendar-body.js
src/hooks/use-toggle-state/use-toggle-state.js
src/hooks/use-toggle-state/use-toggle-state.spec.js

Updates `useToggleState` hook's `toggle` function to accept an option arg that can be used to force the state.
Refactors various components (`MoneyInput`, `PrimaryActionDropdown`, `PasswordField` and `CalendarBody`) to use this hook instead of custom toggle logic.

refactor: improve `useToggleState` and use it across our components

---

src/components/inputs/select-input/select-input.spec.js

Adds test case with `isAutofocussed` to `SelectInput` 
Closes #897 
Big thanks to @iamchanii and the help in https://github.com/JedWatson/react-select/issues/3655#issuecomment-518158533

chore(select-input): add test for when autoFocussed is true

---

src/components/fields/password-field/password-field.js
src/components/inputs/localized-money-input/localized-money-input.js
src/components/inputs/localized-money-input/localized-money-input.story.js
src/components/inputs/localized-text-input/localized-text-input.js
src/components/inputs/time-input/time-input.js
src/components/tooltip/tooltip.js
src/hooks/use-field-id/index.js
src/hooks/use-field-id/use-field-id.js
src/hooks/use-field-id/use-field-id.spec.js

Fixes bug with inputs, where on every render (when an id is not provided), a new ID is generated.
Introduces new hook `useFieldId`

fix(inputs): do not generate new field id on each render

---

src/components/inputs/money-input/money-input.js

Fixes bug with `MoneyInput` and the tooltip
Before
After

chore: fix money input tooltip

---

src/components/inputs/money-input/money-input.js
src/components/inputs/money-input/money-input.spec.js

In this PR we fix the issue explained thoroughly in  #1017 
which causes wrong parsing in `es` locale
The issue only happens to my knowledge in the `es` locale, and that's because in `es` there is no thousands separator for 4 digits numbers and the number that we used for figuring out the separation symbol was 4 digits number.
The issue could've been solved easily by making the number 5 or 6 digits, but the new implementation which uses the fractions separator only made more sense to me.
Currently, our test env can only provide `en` locale, that's why we can't add unit tests for this issue

Fix MoneyInput's parsing

---

src/components/tooltip/README.md

The tooltip docs about the WrapperComponent were wrong.

chore: update tooltip docs

---

src/components/collapsible-motion/README.md
src/components/collapsible-motion/collapsible-motion.js
src/components/collapsible-motion/collapsible-motion.spec.js
src/components/collapsible-motion/collapsible-motion.story.js

Adds a `minHeight` property to `CollapsibleMotion` which allows us to animate between two different heights.

feat(collapsible-motion): add minHeight prop

---

src/components/collapsible-motion/collapsible-motion.js

Fix for the `CollapsibleMotion` component. Currently if the component is rerendered without the isOpen prop changing, the animation is lost. Leading to bugs

fix(collapsible-motion): do not set to null on rerender

---

src/components/tooltip/README.md
src/components/tooltip/tooltip.js
vendors/package-lock.json

Popper.js, which our Tooltip relies on, provides a powerful way of altering tooltip behaviour by using so called modifiers: https://popper.js.org/popper-documentation.html#modifiers
In some tricky cases they can really help properly place your tooltip. Instead of extending Tooltip's API case-by-case when facing them (at the moment I need a way to provide `preventOverflow` modifier to achieve proper positioning of a tooltip in MC), I suggest just expose all of them at once.
By doing this, we are paying a price of leaking internal implementation details of Tooltip component, but on the other hand leveraging lot of power of the underlying lib.

feat(tooltip): expose Popper.js modifiers

---

src/components/inputs/localized-text-input/localized-text-input.js
src/components/inputs/localized-text-input/localized-text-input.styles.js
src/components/inputs/text-input/README.md
src/components/inputs/text-input/text-input.js

Uses `TextInput` in our `LocalizedTextInput`, instead of our current approach of copy pasting the component.
Adds the `className` field to `TextInput`

chore: simplify localized text input

---

.storybook/webpack.config.js

Just removes this annoying warning from building storybook.
DeprecationWarning: @storybook/addon-storysource/loader is deprecated, please use @storybook/source-loader instead.

chore(storybook): fix deprecation warning

---

src/components/inputs/localized-multiline-text-input/translation-input.js
src/components/inputs/localized-multiline-text-input/translation-input.styles.js
src/components/inputs/multiline-text-input/multiline-text-input.js
src/components/internals/multiline-input/index.js
src/components/internals/multiline-input/multiline-input.js
src/components/internals/multiline-input/multiline-input.styles.js

Refactors the `MultilineTextInput` and `LocalizedMultilineTextInput` to use the same internal input.

refactor(multiline-text-input): move internal

---

src/components/inputs/rich-text-input/rich-text-input.story.js
src/components/internals/rich-text-body/dropdown.js
src/components/internals/rich-text-body/dropdown.styles.js
src/components/internals/rich-text-body/multi-dropdown.js

Fixes a bug with onBlur and onFocus firing when you open / close the dropdowns in the `RichTextInput`

fix(rich-text-input): do not fire on blur on dropdown open

---

scripts/run-percy.sh

Now that renovate creates less PRs, we should make it more useful by reenabling Percy.

chore: enable percy for renovate prs

---

src/components/panels/collapsible-panel/README.md

Removes internal wiki link from readme for `CollapsiblePanel`

chore: remove internal link from readme

---

package.json
test/setup-tests.js
vendors/package-lock.json
yarn.lock

With the latest version of `react-select`, it no longer spits out warnings about deprecated lifestyle methods.

chore: update react-select, remove ci silencing

---

src/components/inputs/rich-text-input/editor.js
src/components/inputs/rich-text-input/rich-text-input.form.story.js

This way we can use `<label>` elements to refer to our `RichTextInput`.
Big thanks to @islam3zzat

fix(rich-text-input): use `output` instead of `div` for contenteditable

---

src/components/inputs/rich-text-input/rich-text-input.js

We were getting performance warnings about setTimeout taking N ms. Removing event.persist fixed it.

fix(rich-text-input): performance fix

---

src/components/internals/rich-text-body/rich-text-body-button.js

Using the following css
```
* {
fill: color
}
```
Was resulting in some flakey behaviour when the SVG contained a shadow DOM. It's weird behaviour that results in things like this.
You probably are asking yourself WHERE IS THE GRAY COMING FROM? Yeah. 
More reading
https://stackoverflow.com/questions/27866893/svg-fill-not-being-applied-in-firefox

fix(rich-text-input): fixes undo / redo button problem

---

src/components/inputs/localized-multiline-text-input/translation-input.js

Fixes a problem with margin with localized-multiline-text-input

fix(localized-multiline-text-input): margin fix

---

src/components/inputs/rich-text-input/rich-text-input.js

Regression caused by #1088 
I imagine that because we are using setTimeout, our synthetic event is gone and by not calling `persist()`, we no longer have access to `name` and `id` inside of the onBlur.
When I debug it in storybook I also get `null` as event.target for a non persisted event.

fix(rich-text-input): fix onBlur and onFocus

---

src/components/inputs/rich-text-input/README.md
src/components/inputs/rich-text-input/rich-text-input.form.story.js
src/components/inputs/rich-text-input/rich-text-input.js
src/components/inputs/rich-text-input/rich-text-input.spec.js
src/components/inputs/rich-text-input/rich-text-input.story.js
src/components/inputs/rich-text-input/rich-text-input.visualroute.js
src/components/inputs/rich-text-input/rich-text-input.visualspec.js
vendors/package-lock.json

I started playing around with using the `RichTextInput` in the MC and I found that forcing our users to use Slate values made it a lot more complicated to integrate.
This PR refactors the `RichTextInput` to still be a `controlled` component, but to not expose slate values to the consumer.
Thanks to @pa3 for questioning why we were using slate values in the first place...

refactor(rich-text-input): make rich text only use HTML

---

src/components/inputs/rich-text-input/editor.js
src/components/inputs/rich-text-input/rich-text-input.js
src/components/inputs/rich-text-input/rich-text-input.visualspec.js

Some refactoring to use `pick` and to remove some unused props.

chore(rich-text-input): remove unused props

---

jest-puppeteer.config.js
src/components/inputs/rich-text-input/rich-text-input.js
src/components/inputs/rich-text-input/rich-text-input.story.js
src/components/inputs/rich-text-input/rich-text-input.visualspec.js

Currently, the `RichTextInput` is double rendering on every key stroke.

refactor(rich-text-input): performance optimisation 

---

src/components/inputs/rich-text-input/rich-text-input.js
src/components/inputs/rich-text-input/rich-text-input.visualspec.js

Fixes two regressions.
1. onFocus was being called when we interacted with the toolbar butters.
2. We weren't rerendering when you changed the cursor.

fix(rich-text-input): fix regression

---

src/components/inputs/localized-rich-text-input/localized-rich-text-input.story.js
src/components/inputs/localized-rich-text-input/rich-text-input.js
src/components/inputs/rich-text-input/rich-text-input.js
src/components/inputs/rich-text-input/rich-text-input.story.js

Currently we fire `onChange` when there are any changes to the slate internal value of the `RichTextInput`. However, sometimes these changes result in no changes to the HTML consumed by the consumer. In these cases, we should not fire onChange.
An example would be moving the cursor. This results in a change to slate, but no change to the HTML value.

chore(rich-text-input): perf improvement

---

src/components/inputs/localized-rich-text-input/README.md
src/components/inputs/localized-rich-text-input/localized-rich-text-input.js
src/components/inputs/localized-rich-text-input/rich-text-input.js

Make behaviour of `LocalizedRichTextInput` match other `LocalizedMutilineTextInput` as per the expand / collapse states.

fix(localized-rich-text-input): make behaviour match other localized component

---

src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.js
src/components/inputs/localized-rich-text-input/editor.js
src/components/inputs/localized-rich-text-input/localized-rich-text-input.js
src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualroute.js
src/components/inputs/localized-rich-text-input/rich-text-input.js

As requested by design, we should show the `expand` button when there is more than 32px of collapsed text.

chore(localized-rich-text-input): show expand button

---

src/components/buttons/accessible-button/accessible-button.js
src/components/buttons/accessible-button/accessible-button.spec.js
src/components/buttons/secondary-button/secondary-button.styles.js

Refactors our Buttons to display `cursor: not-allowed` when disabled.
Fixes #1113

fix(accessible-button): use not-allowed cursor on disabled

---

src/components/panels/collapsible-panel/collapsible-panel.styles.js

Adds `z-index: 1` when sticky so that the header is visible.

fix(collapsible-panel): z-index fix when sticky

---

src/components/internals/rich-text-utils/html/html.js
src/components/internals/rich-text-utils/html/html.spec.js
src/components/internals/rich-text-utils/html/index.js
src/components/internals/rich-text-utils/tags.js

The admin centre uses inline style instead of HTML elements.
This results in the following HTML
```
<p>
<span style="text-decoration-line: underline;">Underline</span>
</p>
<p>
<span style="text-decoration-line: line-through;">Strikethrough</span>
</p>
```
We need to translate this to HTML that our `RichTextInput` can understand.
So it should look like this
```
<p><u>Underline</u></p><p><del>Strikethrough</del></p>
```
This is how the Admin Center deals with text that is underlined and strikethrough
```<span style="text-decoration-line: underline line-through" />```

feat(rich-text-input): support admin center rich text

---

src/components/buttons/accessible-button/accessible-button.js
src/components/buttons/secondary-button/secondary-button.spec.js

If the button is NOT disabled, then we should check that `onClick` exists before calling it 🤦‍♂ 
This usually affects link buttons.

fix(buttons): fix onClick bug

---

src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
src/components/inputs/async-select-input/async-select-input.js
src/components/inputs/creatable-select-input/creatable-select-input.js
src/components/inputs/select-input/select-input.js

Allows you to do things like this
With code that looks like
```
const [inputValue, setInputValue] = React.useState('');
return (
<SelectInput
{...props}
inputValue={inputValue}
onInputChange={(value, { action }) => {
if (action === 'input-change' || action === 'set-value') {
setInputValue(value);
}
}}
/>
);
```

feat(select-inputs): support inputValue

---

src/components/typography/text/text.js
src/components/typography/text/text.spec.js

Fixes a bug where `intlMessage` prop is being ignored when the `as` prop is present for the `Text.Body` component.

fix(typography): fix Text.Body to use intlMessage when 'as' prop is present

---

src/components/inputs/localized-rich-text-input/rich-text-input.js
src/components/inputs/rich-text-input/rich-text-input.js

Slate does not seem to respect `disabled`. So instead we pass `readOnly` 
[ref](https://docs.slatejs.org/slate-core/editor#readonly)

fix(rich-text-input): disabled fix

---

src/components/inputs/localized-multiline-text-input/README.md
src/components/inputs/localized-rich-text-input/README.md
src/components/inputs/localized-rich-text-input/localized-rich-text-input.js
src/components/internals/rich-text-utils/localized/index.js
src/components/internals/rich-text-utils/localized/localized.js
src/components/internals/rich-text-utils/localized/localized.spec.js

Defines an HTML centric `omitEmptyTranslations` for `LocalizedRichTextInput`.
Finishes up the README for `LocalizedRichTextInput`.

fix(localized-rich-text-input): fix omit empty translations, add readme

---

src/components/inputs/rich-text-input/rich-text-input.visualspec.js
src/components/internals/rich-text-body/rich-text-body.js

The bug has to do with calling editor.focus() on any event propagated up to the Toolbar. The inline comment should explain the bug and the fix.

fix(rich-text-input): dropdown focus bug

---

src/components/inputs/localized-rich-text-input/editor.js
src/components/inputs/localized-rich-text-input/localized-rich-text-input.spec.js
src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualroute.js
src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualspec.js
src/components/inputs/rich-text-input/editor.js
src/components/inputs/rich-text-input/rich-text-input.story.js
src/components/inputs/rich-text-input/rich-text-input.visualroute.js
src/components/inputs/rich-text-input/rich-text-input.visualspec.js
src/components/internals/rich-text-body/hidden-input.js
src/utils/localized.js

Currently the `RichTextInput` and the `LocalizedRichTextInput` are completely broken in Safari.
After a lot of debugging, I figured out that combining `slate` + `contenteditable` + `<output>` lead to this problem.
In case anyone has forgotten, the reason why we wanted to use `output` in the first place, is because it natively supports working with `label`s and `htmlFor`.
Instead, I added a hidden input and I manually focus the `RichTextInput` based on that.

fix(rich-text-input): fix for safari

---

src/components/internals/rich-text-body/rich-text-body-button.js

Having "focusable" inputs "inside" of our `RichTextInput` is a nightmare and really hard to deal with. This solves a few bugs, including this one.

refactor(rich-text-input): remove focusability from buttons

---

src/components/label/label.visualroute.js
src/components/tooltip/tooltip.visualroute.js
test/percy/README.md
test/percy/spec.js

We sometimes have Specs that look like this.
```js
<Spec label="when inverted" omitPropsList={true}>
<ThemeProvider theme={themes.darkTheme}>
<Label tone="inverted">Hello</Label>
</ThemeProvider>
</Spec>
```
In these cases, we would usually use `omitPropsList`, because otherwise, our props list will come from `ThemeProvider`, instead of from the component that we are testing.
By adding this prop, we can tell our `Spec` to use the child, and therefore display the correct props.

chore(vrts): define new spec `listPropsOfChild` prop

---

src/components/buttons/accessible-button/accessible-button.js
src/components/buttons/secondary-button/secondary-button.js
src/components/buttons/secondary-button/secondary-button.spec.js
src/components/buttons/secondary-button/secondary-button.story.js

Refactors `SecondaryButton` to use `as` internally while keeping same API.

refactor(secondary-button): use as

---

src/components/buttons/accessible-button/accessible-button.js
src/components/buttons/icon-button/README.md
src/components/buttons/icon-button/icon-button.js
src/components/buttons/icon-button/icon-button.spec.js
src/components/buttons/icon-button/icon-button.story.js
src/components/buttons/secondary-button/README.md
src/components/buttons/secondary-button/secondary-button.js
src/utils/filter-invalid-attributes.js
src/utils/filter-invalid-attributes.spec.js

Adds support for `as` to the `IconButton`.
Also supports prop forwarding to `IconButton` and `SecondaryButton`. Without this, it would not be possible to use `anchor` tags.
Closes #1162

feat(icon-button): support `as` 

---

src/components/buttons/accessible-button/accessible-button.js
src/components/buttons/secondary-icon-button/README.md
src/components/buttons/secondary-icon-button/secondary-icon-button.js
src/components/buttons/secondary-icon-button/secondary-icon-button.spec.js

Adds the `as` prop to the `SecondaryIconButton`. All the buttons should support `as`, it will make the Buttons easier to use and more consistent.

feat(secondary-icon-button): add as prop

---

src/components/tag/tag.js

The `Tag` code was needlessly complicated as we rendered different internal "containers" based on whether or not it was a `Link`. This simplifies it quite a bit while preserving the same API.

refactor(tag): simplify code by using `as` internally

---

src/components/buttons/accessible-button/accessible-button.js
src/components/buttons/flat-button/README.md
src/components/buttons/flat-button/flat-button.js
src/components/buttons/flat-button/flat-button.spec.js
src/components/buttons/link-button/link-button.js
src/components/buttons/link-button/link-button.spec.js
src/components/inputs/localized-multiline-text-input/translation-input.js
src/components/inputs/localized-rich-text-input/editor.js
src/utils/warn-deprecated-component.js

* Deprecates `LinkButton`
* Adds `as` prop to `FlatButton`.
* Fixes a bug in `AccessibleButton` where `handleClick` was being overwritten by the passed in `onClick`

refactor(flat-button): add as, deprecate linkbutton

---

src/components/buttons/primary-button/primary-button.styles.js

Fixes the `active` and `toggled` state of `PrimaryButton`, because of some leftover deprecated design tokens we forgot to update on version 10.0.0 😅
**Before**: (the button remains the same when clicked or toggled)
**After**:

fix: primary button active and toggle state

---

src/components/inputs/localized-rich-text-input/editor.js

This PR fixes an edge case where the width of the Localized Rich Text Input might outgrow the size of its container in case there is a very long word (or the container is narrow), such as the name of a very specific tool in the Icelandic language:
This occurs because the Rich Text input container grows until 100% of its parent width and only then it starts breaking the text, but it doesn't take into account the space taken from the language label on the left (which is variable).
The added one-liner fixes this, as the text is broken to different lines before the input outgrows its parent, with no side-effects.

fix: Localized Rich Text Input containment

---

src/components/inputs/toggle-input/toggle-input.js

TL;DR: in Formik v2 they changed a bit how checkbox and radio inputs deal with values
> Formik 2 "fixes" React checkboxes and multi-selects with built-in array binding and boolean behavior
https://github.com/jaredpalmer/formik/releases/tag/v2.0.1
As we are upgrading our apps to formik v2, we started bumping into weird test failures and we narrowed the issue down to checkbox input types. It seems that if no `value` is provided, the default value is `on`, [as described in the MDN <input type="checkbox">](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Value).
You can also see in the following codesandbox how the behavior differs:
https://codesandbox.io/s/formik-checkbox-value-i40kv
It appears that by passing both `value` and `checked` to the input, Formik handles …

fix(toggle-input): allow to pass value prop

---

src/components/tooltip/tooltip.js
src/components/tooltip/tooltip.spec.js

When `Tooltip` is set to off, we should not add `aria-describedby` or `title`.

fix(tooltip): do not use native title when tooltip is off

---

.circleci/config.yml

The [persist_to_workspace](https://circleci.com/docs/2.0/configuration-reference/#persist_to_workspace) step uses golang `filepath.Match` for glob patterns which unfortunately has some limitations (e.g. the double stars `**` is not supported).
This causes nested packages to not be matched.
For now, until we have moved the source code into the related packages and flattened the list of packages, we need to be explicit on the glob matches.
Once we have a flat list, we can simply use `packages/*/dist/`.

fix(circleci): glob for workspace because of golang glob limitations

---

src/components/buttons/flat-button/flat-button.js
src/components/buttons/flat-button/flat-button.spec.js
src/components/buttons/flat-button/flat-button.story.js
src/components/buttons/flat-button/flat-button.visualroute.js

[UKIT-95](https://jira.commercetools.com/browse/UKIT-95)
This PR adjusts the `FlatButton` to allow breaking the text into multiple lines when the element is not a `button`, and changes the position and size of the icon, not allowing it to shrink and keeping it on the same line as the text.
Before:
After:

fix(flat-button): icon size and position for multi-line anchors

---

packages/components/inputs/select-utils/package.json
packages/i18n/data/core.json
packages/i18n/data/de.json
packages/i18n/data/en.json
packages/i18n/data/es.json
packages/i18n/data/fr-FR.json
packages/i18n/data/ja.json
packages/i18n/data/zh-CN.json
src/components/inputs/select-input/select-input.spec.js
src/components/internals/clear-indicator/clear-indicator.js
src/components/internals/clear-indicator/messages.js

Related to #1210 
This PR changes the `ClearIndicator`, used by `SelectInput`, to be a button and have a title and label, becoming screen-readable and easier to select (e.g. for tests).
Some tests for this element were fixed, because they were giving false positives.

fix(select-input): make the ClearIndicator a button

---

package.json

When doing a `yarn release`, if you forgot to log in to the `npm` CLI, lerna will still perform some of the steps but then fail on the `npm publish` process, resulting in dirty state (see https://github.com/lerna/lerna/issues/455).
This PR prevents this problem by checking if the user is logged in to npm on the `prerelease` step.

chore: check npm authentication on prerelease

---

src/components/internals/create-select-styles.js

Small adjustment to the `SelectInput` styles, for multi-values: When there is no `multiValueRemove` component being displayed (by passing an empty component to it), the `multiValueLabel` doesn't have a right border.
This PR fixes that, to prevent the need to also override the `multiValueLabel` just for this styling detail, or other "hacky" workarounds.

fix(select-input): multi select tag borders

---

packages/calendar-utils/package.json
packages/components/inputs/date-input/package.json
packages/components/inputs/date-range-input/package.json

The package `calendar-utils` has new stuff needed by the latest release of `ui-kit` (10.14.1), but `calendar-utils` wasn't updated/released itself.
Because of this, DateInputs are broken in 10.14.1.
I've released it manually, and now the dep has to be updated and to re-release `ui-kit`.

chore: update calendar-utils

---

src/components/tag/tag.story.js

If you go to: https://uikit.commercetools.com/?path=/story/components-tags--tag
And go to `Knobs`, the page crashes.
This PR fixes the problem.

chore(tag): fix storybook example

---

src/components/tag/tag.js

Fix for [UKIT-97](https://jira.commercetools.com/browse/UKIT-97)
> When the user hovers the removable area on a disabled label, the button still displays the orange hover effect that indicates the label is removable. There should not display any hover effect when disabled.

[UKIT-97] fix(tag): on remove button hover when disabled

---

packages/components/messages/README.md
packages/components/messages/package.json
packages/components/messages/src/error-message/error-message.js
packages/components/messages/src/error-message/error-message.spec.js
packages/components/messages/src/warning-message/warning-message.js
packages/components/messages/src/warning-message/warning-message.spec.js

Adding `intlMessage` prop to `ErrorMessage` and `WarningMessage` components similair to `Text` component
current usage of `ErrorMessage` or `WarningMessage`:
```javascript
<ErrorMessage>
<FormattedMessage {...validationMessages.required} />
</ErrorMessage>
```
adding `intlMessage` prop will help reduce code and nesting of components inside one another.
desired usage of `ErrorMessage` or `WarningMessage`:
```javascript
<ErrorMessage intlMessage={validationMessages.required} />
```
This feature implemetation doesn't change the API of the components.

feat(messages): to add intlMessage prop to error and warning message components

---

packages/components/accessible-hidden/LICENSE
packages/components/accessible-hidden/README.md
packages/components/accessible-hidden/index.js
packages/components/accessible-hidden/package.json
packages/components/accessible-hidden/src/accessible-hidden.js
packages/components/accessible-hidden/src/accessible-hidden.spec.js
packages/components/accessible-hidden/src/index.js
packages/components/accessible-hidden/src/version.js

This is a new component proposal for addressing #1269 
The idea is providing an easy way to [render invisible, but machine-readable content](https://webaim.org/techniques/css/invisiblecontent/).
```js
import AccessibleHidden from '@commercetools-uikit/accessible-hidden';
<AccessibleHidden>
<label htmlFor="sample-input">Sample Input</label>
</AccessibleHidden>;
```
Add a prop to Field components to allow hiding the `label` using this component.

feat: add accessible-hidden component

---

CHANGELOG.md

Releasing a new version with some requested features, before releasing the next one with the new Table.

docs(changelog): for release v10.17.0 [skip ci]

---

packages/components/card/README.md
packages/components/card/src/card.js

@YahiaElTai raised the fact that the `className` prop was documented with the wrong casing. This is fixed in this PR.
Also took the opportunity to remove one unnecessary wrapper and styles from the component.

chore(card): fix documentation and small refactor

---

packages/components/buttons/accessible-button/src/accessible-button.js
packages/components/buttons/accessible-button/src/accessible-button.spec.js
packages/components/collapsible-panel/src/collapsible-panel.js
packages/components/collapsible-panel/src/collapsible-panel.spec.js
packages/components/collapsible-panel/src/collapsible-panel.styles.js

This PR addresses this problem: https://github.com/commercetools/merchant-center-frontend/pull/8565#issuecomment-598637568.
It occurs when the `CollapsiblePanel` is passed any child elements for the Header that are buttons, because the Header of the CollapsiblePanel is also a `button` element.
* Fix the `AccessibleButton` component to become truly accessible when the `as` prop is used:
* Add `role` and `tabIndex` attributes.
* Add `onKeyPress` event for `Enter` and `Space` to trigger the `onClick`, for full keyboard navigation support.
* Use this adjusted `AccessibleButton` as a `div` for the CollapsiblePanel header, instead of a `button` element but keeping the a11y.

fix(collapsible-panel): Accessible panel Header element

---

packages/components/collapsible-panel/src/collapsible-panel.js
packages/components/collapsible-panel/src/collapsible-panel.spec.js

I broke the forwarding of `data-` attributes on the last changes for `CollapsiblePanel`.
This PR fixes it and adds a test so it won't happen again 🙃

fix(collapsible-panel): to forward data-attributes

---

packages/components/buttons/accessible-button/src/accessible-button.js

Quick fix: this rule wasn't working because of a missing semicolon 🤦‍♂

fix(accessible-button): fix no-outline rule for button elements

---

src/components/fields/password-field/password-field.js
src/components/fields/password-field/password-field.visualroute.js

A follow-up to https://github.com/commercetools/ui-kit/pull/1292
Fixes the alignment of the `show` password button in `PasswordField`.

[UKIT-110] fix(password-field): show password button alignment

---

packages/components/data-table/src/data-table.styles.js

`DataTable`: Because the header cells have a `z-index` higher than the default, other elements that appear above the table might be painted below the header cells.
This PR fixes the problem by giving bringing the `table` element, parent of the header cells, back to `z-index` of `0`, making the table and all the child elements _relative_ to it respect the normal hierarchy.

fix(data-table): normalize z-index

---

packages/components/data-table/README.md
packages/components/data-table/src/cell.js
packages/components/data-table/src/cell.styles.js
packages/components/data-table/src/data-table.js
packages/components/data-table/src/data-table.spec.js
packages/components/data-table/src/data-table.story.js
packages/components/data-table/src/data-table.styles.js

Adds a `footer` prop to `DataTable` to allow placing content on the `tfoot`  element.

fix(data-table): add footer prop

---

packages/components/data-table/src/cell.styles.js

The `wrapHeaderLabels` prop was incorrectly affecting non-header cells.
This PR fixes this.
This reminds me that we should have VRTs for the new table: will come in a follow-up PR.

fix(data-table): column cells not wrapping

---

packages/components/data-table/src/data-table.visualroute.js
packages/components/data-table/src/data-table.visualspec.js

Adds VRTs to the `DataTable` component.

chore(data-table): add visual regression tests

---

.changeset/seven-adults-turn.md
packages/components/data-table/src/data-table.styles.js

* `DataTable`
This PR complements the last one (https://github.com/commercetools/ui-kit/pull/1341) to prevent the table from overflowing if it's too wide for its container, adding a horizontal scrollbar if needed, even if there's no `maxWidth` defined.
This is a common case if the window is too narrow for the columns, and the table is inside a `Card`, `CollapsiblePanel`, or any other container which doesn't necessarily have a specified width.
A possible follow-up might be excluding the footer part from the containment, but this is still being considered by the design team.

fix(data-table): Allow table to have scrollbar when too wide for its container

---

src/components/typography/text/text.js

This PR simply fixes a false `Warning` being thrown in development because of a wrong fn name.

chore(text): fix wrong util fn causing warnings in dev

---

.changeset/tidy-hounds-repeat.md
packages/components/data-table/package.json
packages/components/data-table/src/cell.js
packages/components/data-table/src/cell.styles.js
yarn.lock

- `DataTable` => Sortable columns should be clearly indicated (showing `AngleUpDown` icon in the header cell) so that user can see it without hover on each column and finding it out that way. If a column is focused/active, either `AngleUp` or `AngleDown` icon is shown, depending on its current sort direction.

feat(data-table/cell): Improve data table's sortable columns

---

src/components/spacings/stack/README.md

This PR fixes an issue with the docs for `Spacings.Stack` default value for `alignItems`

chore(docs): to update spacings stack docs

---

.changeset/little-tomatoes-brush.md
packages/components/data-table/package.json
packages/components/data-table/src/cell.js
packages/components/data-table/src/cell.styles.js
packages/components/data-table/src/data-row.js
packages/components/data-table/src/data-table.js
packages/components/data-table/src/data-table.spec.js
packages/components/data-table/src/data-table.story.js
packages/components/data-table/src/data-table.styles.js

- `DataTable` => Allow table users to expand or collapse data per rows when the table content is truncated

feat(data-table): Enable rows to expand and collapse in case they have truncated columns

---

.changeset/fair-icons-talk.md
src/components/fields/async-creatable-select-field/async-creatable-select-field.spec.js
src/components/fields/async-select-field/async-select-field.spec.js
src/components/fields/creatable-select-field/creatable-select-field.spec.js
src/components/fields/select-field/select-field.spec.js

- **_All select fields_** => The select fields uses the `title` prop to render the labels of a select field. Therefore, the tests should use that for testing the rendered label instead of adding another separate label on top.

fix(select-fields): Fix RTL tests

---

.changeset/fair-rabbits-tell.md
packages/components/data-table/src/cell.js
packages/components/data-table/src/data-row.js
packages/components/data-table/src/data-table.spec.js

This PR adds `data-testid` attributes to the headers and cells of the table, to improve their testability.
I used the same sequential id that was being used in the "old" table, but with the `data-testid` attribute instead of just `data-test`. This means the migration steps for the tests that query for these test ids will be minimal.

fix(data-table): add data-testid attributes to headers and cells

---

.changeset/metal-bees-mix.md
packages/components/data-table/src/column-resizer.js

This PR fixes a small issue with the DataTable column resizer taking too much space on the edge of the table:
This bug makes the table have a horizontal scrollbar because of that little extra space 😠

fix(data-table): column resizer taking extra space

---

packages/components/data-table/src/data-table.story.js

This PR fixes a bug in the storybook DataTable example:
When you set a value for the `align` option of a column, you can't change it back to the default. It keeps the previously selected option.
No changeset as this is just a bug in a storybook example.

fix: storybook data-table example

---

.kodiak.toml

In [this issues](https://github.com/chdsbd/kodiak/issues/437) I proposed that Kodiak would change it's wording from `blacklist_*` to `denylist`. 
They now adopted the wording of `blocking_*`. The documentation PR is pending [here](https://github.com/chdsbd/kodiak/pull/454) while the change is already merged [here[(https://github.com/chdsbd/kodiak/pull/444).
The deployment and deployment of Kodiak was done. I contacted them to make sure.
The documentation can also be found [here](https://kodiakhq.com/docs/config-reference#mergeblocking_title_regex).

fix(kodiak): to use blocking wording not blacklist

---

.changeset/young-jeans-grow.md
packages/components/data-table/src/cell.js
packages/components/data-table/src/cell.styles.js
packages/components/data-table/src/data-row.js
packages/components/data-table/src/data-table.js
packages/components/data-table/src/data-table.styles.js

There are a few edge cases when a DataTable is resized that cause content to overflow out of their cell. This is more noticeable on the last column of a table and especially if the background isn't white.
This PR addresses this problem by making sure cell content is clipped when a column may be narrower than its content, and the table edge (seen by its background color) is moved along with the edge of the last column:

fix(data-table): clip cells when table is resized

---

.changeset/few-bananas-explode.md
packages/components/data-table/src/use-manual-column-resizing-reducer.js

Quick fix related to typings. Not casting the return value of the aforementioned function causes warnings to be thrown because we should expect it to be a boolean.
We should add proper specs to the reducer as a follow-up, but for now I would like this fix to be merged so we can unblock the next release of ui-kit with the resizing feature 🙏

fix(data-table): cast getHasTableBeenResized to a boolean

---

.changeset/angry-carrots-accept.md
packages/components/data-table/src/data-row.js

This PR fixes the `DataTable` to properly update row collapsed state when `isTruncated` options are changed for the whole row.
A bit of context:
* `isTruncated` is a flag that only controls whether a row can be truncated.
* `isRowCollapsed` actually controls if a column with isTruncated=true is in fact truncated(=collapsed)
When a table is initially rendered, the row’s `isRowCollapsed` state is initialized according to the `isTruncated` props of the columns. 
Changing the `isTruncated` prop doesn’t re-initialize that state, which is why the table remains uncollapsed if it was initialized like that (and vice versa). Only the expand/collapse button controls that state.
This was a problem for developing the ManagedDataTable, which allows imperatively toggling the `isTruncated` of the columns …

fix(data-table): Row collapsing behaviour

---

.changeset/flat-squids-decide.md
packages/components/fields/select-field/src/select-field.form.story.js
packages/components/fields/select-field/src/select-field.js
packages/components/fields/select-field/src/select-field.story.js
packages/components/fields/select-field/src/select-field.visualroute.js

`SelectInput` already expose a `hasWarning` prop. However this prop was not available on the `SelectField`. This PR exposes this prop on the `SelectField` as well.
p.s. It is needed for a feature in the MC-FE and it would be nice to have this released as soon as possible so that the MC-FE task can be started.

packages/select-field: Enable hasWarning prop on SelectField

---

.github/workflows/main.yml

Noticed this here
The env variable was already defined in github secrets, but it wasn't referenced in the job step

fix(ci): missing bundlesize token

---

.github/workflows/main.yml

After we enabled bundlesize status check in #1431, it appears that the server is not working fine
It seems to be a general issue. For now we just disable the status check again.

fix: disable bundlesize status check

---

.changeset/ten-suns-count.md
packages/components/link/README.md
packages/components/link/package.json
packages/components/link/src/link.js
packages/components/link/src/link.spec.js
packages/components/link/src/link.visualroute.js

This PR adds a intlMessage prop to Link component, which can replace the children prop for translated text, in the same fashion as the Text components.

feat(link): add intlMessage prop to Link in ui-kit

---

.github/workflows/release.yml

Same as in the appkit repo, we use a personal access token from our `ct-release-bot` account, which allows to trigger multiple github workflows (not possible using the default github token).
For instance, when the "Version packages" PR gets opened/updated, the main workflow should now be triggered.
PS: the secret is already in place.

chore(actions): use personal access token to allow triggering multiple workflows

---

packages/components/data-table-manager/README.md
packages/components/data-table-manager/src/data-table-manager.js

This PR fixes a few things in the documentation (leftovers) and prop-type validation of the `DataTableManager` component.
Thanks @NickDevG for pointing these out.

chore(data-table-manager): Documentation and prop-type validation fixes

---

.changeset/slimy-windows-yell.md
packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.form.story.js
packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.js
packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.story.js
packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.visualroute.js
packages/components/fields/async-select-field/src/async-select-field.form.story.js
packages/components/fields/async-select-field/src/async-select-field.js
packages/components/fields/async-select-field/src/async-select-field.story.js
packages/components/fields/async-select-field/src/async-select-field.visualroute.js
packages/components/fields/creatable-select-field/src/creatable-select-field.form.story.js
packages/components/fields/creatable-select-field/src/creatable-select-field.js
packages/components/fields/creatable-select-field/src/creatable-select-field.story.js
packages/components/fields/creatable-select-field/src/creatable-select-field.visualroute.js

- `AsyncSelectInput` has `hasWarning` prop to indicate that the field has a warning. This prop was not passed down from the `AsyncSelectField` and this PR passes down via the `hasWarning` field.

Expose hasWarning prop on select fields

---

.changeset/slow-ligers-stare.md
packages/components/data-table/src/data-table.styles.js

This PR fixes a bug where the user can't scroll horizontally on the DataTable when it exceeds the container's size.

fix(data-table):horizontal scrolling

---

.renovaterc.json
package.json
yarn.lock

`pptr-testing-library` version was locked because of https://github.com/testing-library/pptr-testing-library/issues/31
That has been fixed with https://github.com/testing-library/pptr-testing-library/pull/34.
This PR unlocks the version and updates.
<del>EDIT: Actually, we need to wait for the new version with the fix to be released 😅 </del>

chore: update pptr-testing-library

---

.changeset/yellow-chicken-lay.md
packages/components/data-table/package.json
packages/components/data-table/src/data-table.js
packages/components/data-table/src/data-table.styles.js
packages/components/data-table/src/use-manual-column-resizing-reducer.js
packages/components/data-table/src/use-manual-column-resizing-reducer.spec.js

`DataTable`: This PR fixed a bug where the table container is not adjusting to table size when columns are shrinked, which is noticeable when there is a footer present:

fix(data-table): container not adjusting to table size when shrank

---

.changeset/silver-cars-kiss.md
packages/components/data-table/src/data-table.js
packages/components/data-table/src/data-table.story.js

`DataTable`
This PR fixes a bug where the table column resizing could break after changing the number of columns, because the column measurements were not being properly reset.

fix(data-table): table column sizes not being properly reset

---

.changeset/seven-bananas-argue.md
packages/components/data-table/src/cell.js
packages/components/data-table/src/cell.styles.js

`DataTable`
Fixed bug where clicking near the edge of a cell wouldn't trigger `onRowClick` if the cell was substantially taller than its own content.

fix(data-table): Cell clickable area

---

.github/workflows/main.yml

An attempt to solve this error.
Alternatively we might `sudo apt-get install libxss1`.

fix(github): action to use recent puppeteer action

---

.changeset/bright-ants-grow.md
packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.form.story.js
packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.story.js
packages/components/fields/async-select-field/src/async-select-field.form.story.js
packages/components/fields/async-select-field/src/async-select-field.story.js
packages/components/fields/creatable-select-field/src/creatable-select-field.form.story.js
packages/components/fields/creatable-select-field/src/creatable-select-field.story.js
packages/components/fields/select-field/src/select-field.form.story.js
packages/components/fields/select-field/src/select-field.story.js
packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.form.story.js
packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.story.js
packages/components/inputs/async-select-input/src/async-select-input.form.story.js
packages/components/inputs/async-select-input/src/async-select-input.story.js
packages/components/inputs/creatable-select-input/src/creatable-select-input.form.story.js
packages/components/inputs/creatable-select-input/src/creatable-select-input.story.js
packages/components/inputs/select-input/src/select-input.form.story.js
packages/components/inputs/select-input/src/select-input.story.js

- `SelectInput`s and `SelectField`s are group under their own sub-menus in the storybook to ease the find. 
- Also fixed a bug in the options filtering in the `async-select-input` and `async-createable-select-input`

Chore: Group select inputs and fields in the storybook

---

.changeset/gorgeous-poets-cry.md
packages/components/data-table-manager/src/data-table-settings/data-table-settings.js

This PR adds the TableIcon to the Table Settings dropdown.

feat: to add table icon to data-table-manager dropdown

---

.changeset/little-items-press.md
src/components/internals/icons/create-styled-icon.js

This PR prevents `Icon` component from shrinking when inside of resized flex container.

fix(icon): to prevent icon from shrinking inside of flex container

---

.changeset/mighty-birds-vanish.md
packages/components/inputs/date-range-input/src/date-range-input.js

Fixes #1567 
**Before**
**After**

fix(date-range-input): rendering of weekdays with dates in calendar body

---

.changeset/mean-hornets-explode.md

This PR is for bumping the version of some inputs and fields which weren't bumped in https://github.com/commercetools/ui-kit/pull/1539
All the inputs & fields were affected but not all had their versions bumped, which was a mistake.

chore: add focus/hover changeset to missing inputs and fields

---

.changeset/plenty-pianos-bow.md
packages/components/collapsible-motion/src/collapsible-motion.js
packages/components/collapsible-motion/src/collapsible-motion.spec.js

This PR changes the `CollapsibleMotion` component to actually hide the content from the accessibility tree when collapsed so that elements like buttons or inputs won't continue to receive focus when they're visually nowhere to be seen.
This is achieved with the CSS property `visibility`.

fix(collapsible-motion): make content effectively invisible when collapsed

---

.changeset/stale-guests-rhyme.md
packages/components/fields/search-select-field/README.md
packages/components/stamp/README.md
packages/components/stamp/package.json
packages/components/stamp/src/stamp.js
packages/components/stamp/src/stamp.story.js
packages/components/stamp/src/stamp.visualroute.js

Currently, the stamp component has too much padding for some use-cases, the smaller version is important for use-cases that need the stamps after the text. With the small padding from the top and bottom, the stamp will be highlighted but not too much.

Add isCondensed prop to the Stamp component

---

generators/package-json/src/index.ts
generators/package-json/test/generate-package-json.spec.ts

Leftover of #1646 
It was more of a "one-time" thingy, we don't need it in general.

refactor(generator): cleanup leftovers

---

generators/package-json/bin/generate_package_json.sh
tsconfig.json

Using the same `tsconfig.json` as in appkit.
In preparation for #1669

fix: prepare tsconfig.json for TS migration

---

.github/workflows/release.yml

Recently I noticed that changesets do not perform a semantic commit. This is not too bad but when updating to Husky v5 the releases failed. To avoid running into this eventually I propose to be proactive and have a semantic commit for the release.

fix(ci): to have semantic commit for changesets

---

.github/renovate.json

* Moves renovate config into `.github` folder
* Uses `preserveSemverRanges` instead of `pinOnlyDevDependencies`

chore(renovate): preserve semver ranges

---

.changeset/tidy-mails-reflect.md
presets/spacings/src/index.ts

Follow up of #1742 
Letting TS inferring the exported type somehow leads to weird imports such as `import("@commercetools-uikit/spacings-inline/src/inline")`, whichis an invalid path.

fix(spacings): be explicit in typing Spacings object

---

package.json
yarn.lock

The [concurrency fix](https://github.com/atlassian/changesets/releases/tag/%40changesets%2Fcli%402.14.1) has been merged and released.

chore: update changeset to 2.14.1, which includes the publishing concurrency fix

---

docs/package.json
docs/yarn.lock

I'm not sure if this helps, but I got this notification
so I added `prism@v1.23.0` as peer/dev dependency to docs
inspecting the version after installation, it looks like it's in place

chore(docs): add prism@1.23.0 as peer

---

.changeset/tall-ladybugs-tan.md
packages/components/link/README.md
packages/components/link/src/link.js
packages/components/link/src/link.spec.js
packages/components/link/src/link.story.js
packages/components/link/src/link.visualroute.js

This PR adds `isWhite` prop to the `Link` component
Right now we can use the Link component only in one color which in some cases doesn't fit to background color: 
This PR adds possibility to make the link white which is supposed to cover all the cases when primary color is not visible enough.

feat: to add a `primary` and `inverted` tone to the `link` component

---

.changeset/two-months-obey.md
packages/components/link/README.md
packages/components/link/src/link.js
packages/components/link/src/link.story.js

- removes `hasUnderline`. 
- link is underlined by default
ref #1737

refactor(link): remove `hasUnderline`

---

.changeset/smooth-spoons-walk.md
packages/components/text/README.md
packages/components/text/src/text.styles.ts
packages/components/text/src/text.tsx

- removes `isInline`
- removes `elementType`
- targets `v12` branch.
ref: #1737 
it's time to start the breaking changes IMO, but to ease the flow of introducing other changes in parallel without blocking release, we take a strangling approach and target an intermediate branch

refactor(text): remove deprecated props

---

.changeset/eleven-meals-remain.md
packages/components/inputs/localized-rich-text-input/README.md
packages/components/inputs/rich-text-input/README.md

- removes `beta` flag from rich text #1737

docs(rich-text): remove beta

---

packages/components/text/src/text.story.js
packages/components/text/src/text.visualroute.js

- removes `isInline` from story and visual test
no changeset needed, since the target branch has this.

refactor(text): remove isinline tests story

---

.changeset/unlucky-mirrors-argue.md
package.json
packages/components/data-table-manager/package.json
packages/components/data-table/package.json
packages/components/pagination/package.json
packages/components/pagination/src/page-navigator/page-navigator.js
packages/components/pagination/src/pagination.spec.js
yarn.lock

- use `formik` state with `enableReinitialize`
- reference #1838 
In previous implementation, when the client passes a `page` it is set as the `initial` state of `PageNavigator` and from there leverage an internal state via `useState()`
When the `page` prop updates, `PageNavigator` doesn't reflect the updated changes as the prop is accept in subsequent renders.
use `formik` to manage the state with `enableReinitialize`, this gives us a couple of advantages.
- previous implementation of focus and blur handle are abstracted away from the pagination. They are now handled with formik with the help of the `validateOnBlur`, `validateOnChange` and `validateOnMount` configs
- via `enableReinitialize`, the internal formik state updates

refactor(page-navigator): use formik state

---

.changeset/slow-grapes-hope.md
packages/hooks/package.json
packages/hooks/src/index.js
packages/hooks/src/use-data-table-sorting-state/index.js
packages/hooks/src/use-data-table-sorting-state/use-data-table-sorting-state.js
packages/hooks/src/use-data-table-sorting-state/use-data-table-sorting-state.spec.js
packages/hooks/src/use-pagination-state/index.js
packages/hooks/src/use-pagination-state/use-pagination-state.js
packages/hooks/src/use-pagination-state/use-pagination-state.spec.js

- adds `pagination-state` hook
- adds `data-table-sort-state` hook
to be frank, I'm not sure if this is the correct naming or if this is the repo for it,
because it is more than likely that this hook is used to forward the state to fetchers within the MC. feedback welcome
We need to expose these hooks so that other consumers than the Merchant Center can use this interchangeably with the Pagination component (for pagination-state) without having to re-implement it themselves.
The idea is that once this is merged, we migrate the MC to use this.
shall be included in this release https://github.com/commercetools/ui-kit/pull/1841

Add pagination and table sorting state

---

packages/components/text/README.md
packages/components/text/src/text.spec.js
packages/components/text/src/text.story.js
packages/components/text/src/text.styles.ts
packages/components/text/src/text.tsx
packages/components/text/src/text.visualroute.js

- caused by #1824 
Discovered when migration app-kit
https://github.com/commercetools/merchant-center-application-kit/pull/2131#discussion_r609585711
I don't think `isInline` was marked deprecated on `Text.Detail` in the first place, nor was it intended that `Text.Detail` should support `as={}` prop.

refactor(text): accept `as` prop for inline render of `Text.Detail`

---

.changeset/violet-beans-perform.md
packages/components/spacings/spacings-inline/README.md

Document the alternative when it's needed to use the CSS property `flex-wrap` in the component `<Spacings.Inline />`. I found out about this via https://github.com/commercetools/ui-kit/pull/899.

docs(spacings-inline): flex-wrap alternative

---

README.md

Fixes link on main `README` to point to the right file.

docs(readme): fix link to `custom-properties`

---

.changeset/loud-feet-remain.md
presets/ui-kit/src/index.js

exports hooks from the presets.
This is needed within MC.

chore(preset): export pagination and sorting hooks

---

.changeset/lemon-eagles-sip.md
packages/hooks/src/use-data-table-sorting-state/use-data-table-sorting-state.js
packages/hooks/src/use-pagination-state/use-pagination-state.js

😬 
We accidentally overrode the key, where the intention is to assign the value designated for the key.

fix(hooks): apply a value if available

---

.changeset/great-pumpkins-fry.md
.changeset/wild-elephants-hug.md
packages/components/buttons/secondary-button/src/secondary-button.tsx
packages/components/inputs/text-input/src/text-input.tsx

It turns out that the TypeScript migration came with some mistakes 😅 .
My idea to address this is continue pushing towards master and use the canary build on this PR until the tests has passed. 
Given the tests passes, I will then do a release and update the client PR again.
https://github.com/commercetools/merchant-center-frontend/pull/10770

fix(components): set text-input.onChange option, update to prop to use Location

---

.changeset/big-bobcats-shout.md
packages/components/data-table-manager/src/column-settings-manager/column-settings-manager.js
packages/components/data-table-manager/src/column-settings-manager/column-settings-manager.spec.js
packages/components/data-table-manager/src/data-table-manager.story.js
packages/components/data-table-manager/src/data-table-settings/data-table-settings.js

According to `<DataTableManager />` documentation the name of the prop controlling presence of search fields in column manager is `areHiddenColumnsSearchable`. But, it is never took in account, and `<ColumnSettingsManager/>` relies on an undocumented prop called `disableHiddenColumnSearch`. 
This PR brings searching behaviour in accordance with docs.

fix(data-table-manager): areHiddenColumnsSearchable prop has no effect

---

.changeset/old-bugs-exist.md
packages/components/data-table-manager/src/data-table-settings/data-table-settings.js

`<DataTableManager />` wraps provided top bar controls in an unstyled `<div />`. That brings some troubles when styling controls being shown in a table's top bar. In general, as that `<div />` doesn't grow, it works against UI-Kit layout pattern (or let's better say MC pattern of UIKit usage) of letting controls grow up to the limit provided by the wrapping `<Constraints.Horizontal />`.
This PR solves described issue by making top bar container grow (by adding `flex-grow: 1`):
|Before|After|
|--|--|
|![Screenshot from 2021-06-02 12-13-05](https://user-images.githubusercontent.com/1228431/120441835-6adc3e80-c39e-11eb-986b-3408c1af9031.png)|![Screenshot from 2021-06-02 12-11-43](https://user-images.githubusercontent.com/1228431/120441891-7cbde180-c39e-11eb-97d6-fd25b31dda16.png)| 
I have …

fix(data-table-manager): make top bar take up all available space

---

.changeset/khaki-mirrors-fold.md
packages/components/link/package.json
packages/components/link/src/link.tsx
packages/components/link/src/link.visualroute.js

This automatically adds an `ExternalLinkIcon` to any `Link` which has `isExternal`.
We learned that we don't consistently use the same patterns for external links and have to custom build components internally when a link is external and should have an icon to reflect that.
The discussion has open ends, for instance if the link should be underlined. As a result this is not ready. It's merely the result of a first investigation anybody could pick up.

feat(link): add icon when link is external

---

.changeset/five-items-train.md
packages/components/link/src/link.tsx

In some cases the `Link` is used in text where inline flex has to be used to not accidentally line break.

fix(link): to use inline flex

---

.changeset/smooth-phones-look.md
packages/components/link/src/link.tsx

`children` is not required by the types, neither prop-types.

fix(link): prop-types for children

---

.changeset/light-gifts-jam.md
packages/components/link/src/link.tsx

This fixes an alignment issue with the icon on small screens.
Internally we always used a spacing `Spacings.Inline` or `inline-flex` to position the icon to the text. Turns out this implementation is flawed. On small screen sizes it will, due to a line breaks, position the icon falsely. 
As a proposed solution we can avoid Flexbox altogether and just vertically align the icon to the buttom.

fix(link): vertical alignment of icon

---

generators/readme/package.json
generators/readme/src/index.ts
generators/readme/src/utils/stringify-options.ts
generators/readme/test/generate-readme.spec.ts
jest.ts-test.config.js
yarn.lock

Reverts commercetools/ui-kit#1969
Using ESM packages is just a rabbit hole and requires lots of workarounds. Let's just revert things back for now.

Revert "fix(deps): update dependency unified to v10"

---

.changeset/spotty-clouds-warn.md
packages/components/icons/package.json
packages/components/icons/src/inline-svg/inline-svg.tsx
yarn.lock

The attempt to fix the issue with `DOMPurify` and SSR (#2037 ) didn't really work.
We can simply have a better safeguard check, if the DOM is available.

fix(icons): use better safeguard for SSR

---

scripts/postinstall.sh

Infinite loop when running initialization command in some cases
It seems that sometimes there is an infinite loop when running the initialization command on a fresh cloned repository.
Running `yarn` from the root directory have this [post-install](https://github.com/commercetools/ui-kit/blob/main/scripts/postinstall.sh) process where it tries to install isolated dependencies for the documentation tool (Storybook) but it does not end. After it install those dependencies, the process starts over again.

fix: random infinite loop initializing project

---

.changeset/quick-lions-obey.md
packages/components/data-table-manager/src/data-table-manager.tsx
packages/components/data-table-manager/src/export-types.ts
packages/components/data-table-manager/src/index.ts
packages/components/data-table/src/export-types.ts
packages/components/data-table/src/index.ts
packages/hooks/src/index.ts
packages/hooks/src/use-data-table-sorting-state/export-types.ts
packages/hooks/src/use-data-table-sorting-state/index.ts
packages/hooks/src/use-data-table-sorting-state/use-data-table-sorting-state.ts

when trying to build a ui to display some data table information with typescript I found some useful types are not exported.
Some of the types regarding `DataTable` and `DataTableManager` components and also for `useDataTableSortingState' hook are needed to seamlessly integrate those in a new view so the goal of this PR would be to have them publicly exposed for consumers to use them.

Export Typescript types related to data tables

---

docs/.storybook/configs/intl-context.js

The `i18n` package does not export the messages since some time, so we need to map them explicitly.

fix(storybook): intl setup

---

.changeset/strange-bugs-vanish.md
packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.tsx
packages/components/fields/async-select-field/src/async-select-field.tsx
packages/components/fields/creatable-select-field/src/creatable-select-field.tsx
packages/components/fields/search-select-field/src/search-select-field.tsx

Suppress invalid props warnings in some field components.
We were told that some field components are raising some warnings regarding the `touched` prop when they also have the `isMulti` prop with the value `true`.
This is because we are not correctly checking that `touched` property can be undefined while the input has not been gained focus yet.
Affected components:
* async-creatable-table-field
* async-select-field
* creatable-select-field
* search-select-field
closes #2162

fix unexpected warnings in some field components

---

.changeset/fuzzy-moose-fly.md
packages/components/grid/README.md
packages/components/grid/docs/usage-example.js

Fix issue with code snippet on grid component usage

Fix issue with code snippet on grid component usage

---

README.md

This PR adds a top-level Storybook link to the UI Kit documentation
A nonzero number of developers (myself included 😅 ) have reached out to ask where the link to the UI Kit Storybook is, and I've often found myself landing on this page finding it difficult to find it 🔍 .
I figured we could add one at the top level, but as this package is open source, I was unsure of any formalities surrounding editing the documentation here. I'm mostly just throwing this PR at the wall to see if it sticks.

chore(ui-kit): add top-level storybook link to docs

---

.changeset/old-jeans-yell.md
packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.form.story.js
packages/components/inputs/rich-text-utils/src/html/html.spec.js
packages/components/inputs/rich-text-utils/src/html/html.tsx
packages/components/inputs/rich-text-utils/src/html/index.ts
packages/components/inputs/rich-text-utils/src/localized/localized.spec.js
packages/components/inputs/rich-text-utils/src/slate-helpers.tsx

In order to make rich text inputs work properly with Formik if there is no text entered the input should return empty string instead of empty paragraph (`<p></p>`). That implies some changes in the way serialization has worked before and what some unit tests expected.
Other than that, custom module declarations were moved to `html.tsx` file, since they were not visible previously during `tsc-files` type checks.

refactor(rich-text): return empty string instead of empty paragraph

---

.github-labelsrc.json
.github/workflows/close-inactive-issues.yml
.github/workflows/main.yml

Added action to mark issues as stale after 14 days of inactivity and close them after 14 more days

Add CI job for stale bot

---

.changeset/mean-glasses-pull.md
packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.visualspec.js
packages/components/inputs/rich-text-input/src/rich-text-input.visualspec.js

I've noticed the visual regression test for the `LocalizedRichTextInput` fails randomly in CI so I tried to updated it to make it more robust.
When the test failed it was always trying to assert the state of the rich text input after some manipulation.
Since it fails randomly, I believe this is a timing issue where some changes in the underlying library (`slate`) are not reflected fast enough in the test environment.
Instead of trying to slow down the test a little more (we are already slowing it down a bit), I opted for changing some assertions to be async so we wait for the changes to be reflected in the UI.

Improve LocalizedRichTextInput VRT

---

.github/workflows/close-inactive-issues.yml

This PR activates the GitHub action we implemented to deal with issues that don't have replies from their authors in a long period of time after we replied.
(_currently it's working in `dry-run` mode_).

Activate stale github action

---

.changeset/weak-avocados-flow.md
packages/components/collapsible-panel/package.json
packages/components/collapsible-panel/src/collapsible-panel.spec.js
packages/components/collapsible-panel/src/collapsible-panel.tsx
yarn.lock

`CollapsiblePanel` component does not correctly autogenerate IDs. 
When the `CollapsiblePanel` component is used and no `id` property is provided, the autogenerated value is not correctly calculated so, if a consumer uses several instances of this component in the same view, they all will have the same ID in the rendered HTML.
I also found some room for improvements in the accessibility attributes of the component based of [this reference](https://w3c.github.io/aria-practices/examples/accordion/accordion.html).

Fix CollapsiblePanel default ID generation

---

.changeset/tall-cooks-sneeze.md
packages/components/inputs/select-input/src/select-input.spec.js
packages/components/inputs/select-utils/src/clear-indicator/clear-indicator.tsx

The aim of this PR is to add some accessibility improvements to the `ClearIndicator` component.
The warning from `Lighthouse`:
```
[aria-hidden="true"] elements contain focusable descendents. Focusable descendents within an `[aria-hidden="true"]` element prevent those interactive elements from being available to users of assistive technologies like screen readers.
```

fix: `ClearIndicator` accessibility improvements

---

.changeset/wet-lions-sniff.md
packages/components/avatar/src/avatar.tsx

This PR attempts to fix the error reported by axe
```
Alternative text of images should not be repeated as text. 
Element contains <img> element with alt text that duplicates existing text
```

fix: `Avatar` accessibility improvements

---

.changeset/healthy-rockets-pretend.md
packages/components/inputs/rich-text-utils/src/html/html.spec.js
packages/components/inputs/rich-text-utils/src/html/html.tsx
packages/components/inputs/rich-text-utils/src/is-empty/is-empty.spec.js

Fixes regression in `@commercetools-uikit/rich-text-utils` related to deserialization of nested html markup

fix: enable deserialization of nested html markup

---

.changeset/slow-bags-cheer.md
packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.visualroute.jsx
packages/components/inputs/rich-text-utils/src/html/html.spec.js
packages/components/inputs/rich-text-utils/src/html/html.tsx

This is a follow up of #2235.
I'm very sorry this was done in turns, I should have added visual tests to the previous PR 😕
It turned out that each text node provided to `slate` editor has to be wrapped with a paragraph.
For instance:
`<p>this </p>will<p> fail</p>`
`<p>this </p><p>is</p><p> ok</>`

fix: deserialization - wrap each resulting non-empty child text node with a paragraph

---

design-system/scripts/generate-custom-properties.js
design-system/src/custom-properties.ts
visual-testing-app/index.html

This PR includes a proposal fix for the problem we found when implementing Theming support with Percy snapshot testing.
It seems Percy does not support using CSS vars the way we want to use them (CSS in JS).
Since our components use the `custom-properties.ts` file to get access to design tokens values which we want to be CSS vars in the new version but that does not seem to be working with Percy snapshot testing, following their recommendation (not to use CSS vars), in this proposal we add a marker in the visual testing app document (the one we use for snapshot testing) and use it in the mentioned file to not return a CSS var but the fixed default value when rendering in that environment.

[POC] Fix proposal for Percy related issues with CSS vars

---

.changeset/curvy-worms-invite.md
packages/components/buttons/accessible-button/src/accessible-button.spec.js
packages/components/buttons/accessible-button/src/accessible-button.tsx

SecondaryButton components rendered as` a` tags lose their role attribute when disabled. We should still see the role attribute even if the component is disabled.

Acccessibility button: display role attribute when SecondaryButton component is disabled

---

design-system/src/theme-provider.spec.js
design-system/src/theme-provider.tsx
design-system/src/theme-provider.visualroute.jsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX128lVqpOwrffDpRNHsoxrRgNT0r5z644%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=QALXUDg)
Remove `applyTheme` from `useTheme` hook since we don't see the need for it.
We expect users to handle the current theme on their side and provide it to the `ThemeProvider` as a prop.
When they'll need to change it, they would just provide a new value in the `theme` prop of the provider.
`useTheme` hook will only return a string with the current provider theme.

Remove unnecessary helper from theming React hook

---

.changeset/hot-points-flow.md
packages/components/collapsible-panel/src/collapsible-panel.styles.tsx

Increase header vertical padding in `condensed` mode.
Updated vertical padding of panel header from `4px` to `8px` when `condensed` property is used.
closes #2275

Update `CollapsiblePanel` header styles

---

.changeset/thirty-jars-argue.md
packages/components/fields/creatable-select-field/src/creatable-select-field.tsx
packages/components/fields/select-field/src/select-field.tsx
packages/components/inputs/creatable-select-input/src/creatable-select-input.tsx
packages/components/inputs/select-input/src/select-input.tsx

fix: add missing `label` property to `options` prop type of select inputs and select fields

---

.changeset/heavy-parrots-hear.md
packages/components/fields/creatable-select-field/src/creatable-select-field.tsx
packages/components/fields/select-field/src/select-field.tsx
packages/components/inputs/creatable-select-input/src/creatable-select-input.tsx
packages/components/inputs/select-input/src/select-input.tsx

Fixes the type of options `label` property to allow more types than a string.
When providing the value for the `label` property of the options, users might use not only strings but other types as well (ex: an element for a rich label).
We widen the type of that property to support different use cases.

Fix `label` property type in `options prop` type of select inputs and select fields

---

.changeset/slimy-walls-worry.md
packages/components/data-table/src/data-table.story.js
packages/components/data-table/src/header-cell.styles.tsx
packages/components/data-table/src/header-cell.tsx

This PR fixes the issue opened regarding data-table info button arrangement. 
Fixes #2283

Fix info button arrangement in the data table component

---

.changeset/smooth-ears-drum.md
packages/components/data-table/src/cell.styles.tsx
packages/components/data-table/src/header-cell.styles.tsx
packages/components/data-table/src/header-cell.tsx

Fix icon displaced to far right when data table cell is expanded
Before: 
After:

Fix icon displaced to far right when data table cell is expanded

---

.changeset/warm-pigs-raise.md
packages/components/text/README.md
packages/components/text/src/text.story.js
packages/components/text/src/text.styles.ts
packages/components/text/src/text.tsx
packages/components/text/src/text.visualroute.jsx

Since teams are using the custom styling to achieve the strikethrough text in the Merchant center, I introduced a new prop `strikethrough` for body and detail text components.
Open issue: https://github.com/commercetools/ui-kit/issues/2217

Adding the strikethrough property to text component

---

design-system/scripts/generate-design-tokens.js

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX181Ihoct2AUlIvW3Xnkp4wQi8aQU1jy4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=9-mOGm8)
Extend design tokens naming so we can support more use cases.
While working with the designs for the new theme and making our components compatible with both current and new UI we-re finding finding some restrictions in tokens naming that it seems we need to extend.
So now the naming pattern we allow is like this:
```
<attribute>-for-<component-group>(-[when|as]-[<variant|state>])?
```
This pattern allows for this token names:
```
background-color-for-tag
font-color-for-text-when-inverted
font-size-for-text-as-h1
```
What we …

Extend design tokens naming rules

---

.changeset/three-poets-rule.md
packages/components/link/README.md
packages/components/link/src/link.spec.js
packages/components/link/src/link.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1K2q1DTyiIPZTdgr7TmzzLpWGAS5DB53w%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=mcxXD_f)
`Link` component allows for the `onClick` prop but it is not defined in its props typescript type.
We just add the `onClick` to the `Link` component props typescript definition and also include a couple of tests to verify this prop is called when provided after clicking the component, both when we render a `react-router-dom` link or a native HTML one.

Export missing prop in `Link` typescript type

---

.changeset/few-toes-roll.md
design-system/src/index.ts
design-system/src/theme-provider.tsx
design-system/src/utils.spec.ts
design-system/src/utils.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX17xWMWk5e7c8strlZy0Ke7ZNR66J8EMQg%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=ZwmdL-5)
Export utility helpers to transform from design tokens to CSS vars
We realized there are a couple of consumer repositories that are implementing transformer utilities to convert from design tokens map to CSS vars.
Having an input design tokens map like this:
```
{
colorPrimary: '#00b39e',
borderRadius4: '4px',
}
```
We might want to transform that object to be a map where keys are CSS var names and values are the CSS values:
```
{
'--color-primary': '#00b39e',
'--border-radius-4': '4px',
}
```
Another option would be the …

Export utility helpers to transform from design tokens to CSS vars

---

.changeset/purple-flowers-provide.md
design-system/materials/resets.css
docs/.storybook/config.js
docs/.storybook/preview-head.html
docs/.storybook/webpack.config.js
docs/package.json
docs/yarn.lock
visual-testing-app/index.html
visual-testing-app/src/App.jsx
visual-testing-app/src/globals.css

Extracting some of the changes from #2324 
Most of the resets styles are currently [defined in App Kit](https://github.com/commercetools/merchant-center-application-kit/blob/87853f778b03fc86363333e7c1bc1953a7728ef4/packages/application-shell/src/components/application-shell/global-styles.tsx#L53-L98). However, some of them are tightly related to basic styles which are more a concern of the design system.
This PR proposes to expose a `resets.css` file from the `design-system` package that can be used by the consumers of the UI Kit. This should make it easier to manage basic changes in one place.
Happy to hear your thoughts and if this makes sense or not.

feat(design-system): export `resets.css` styles

---

docs/.storybook/configs/theme-context.js

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19f5r7Q03K8ENjeXiPU777K9OcwZ1ElOQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=lfZa2-D)
Design tokens are not loaded in Storybook production environment. 
Since we don't want to make public the testing theme, we are not rendering the Theme switcher in the production environment but, as that switcher is the one rendering the `ThemeProvider` component which deals with loading the design tokens in the document, no token is loaded.
This is a basic and fast solution where we render the switcher although we will only have one option available in production environment.

Fix design tokens not loading in production environment

---

.changeset/rotten-moons-peel.md
design-system/materials/internals/definition.yaml
design-system/src/design-tokens.ts
packages/components/tag/src/tag-body.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18wttyCCnTnBQif6FHI2uESuuflMfBOMbE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=SI3CGuH)
Fix `Tag` component design tokens values in new theme
The values for the background color used in the new theme were invalid. Actually, the background color should not change by theme.
Also, I found a visual bug with the right border of the component when using type warning, onClick and the mouse over the component:

Fix `Tag` component design tokens values in new theme

---

.changeset/heavy-hornets-pretend.md
.changeset/nasty-ears-deliver.md
design-system/src/theme-provider.tsx
design-system/src/theme-provider.visualroute.jsx
packages/components/tag/src/tag-body.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1q4bxywP8JWXyyl0TMBaOo3CB7WWR4ud0%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=a27jD5v)
`useTheme` hook returns the selected theme but the value gets out of sync if it's changed.
Initially we thought the theme would not needed to be changed for the purpose of the migration but as we started working on it, we realized it's quite useful and also that's something we would like to have in the future (if we support official themes).
The current selected theme is not stored in a context state but in the DOM element where we set the design tokens up.
The `useHook` was just reading that value after first render so …

Fix `useTheme` hook

---

.changeset/twenty-trains-count.md
packages/components/stamp/src/stamp.tsx

Remove `overrideTextColor` prop from `Stamp` component.
This prop was previously introduced but not published.
We realized we won't be needing such a prop so we prefer to remove it before releasing a new versions of the library.

Remove prop from `Stamp` component

---

.changeset/seven-guests-raise.md
packages/components/stamp/src/stamp.tsx

Remove `Stamp` breaking warning
We updated the `Stamp` component to use inline props instead of `children` for the text to render and, while we temporary allow for both (`children` is ignored if new inline props are provided) to make transition easier, we added a `warning` to let users know about this change that actually throws an error in development mode.
In this PR we remove that `warning` and we will think on a better solution to let users know about this change.

Remove `Stamp` breaking warning

---

.changeset/gorgeous-snails-sip.md
packages/components/inputs/time-input/src/time-input-body.tsx
packages/components/inputs/time-input/src/time-input.tsx

We don't want to display the clear icon when there is no value in the input.
Here is an example of the new behavior:
[Components _ Inputs - TimeInput ⋅ Storybook.webm](https://user-images.githubusercontent.com/97907068/217501168-85176e67-a306-4be1-ab41-374466c9a9a4.webm)

[`TimeInput`] Adjust clear icon visibility

---

.changeset/hot-files-marry.md
.changeset/nice-apricots-tan.md
design-system/package.json
design-system/src/theme-provider.tsx
packages/hooks/package.json
packages/hooks/src/index.ts
packages/hooks/src/use-mutation-observer/index.ts
packages/hooks/src/use-mutation-observer/use-mutation-observer.ts
yarn.lock

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18N7ccWKQq24UO8HEqZe8XsQLnPSSpcxzc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=9Tthkrf)
Include a new hook to easily use [MutationObserver API](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) in components.
The new implementation has been copied from the `app-kit` [repository](https://github.com/commercetools/merchant-center-application-kit/blob/main/packages/application-components/src/hooks/use-mutation-observer/use-mutation-observer.ts).
There are two changes over the original implementation:
1. `observer` configuration is not passed to the mutation observer factory but to the `observe` …

Add new hook to use `MutationObserver` API

---

.changeset/light-oranges-design.md
design-system/materials/internals/definition.yaml
design-system/src/design-tokens.ts
packages/components/link/src/link.tsx
packages/components/link/src/link.visualroute.jsx

Fix `Link` component `font-size` value in the new theme
We want the `font-size` of the `Link` component to be inherited from its parent in the new theme but it's currently not wroking.
We decided to use `font-size: inherit` for the new theme, but that's making the size to be inherited from the `body` element, not its parent.

Fix `Link` component `font-size` value in the new theme

---

.changeset/old-hounds-study.md
packages/components/inputs/radio-input/src/radio-option.styles.ts

fix(radio-input): radio input default hover area background color

---

.changeset/chilled-boxes-yell.md
packages/components/fields/radio-field/src/radio-field.story.js
packages/components/inputs/radio-input/src/radio-input.story.js
packages/components/inputs/radio-input/src/radio-option.styles.ts

Before:
After:
In `RadioInput` and `RadioField` components' stories we define `Option` label alignment in the stories ([ref](https://github.com/commercetools/ui-kit/blob/29964960c78206aa7b766b2a173f46f0743d8b5c/packages/components/fields/radio-field/src/radio-field.story.js#L112), [ref2](https://github.com/commercetools/ui-kit/blob/29964960c78206aa7b766b2a173f46f0743d8b5c/packages/components/inputs/radio-input/src/radio-input.story.js#L78)). Recent changes in styles and adding `Flexbox` to the label container without specifying the vertical alignment caused some misalignment of the label for the new theme. We missed that unfortunately.
Perhaps adding a ` <Spacings.Inline scale="xs" alignItems="center">` as the `Option`'s children is not the most fortunate decision. We don't show the label …

fix(radio-input): option label alignment

---

.changeset/tall-shirts-roll.md
packages/components/inputs/toggle-input/src/toggle-input.styles.ts
packages/components/inputs/toggle-input/src/toggle.story.js

`<ToggleInput>` used within `<Spacings.Inline>` in the MC:

fix(toggle-input):  overflow when in focused or hovered state

---

.changeset/eighty-items-kick.md
packages/components/inputs/localized-multiline-text-input/src/translation-input.styles.ts
packages/components/inputs/localized-text-input/src/localized-text-input.styles.ts

closes #2483
Before:
|  LocalizedTextInput |  LocalizedMultilineTextInput |  
|---|---|
|  <img width="369" alt="Screenshot 2023-04-06 at 14 57 48" src="https://user-images.githubusercontent.com/49066275/230385387-740f6610-c868-4163-b2ad-8f00105e9bf5.png"> |   <img width="376" alt="Screenshot 2023-04-06 at 14 59 24" src="https://user-images.githubusercontent.com/49066275/230385790-89712d29-e1d9-4c02-b7e8-8ecd15a649f5.png"> |
After:
|  LocalizedTextInput | LocalizedMultilineTextInput  |  
|---|---|
|  <img width="394" alt="Screenshot 2023-04-06 at 14 58 44" src="https://user-images.githubusercontent.com/49066275/230385558-1306c07e-480e-4d7d-a58a-eb06718c60c1.png"> |  <img width="378" alt="Screenshot 2023-04-06 at 15 00 52" src="https://user-images.githubusercontent.com/49066275/230386123-ba …

fix: proper border color when localized input in both disabled and read-only state

---

.changeset/poor-wasps-mate.md
packages/components/link/src/link.story.js
packages/components/link/src/link.tsx

For some of the redesigned components `line-height` has been increased. If those components render `<Link isExternal>` as their child, the Link's icon and text are currently misaligned.
Credit to @bradd123 💪

fix: vertical alignment of the external Link's icon

---

.changeset/fast-ducks-run.md
packages/components/inputs/select-input/src/select-input.tsx
packages/components/inputs/select-utils/src/create-select-styles.ts

Issue originating from [the discussion](https://github.com/commercetools/ui-kit/pull/2466#issuecomment-1486896859).

fix: `<SelectInput>` styles when `isMulti` prop is used together with `controlShouldRenderValue`

---

.changeset/serious-peas-run.md
packages/components/text/README.md
packages/components/text/src/text.story.js
packages/components/text/src/text.styles.ts
packages/components/text/src/text.tsx
packages/components/text/src/text.visualroute.jsx

When using `Spacings.Inline` to lay out two elements side-by-side, if one of the elements is a text element and the other is large enough, the text may wrap, which is undesirable in some cases.
That's why we've introduced the `nowrap` prop for the Text components. 
It renders the `white-space` CSS prop and then the element will not be wrapped to a new line.
Closes [this issue](https://github.com/commercetools/ui-kit/issues/2474).
**Before the change:**
**After the change:**

Adding `nowrap` prop to the Text component

---

.changeset/modern-books-tie.md
.changeset/tidy-shoes-play.md
packages/components/fields/select-field/src/export-types.ts
packages/components/fields/select-field/src/select-field.tsx
packages/components/inputs/select-input/src/export-types.ts
packages/components/inputs/select-input/src/select-input.tsx

Export more Typescript types from Select components
In order to help consumers using `SelectInput` and `SelectField` components, I propose to expose more TS types from them.

Export more Typescript types from Select components

---

packages/components/fields/localized-multiline-text-field/src/localized-multiline-text-field.visualroute.jsx
packages/components/inputs/localized-multiline-text-input/src/localized-multiline-text-input.visualroute.jsx

Disable flaky visual regression tests
We have some visual regression tests that are constantly and randomly failing because the components they tests execute some ui adjustments after being mounted and the current Percy implementation does not address them reliable in terms of timing.
We're disabling them until we (or Percy) find a solid solution.

Disable flaky visual regression tests

---

.changeset/cuddly-months-give.md
packages/components/tag/package.json
packages/components/tag/src/tag-list/tag-list.tsx
yarn.lock

I’ve been trying to integrate the new `<TagList>` component in the mc-fe and it turned out that:
- in almost every case we apply custom styles via a `className`. Some styles are quite sophisticated so I didn't want to change anything in the implementation and only pass the classname.
- most of the components are tested via `data-testid` attribute
We accept `className` as a prop in case of several ui-kit components, so I thought about doing it here as well instead of using a wrapper with custom styles in the client code. But I'm open to suggestions if you see it differently.
Another thing is the changeset. I've enclosed it but I'm not sure we need it if the component hasn’t been released yet 🤔, any ideas?

fix: enable passing `data-*` attributes to `TagList`

---

.changeset/warm-yaks-admire.md
packages/components/inputs/money-input/src/money-input.spec.js
packages/components/inputs/money-input/src/money-input.tsx

Add support for negative numbers in `MoneyInput` component.
(_closes #2363_)
The component didn't support negative numbers as there was a bug when parsing the input value removing the negative sign.

Add support for negative numbers in `MoneyInput` component

---

.changeset/olive-readers-return.md
packages/components/inputs/select-input/src/select-input.tsx
packages/components/inputs/select-utils/src/create-select-styles.ts

Closes #2503
Regression resulting from https://github.com/commercetools/ui-kit/pull/2490/
Appearing in all select fields and inputs (apart from `SelectField` and `SelectInput` where the default `controlShouldRenderValue` prop value was added).

fix: ui regression with `controlShouldRenderValue`

---

.changeset/afraid-brooms-punch.md
packages/components/data-table/src/data-table.tsx

This PR extends `TDataTableProps` type by using the generic row type in its `columns` property
While typing column definitions in one of Discounts web app features, the following error appeared. The type of the `columns` prop of the `DataTable` component can be improved.

fix: extend TDataTableProps type

---

.changeset/old-pigs-check.md
design-system/src/theme-provider.tsx

`useTheme.themedValue` helper is causing re-renders in memoized code.
While working on Discounts web app and trying to avoid re-renders on a form, I realized that `useTheme.themedValue` helper was causing them.
I know this helper is ephemeral, but is being used in production while the cleanup phase is not finished yet.

fix: memoize `useTheme.themedValue` helper

---

packages/components/inputs/input-utils/src/multiline-input/multiline-input.tsx
packages/components/inputs/localized-multiline-text-input/src/translation-input.tsx
packages/components/inputs/multiline-text-input/src/multiline-text-input.tsx

Alternative proposal (#2511 ) for multiline inputs height management.
The idea is to abstract if the component has more than one row in the util `MultilineInput` component so it's easier for its consumers to deal with it since the former is the one which has all the info to calculate the values.

Alternative proposal for multiline inputs height management

---

.changeset/hot-ways-care.md
packages/hooks/index.ts
packages/hooks/package.json
packages/hooks/polyfills.js
packages/hooks/polyfills/package.json
packages/hooks/src/polyfills.ts
packages/hooks/src/use-mutation-observer/use-mutation-observer.ts

Follow up of #2485 
Including the polyfill into the normal bundle will result in the polyfill code to be removed because the bundle itself has already evaluated it.
However, what we want is to provide the polyfill to consumers of the package as it needs to be evaluated when building the end application.
Therefore, we should export the polyfill as a separate entry point.

fix(hooks): export polyfills as a separate entry point

---

.changeset/curvy-boats-hunt.md
packages/components/tag/src/tag-body.tsx
packages/components/tag/src/tag.spec.js

This PR fixes an issue with rendering `<div>`s as children of `<Tag>` component

fix(Tag): make `TagBody` render as `span` rather than `p`

---

.changeset/nervous-insects-dance.md
packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.story.js
packages/components/inputs/rich-text-input/src/rich-text-input.story.js
packages/components/inputs/rich-text-utils/src/html/html.spec.js
packages/components/inputs/rich-text-utils/src/html/html.tsx
packages/components/inputs/rich-text-utils/src/slate-helpers.tsx

This PR is meant to fix:
- `<sup>` and `<sub>` deserialization
- issue with rich text state resetting
- removes unnecessary wrapping every text node with paragraph in the deserialization function
- adds a more complex story to enable manual tests of `<RichTextInput>` and `LocalizedRichTextInput>` 
⚠️ ⚠️ ⚠️ it does not cover #2522 ⚠️ ⚠️ ⚠️

fix(RichTextInput): deserialization of `<sup>` and `<sub>`

---

.changeset/funny-melons-design.md
packages/components/inputs/radio-input/src/radio-option.styles.ts

Enable proper alignment of <RadioInput.Option> sibling components
n the current implementation of the <RadioInput.Option> there is no possibility of proper aligning of sibling components out of the box. This leads to misalignments like in the picture below:

Align siblings of radio input options

---

.changeset/rare-jars-exercise.md
packages/components/collapsible-panel/src/collapsible-panel-header.tsx
packages/components/collapsible-panel/src/collapsible-panel.spec.js
packages/components/collapsible-panel/src/collapsible-panel.tsx

We've found an inconsistency in out `CollapsiblePanel` component manages the `header` prop.
The issue is that we are rendering an invalid HTML structure when passing a `<CollapsiblePanelHeader>` component as a `header` prop and when `condensed` prop is set as true in `<CollapsiblePanel>`. 
In that case it would wrap `<h2>` tag in the `<h4>` which would cause the error - `<h2> cannot appear as a child of <h4>`.
This is a temporary fix, in order to unblock us and until we have a chance to discuss it with Filip on how to proceed further.

Fix for the heading issue of the `CollapsiblePanel'

---

.changeset/nine-cooks-promise.md
jest-puppeteer.config.js
packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.visualspec.js
packages/components/inputs/rich-text-input/src/rich-text-input.visualspec.js

Update `puppeteer` config param
We have some warning logs when running the visual regression tests related to some configuration update of the `puppeteer` package:
That package will change the way the headless mode configuration works so I think it's better for use to update consciously.
[Here](https://developer.chrome.com/articles/new-headless/) are more details about this change.

Update `puppeteer` config param

---

.changeset/hip-ducks-jog.md
packages/components/inputs/checkbox-input/src/checkbox-input.tsx

Make the CheckboxIcon not be compressed when wrapping the text.
`CheckboxIcon` is in a flexbox with `LabelTextWrapper` and if they don't fit the flexbox shrinks them both equally, which compresses the icon. It should only shrink the label.

Prevent CheckboxInput icon shrinking when label text wraps

---

.changeset/lazy-icons-drive.md
packages/components/field-label/src/field-label.visualroute.jsx
packages/components/label/src/label.tsx

This PR closes - [issue](https://github.com/commercetools/ui-kit/issues/2588).
There was an issue when displaying `FieldLabel` with `ReactNode` title and the required asterisk.

Fix <FieldLabel> title when is `ReactNode`

---

.changeset/khaki-mirrors-refuse.md
packages/components/tooltip/src/tooltip.tsx

Fix edge case with managing end transition in `Tooltip` component
We've seen some end-to-end test having random problems that involves the `Tooltip` component.
The error we see in the browser console in those cases is like this:
Code referenced in the stack trace:
It means, for some unknown reason, when we want to add a listener for the animation ending, the expected element does not exist anymore.
I don't understand this behaviour. Maybe it's due to the e2e test environment being slow (just a guess).
In this  PR I just check for that potential condition and, if there is no element to be animated, I assume is not in the DOM anymore and apply the side effect (calling the `onClose` props callback) right away.
I'm not adding any test because I don't know how to reproduce this error.
Any …

Fix edge case with managing end transition in `Tooltip` component

---

.changeset/calm-hairs-try.md
packages/calendar-utils/package.json
packages/calendar-utils/src/calendar.spec.js
packages/calendar-utils/src/calendar.ts
yarn.lock

Fixes [the reported issue](https://commercetools.atlassian.net/browse/SUPPORT-22938?atlOrigin=eyJpIjoiNDcwZTc0MWY5NzRjNDJlYjg5ZjQ1NDNmZjIyMGZkZTciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[Sentry error log](https://commercetools.sentry.io/issues/4477369881/events/3755b7e3471b478b88e632d15539ed52/?project=1549825&referrer=issue-list&statsPeriod=14d) 
The error:
Please mind all contexts in which `getPaddingDayCount` helper function is used ([1](https://github.com/commercetools/ui-kit/blob/73bc8841022ea3b46dc9e2b75d3f9fd3e1d4fff6/packages/components/inputs/date-input/src/date-input.tsx#L253-L254), [2](https://github.com/commercetools/ui-kit/blob/73bc8841022ea3b46dc9e2b75d3f9fd3e1d4fff6/packages/components/inputs/date-range-input/src/date-range-input.tsx#L430-L434), …

fix: DateInput when providing invalid calendar date input

---

.changeset/funny-eggs-act.md
packages/components/inputs/rich-text-utils/src/html/html.spec.js
packages/components/inputs/rich-text-utils/src/html/html.tsx

Fixes #2605 
You may test the result by pasting the contents:
```
<p>\r\n<em>Bitte beachten Sie: Die Lieferung erfolgt nach Verf&uuml;gbarkeit - Jahrgangs- und Designw&uuml;nschen k&ouml;nnen wir leider nicht nachkommen. Wir danken Ihnen f&uuml;r Ihr Verst&auml;ndnis.</em>\r\n</p>\r\n\r\n<h3>Informationen zum Gold K&auml;nguru 1/4</h3>\r\n<p>\r\nDer <strong>Australian Nugget (Gold K&auml;nguru)</strong> ist eine australische Goldm&uuml;nze, die erstmals 1986 von der Perth Mint gepr&auml;gt wurde und sich vor allem dank der j&auml;hrlich wechselnden Motive auf der Vorderseite weltweiter Beliebtheit erfreut. Die M&uuml;nze hat einen Feingehalt von 999,9 und gilt als offizielles Zahlungsmittel.\r\n</p>\r\n\r\n<p >\r\nSeit 1987 wird der <strong>Australian Nugget</strong> in den …
```

fix(RichTextEditor): handle invalid markup passed to a text node

---

.changeset/violet-mice-change.md
packages/components/tooltip/src/tooltip.styles.ts
packages/components/tooltip/src/tooltip.visualroute.jsx

Currently, when a tooltip is contained within a parent element with a `white-space` property set to `nowrap`, it will inherit the property and that will create an unwanted layout if the tooltip label is long.
We can address this issue by explicitly setting up the `white-space` to `break-spaces` and move to the next line when the text exceeds a certain length.

Tooltip long title issue

---

.changeset/early-peas-return.md
packages/components/inputs/localized-rich-text-input/src/editor.styles.ts
packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.tsx

Fixes https://github.com/commercetools/ui-kit/issues/2626
In the `<LocalizedRichTextEditor>` component, when `<RichTextEditors>` for certain languages are first rendered, the refs are created. When the editors are hidden later on, the refs are null, so calling the reset callback for those hidden editors ends up with:

fix(LocalizedRichTextInput): reset callback

---

.changeset/proud-pugs-decide.md
.changeset/stale-radios-punch.md
packages/components/card/src/card.tsx
packages/components/card/src/card.visualroute.jsx
packages/components/spacings/spacings-inset-squish/README.md
packages/components/spacings/spacings-inset-squish/src/inset-squish.tsx
packages/components/spacings/spacings-inset/README.md
packages/components/spacings/spacings-inset/src/inset.tsx

Refactor `Inset` components vertical space usage
We found a problem with the vertical space of the `Card` component contents which we tried to address in [this PR](https://github.com/commercetools/ui-kit/pull/2624).
In that one, we thought it made sense to address the `Inset` and `InsetSquish` components (as the `Card` is using the former`) since, as container components, they should always use its parent available vertical space but we were wrong.
We noticed several use cases where this is not true so we're now proposing another approach.
The idea is that the vertical space used by `Inset` and `InsetSquish` components can be controlled with a new prop (`useAllAvailableHeight`) defaulting to the previous behaviour and only changing it for the `Card` component use case.
We suggest to use a …

Refactor `Inset` components vertical space usage

---

.changeset/fresh-bugs-shake.md
design-system/materials/custom-properties.css
design-system/materials/custom-properties.json
design-system/materials/internals/definition.yaml
design-system/src/design-tokens.ts
packages/components/text/src/text.styles.ts

This PR covers the following:
**1.)** Component: `Link`
-` font-color-for-link-as-primary`: updated from `color-primary-25` to `color-primary-30`
**2.)** Component: `FlatButton`
- ` font-color-for-flat-button-as-primary` (icon color included) : updated from `color-primary-25` to `color-primary-30`
**3.)** Text styles for tone:primary updated from `colorPrimary` to `colorPrimary30`. 
This affects the following:
- text.caption
- text.detail
- text.body
- text.subheadline

PANGOLIN-3257 / SHIELD-961 - Change color value for links, flat buttons & text

---

.changeset/cool-countries-brake.md
packages/components/tooltip/src/tooltip.styles.ts

Decrease default font size for `Tooltip` component.
We're changing the default font size for the tooltip text from `0.875rem` to `0.75rem`. 
Bear in mind that consumers can customize Tooltip contents, so this change only applies when they don't customize them.

Decrease default font size for `Tooltip` component

---

.changeset/fuzzy-dogs-sip.md
packages/components/data-table/src/use-manual-column-resizing-reducer.ts

This PR fixes the query selector in data table which calculates the individual column's width when user resizes any column.
Before the querySelector was targeting all `th` which was causing issue when a nested table is implemented and `th` of the inner table also considered for the computation. 
In this PR, only `th` of outertable is targeted leaving the inner table's th.
slack reference: https://commercetools.slack.com/archives/CCL83RA06/p1701436677019559

Change queryselector to target outer table's header

---

.changeset/tricky-deers-sparkle.md
packages/components/tooltip/src/tooltip.story.js
packages/components/tooltip/src/tooltip.styles.ts

Remove unnecessary cursor: not-allowed property from tooltip container on the <Tooltip> component.
Closes #2663

Remove unwanted cursor css property

---

.github/workflows/release.yml

[NPM has support for provenance data](https://github.blog/2023-04-19-introducing-npm-package-provenance/) as a mean to increase supply-chain security for published packages.
See documentation on [how to enable it via GitHub Actions](https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions).

ci: include provenance info when publishing packages

---

.changeset/rich-flies-behave.md
packages/components/inputs/select-input/src/select-input.story.js
packages/components/inputs/select-utils/src/create-select-styles.ts

Fix select input components dropdown menu width
We have an issue while calculating the width for the dropdown menu rendered when a select input component is clicked.
The problem is that we are using the minimum width configured also for the maximum width of that element:

Fix select input components dropdown menu width

---

packages/components/view-switcher/src/view-switcher.stories.tsx

[Storybook migration] `ViewSwitcher` alternative proposal
In this PR I've implemented a proposal for refactor the new `ViewSwitcher` Storybook stories to use less typescript casting and reuse rendering logic.
This one is build on top of #2689

[Storybook migration] `ViewSwitcher` alternative proposal

---

.storybook/helpers/categorize.ts
.storybook/helpers/hide-controls.ts
.storybook/helpers/horizontal-constraint-arg-type.ts
.storybook/helpers/index.ts
packages/components/messages/src/error-message/README.mdx
packages/components/messages/src/error-message/error-message.stories.tsx
packages/components/messages/src/warning-message/README.mdx
packages/components/messages/src/warning-message/warning-message.stories.tsx
packages/components/tooltip/README.mdx
packages/components/tooltip/src/tooltip.stories.tsx
packages/components/view-switcher/README.mdx
packages/components/view-switcher/src/view-switcher.stories.tsx

This pull request migrates the initial set of Storybook stories for the `Tooltip`, `ViewSwitcher`, `ErrorMessage`, and `WarningMessage` components

refactor(storybook): migrate to v7 - part 1

---

.changeset/tricky-humans-invite.md
packages/components/card/src/card.tsx

This PR fixes a bug encountered in the Merchant Center, when using clickable `Card` functionality.
Without `to` prop defined:
With `to` prop defined:
TIL `<a>` tags are `display: inline;` by default. By overriding this style, we can match that of the `div` and ensure expected behavior when anchor tags are parent `Card` elements.

fix(ui-kit): override default anchor card wrapper display style

---

.changeset/yellow-ears-remember.md
design-system/materials/custom-properties.css
design-system/materials/custom-properties.json
design-system/materials/internals/definition.yaml
design-system/materials/internals/tokens.story.js
design-system/scripts/generate-design-tokens.js
design-system/src/design-tokens.ts
packages/calendar-utils/src/calendar-menu/calendar-menu.tsx
packages/components/avatar/src/avatar.styles.ts
packages/components/collapsible-panel/src/collapsible-panel.styles.tsx
packages/components/grid/src/grid.visualroute.jsx
packages/components/icons/src/icon.story.js
packages/components/inputs/date-time-input/src/time-input.tsx
packages/components/inputs/localized-rich-text-input/src/editor.styles.ts
packages/components/inputs/rich-text-utils/src/rich-text-body/dropdown.styles.tsx
packages/components/inputs/rich-text-utils/src/rich-text-body/rich-text-body.styles.ts
packages/components/inputs/select-utils/src/create-select-styles.ts
packages/components/primary-action-dropdown/src/primary-action-dropdown.tsx
packages/components/view-switcher/src/view-switcher.styles.ts
test/percy/spec.jsx
visual-testing-app/index.html

Remove design legacy plain tokens
Since we already removed (#2703) temporary design tokens we introduced for last year's redesign, we think this is a good time to also remove the legacy plain tokens as well.
Consumer applications have already been prepared for this.

Remove design legacy plain tokens

---

.changeset/polite-glasses-move.md
packages/components/inputs/select-utils/src/create-select-styles.ts

1. Changing the `font-size` of the `GroupHeading` to '14px'.
___________________________________________________________
2. Setting up 'not-allowed' cursor when `MenuItem` is disabled.

`Select-input` small UI improvements

---

.changeset/beige-mails-explain.md
.changeset/cold-tables-search.md
packages/components/fields/localized-multiline-text-field/src/localized-multiline-text-field.story.js
packages/components/fields/localized-text-field/src/localized-text-field.story.js
packages/components/fields/localized-text-field/src/localized-text-field.tsx
packages/components/inputs/localized-money-input/package.json
packages/components/inputs/localized-money-input/src/localized-money-input.story.js
packages/components/inputs/localized-money-input/src/localized-money-input.tsx
packages/components/inputs/localized-money-input/src/localized-money-input.visualroute.jsx
packages/components/inputs/localized-multiline-text-input/src/localized-multiline-text-input.story.js
packages/components/inputs/localized-multiline-text-input/src/localized-multiline-text-input.visualroute.jsx
packages/components/inputs/localized-multiline-text-input/src/translation-input.tsx
packages/components/inputs/localized-rich-text-input/src/editor.tsx
packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.story.js
packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.visualroute.jsx
packages/components/inputs/localized-text-input/src/localized-text-input.story.js
packages/components/inputs/localized-text-input/src/localized-text-input.tsx
packages/components/inputs/localized-text-input/src/localized-text-input.visualroute.jsx
yarn.lock

Improve handling styles for errors/warnings in localized inputs and fields.
fixes #2730
When localized inputs and fields components users want to provide some error or warning messages, they are currently required to provide a `ReactNode` element using one of our `ErrorMessage` or `WarningMessage` components to wrap the text in order to get the rights styles.
Example:
```jsx
<LocalizedTextField
title="Title"
value={value}
onChange={handleChange}
errorsByLanguage={{
en: <ErrorMessage>This is an error</ErrorMessage>,
}}
/>
```
This should not be a consumer's responsibility so we're changing the way these components handle `errors` and `warnings` so they will include the right styles by default.
Example:
```jsx
<LocalizedTextField
title="Title"
value={value}
onChange={handleChange} …
```

Improve handling styles for errors/warnings in localized inputs and fields

---

.changeset/twenty-paws-join.md
packages/components/view-switcher/src/view-switcher.styles.ts

Fix viewswitcher border radius
Screenshots:
Before: 
After:

Fix viewswitcher border radius

---

packages/components/icons/src/export-types.ts
packages/components/icons/src/inline-svg/export-types.ts
packages/components/icons/src/inline-svg/index.ts
packages/components/icons/src/inline-svg/inline-svg.tsx
packages/components/icons/src/leading-icon/export-types.ts
packages/components/icons/src/leading-icon/index.ts

This is al alternative proposal for #2752.
Here I'm proposing a change in the way we want to expose custom icon components types so they can be consumed from their own entry point.
With the implementation proposed in the original PR, a user wanting to use the `LeadingIcon` component and also access its type would need two different _imports_:
```
import LeadingIcon from '@commercetools-uikit/icons/leading-icon';
import { type TLeadingIconProps } from '@commercetools-uikit/icons';
```
With the approach I'm proposing here, only one import is required:
```
import LeadingIcon, { type TLeadingIconProps } from '@commercetools-uikit/icons/leading-icon';
```
I'm also doing the same for the ` InlineSvg` component.

refactor(icons): update ts type exporting for custom icon components

---

.changeset/calm-emus-warn.md
packages/components/field-label/package.json
packages/components/field-label/src/field-label.tsx
yarn.lock

Show a different info-button in the `FieldLabel` component based on the theme.
**Changes:**
**Design requirements:**

`FieldLabel` style changes for the recolouring theme

---

.changeset/two-colts-build.md
design-system/materials/custom-properties.css
design-system/materials/custom-properties.json
design-system/materials/custom-properties_default.css
design-system/materials/custom-properties_recolouring.css
design-system/materials/internals/definition.yaml
design-system/src/design-tokens.ts
packages/components/buttons/icon-button/src/icon-button.styles.ts
packages/components/buttons/icon-button/src/icon-button.tsx

Icon button changes
When disabled:

Icon button changes

---

docs/package.json
docs/yarn.lock

Update `prismjs` transitive dependency version
We have [this security alert](https://github.com/commercetools/ui-kit/security/dependabot/48) about the `prismjs` dependency having a security issue.
This dependency is only used in Storybook.
Here is the dependency path:
```
@storybook/components@npm:5.3.21 [dba4e] -> react-syntax-highlighter@npm:11.0.3 [b2f13] -> refractor@npm:2.10.1 ->  prismjs@npm:1.17.1
```

Update prismjs transitive dependency version

---

docs/package.json
docs/yarn.lock

Update `node-fetch` transitive dependency version
We have [this security alert](https://github.com/commercetools/ui-kit/security/dependabot/44) about the `node-fetch` dependency having a security issue.
This dependency is only used in Storybook.
Here is the dependency path:
```
@storybook/core@npm:5.3.21 -> isomorphic-fetch@npm:2.2.1 -> node-fetch@npm:1.7.3 (via npm:^1.0.1)
```

Update `node-fetch` transitive dependency version

---

.changeset/great-carpets-share.md
package.json
yarn.lock

Update `trim` transitive dependency version.
We have [this security alert](https://github.com/commercetools/ui-kit/security/dependabot/14) about the `trim` dependency having a security issue.
Here is the dependency path:
```
@commercetools-local/generator-readme -> remark-parse@npm:8.0.3 ->  trim@npm:0.0.1 (via npm:0.0.1)
```

Update `trim` transitive dependency version

---

.changeset/smooth-baboons-beg.md
packages/components/tag/src/tag-body.tsx
packages/components/tag/src/tag.spec.js
packages/components/tag/src/tag.tsx

Figma references [here](https://www.figma.com/file/PaImaWorWz1RbV85gqw4MH/Filter-%26-Table-controls?type=design&node-id=1133%3A127328&mode=dev)
This PR contains the following updates (screenshots below):
1.) **border-radius** from `2px` to `20px`    --> all tags, in any state
2.) **typography** - `Text.Body` to `Text.Detail` -->   in `TagBody` component
3.) **border-color** to `warning85` --> when type is warning
4.)  **border-color** to `colorPrimary90` --> when type is default w/ hover (onClick)
5.) **background-color** to `neutral95` && **border-color** to `neutral` --> when type is default & isDisabled
Updates 09/04/24:
6.) **background-color** to `neutral95` && **border-color** to `neutral` --> when type is warning && isDisabled (this now matches the color schema of type=default && …

PANGOLIN- 3683 - <Tag/> styling updates

---

.changeset/fresh-suns-count.md
design-system/src/theme-provider.tsx

Fix `useTheme` hook helper.
The `themedValue` helper is now always returning the left-side provided parameter (meaning "old" value) where it should be always returning the right-side one ("new" value) as we already migrated to the new theme.

Fix `useTheme` hook helper

---

.changeset/kind-countries-yell.md
packages/components/dropdowns/dropdown-menu/src/menu/dropdown-menu-menu.tsx

There's been found an issue with the width and positioning of the `DropdownMenu` floating panel element.
closes #2813
The issue can be reproduced when using this properties values combination:
* `menuPosition`: right
* `menuHorizontalConstraint`: auto
In this situation, the floating menu was not correctly aligned with the triggering element and also was narrower that expected.
The issue seems to be related with the rendering and painting synchronization: although we use the `useLayoutEffect` hook to perform the calculation about the width and positioning of the floating element, the actual read width of the menu (determined by its contents because of the _auto_ value for the `menuHorizontalConstraint` property) was not accurate.
We were using this width measurement in order to calculate …

Fix `DropdownMenu` positioning issue 

---

.changeset/thin-nails-rush.md
packages/components/inputs/money-input/src/currencies.ts

I was wondering how I best prevent this or similar error(s) from happening again in the future, but did not manage to come up with a good change/solution I feel safe committing.
If someone has an idea, please share with me, otherwise this minimal solution will at least solve the problem in question.
fixes #2820

fix(money-input): missing BYN currency added

---

.changeset/warm-seahorses-bow.md
packages/components/inputs/search-text-input/src/search-text-input.styles.ts

I used the css `order` property to change the order of appearance on screen while keeping the logical tabbing order for keyboard-users.

refactor(search-text-input): swap icon and input order (visually)

---

.changeset/forty-tips-deny.md
packages/components/inputs/select-utils/src/create-select-styles.ts

We should preserve default wrap behaviour for multi selection.
See reference for an example: https://github.com/commercetools/merchant-center-frontend/pull/16911#issuecomment-2144777982
nowrap should be added only when select input is not multi to keep the left icon wrapping fix.

fix(create-select-styles): preserve default behavior for multi select

---

package.json
yarn.lock

Set `glob-parent` dependency minimum version
This is due to this security alert about that dependency having a [vulnerability](https://github.com/commercetools/ui-kit/security/dependabot/16).
This is a transitive dependency coming from the `@preconstruct/cli` which we already have in its latest version so that's why I added a new resolution to make sure it also uses the minimum version.
Building seems to work as well, so all good.

Set `glob-parent` dependency minimum version

---

docs/.storybook/manager-head.html

Somehow an excess `;` character was overseen by all of us and is (was) messing with the layout.

chore: get rid of excess ';' character

---

.changeset/cool-gorillas-bow.md
packages/components/text/src/text.tsx

Closes https://github.com/commercetools/ui-kit/issues/2867
Forwards `Text.Detail` `id` prop in all circumstances.
See full context in https://github.com/commercetools/ui-kit/issues/2867

fix(Text.Detail): forward `id` prop when `as` prop is not defined

---

packages/components/avatar/src/avatar.readme.mdx
packages/components/avatar/src/avatar.stories.tsx
packages/components/buttons/flat-button/src/flat-button.readme.mdx
packages/components/buttons/flat-button/src/flat-button.stories.tsx
packages/components/buttons/icon-button/src/icon-button.readme.mdx
packages/components/buttons/icon-button/src/icon-button.stories.tsx
packages/components/buttons/link-button/src/link-button.readme.mdx
packages/components/buttons/primary-button/src/primary-button.readme.mdx
packages/components/buttons/primary-button/src/primary-button.stories.tsx
packages/components/buttons/secondary-button/src/secondary-button.readme.mdx
packages/components/buttons/secondary-button/src/secondary-button.stories.tsx
packages/components/buttons/secondary-icon-button/src/secondary-icon-button.readme.mdx
packages/components/buttons/secondary-icon-button/src/secondary-icon-button.stories.tsx
packages/components/card/src/card.readme.mdx
packages/components/card/src/card.stories.tsx
packages/components/collapsible-motion/src/collapsible-motion.readme.mdx
packages/components/collapsible-motion/src/collapsible-motion.stories.tsx
packages/components/collapsible-panel/src/collapsible-panel.readme.mdx
packages/components/collapsible-panel/src/collapsible-panel.stories.tsx
packages/components/constraints/src/helpers.ts
packages/components/constraints/src/horizontal/horizontal.readme.mdx
packages/components/constraints/src/horizontal/horizontal.stories.tsx
packages/components/dropdowns/dropdown-menu/src/dropdown-menu.readme.mdx
packages/components/dropdowns/dropdown-menu/src/dropdown-menu.stories.tsx
storybook/.storybook/preview-head.html

Storybook v8 stories batch 1

---

packages/components/data-table-manager/src/data-table-manager.readme.mdx
packages/components/data-table-manager/src/data-table-manager.stories.tsx
packages/components/data-table/src/data-table.readme.mdx
packages/components/data-table/src/data-table.stories.tsx
packages/components/data-table/src/data-table.tsx
packages/components/data-table/src/header-cell.tsx

Storybook v8 stories batch 2

---

packages/components/field-errors/src/field-errors.readme.mdx
packages/components/field-errors/src/field-errors.stories.tsx
packages/components/field-label/src/field-label.readme.mdx
packages/components/field-label/src/field-label.stories.tsx
packages/components/field-warnings/src/field-warning.readme.mdx
packages/components/field-warnings/src/field-warning.stories.tsx
packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.readme.mdx
packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.stories.tsx
packages/components/fields/async-select-field/src/async-select-field.readme.mdx
packages/components/fields/async-select-field/src/async-select-field.stories.tsx
packages/components/fields/creatable-select-field/src/creatable-select-field.readme.mdx
packages/components/fields/creatable-select-field/src/creatable-select-field.stories.tsx
packages/components/fields/date-field/README.md
packages/components/fields/date-field/src/date-field.readme.mdx
packages/components/fields/date-field/src/date-field.stories.tsx
packages/components/fields/date-field/src/date-field.tsx
packages/components/fields/date-range-field/src/date-range-field.readme.mdx
packages/components/fields/date-range-field/src/date-range-field.stories.tsx
packages/components/fields/date-time-field/src/date-time-field.readme.mdx
packages/components/fields/date-time-field/src/date-time-field.stories.tsx
packages/components/fields/localized-multiline-text-field/src/localized-multiline-text-field.readme.mdx
packages/components/fields/localized-multiline-text-field/src/localized-multiline-text-field.stories.tsx
packages/components/fields/localized-text-field/src/localized-text-field.readme.mdx
packages/components/fields/localized-text-field/src/localized-text-field.stories.tsx
packages/components/fields/money-field/src/money-field.readme.mdx
packages/components/fields/money-field/src/money-field.stories.tsx

Storybook v8 stories batch 3

---

packages/components/inputs/checkbox-input/src/checkbox-input.readme.mdx
packages/components/inputs/checkbox-input/src/checkbox-input.stories.tsx
packages/components/inputs/creatable-select-input/src/creatable-select-input.readme.mdx
packages/components/inputs/creatable-select-input/src/creatable-select-input.stories.tsx
packages/components/inputs/date-input/src/date-input.readme.mdx
packages/components/inputs/date-input/src/date-input.stories.tsx
packages/components/inputs/date-range-input/src/date-range-input-proxy.tsx
packages/components/inputs/date-range-input/src/date-range-input.readme.mdx
packages/components/inputs/date-range-input/src/date-range-input.stories.tsx
packages/components/inputs/date-time-input/src/date-time-input-wrapper.tsx
packages/components/inputs/date-time-input/src/date-time-input.readme.mdx
packages/components/inputs/date-time-input/src/date-time-input.stories.tsx
packages/components/inputs/localized-money-input/src/localized-money-input.readme.mdx
packages/components/inputs/localized-money-input/src/localized-money-input.stories.tsx
packages/components/inputs/localized-multiline-text-input/README.md
packages/components/inputs/localized-multiline-text-input/docs/additional-info.md
packages/components/inputs/localized-multiline-text-input/src/localized-multiline-text-input.readme.mdx
packages/components/inputs/localized-multiline-text-input/src/localized-multiline-text-input.stories.tsx
packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.readme.mdx
packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.stories.tsx
packages/components/inputs/localized-text-input/src/localized-text-input.readme.mdx
packages/components/inputs/localized-text-input/src/localized-text-input.stories.tsx
packages/components/inputs/money-input/src/money-input.readme.mdx
packages/components/inputs/money-input/src/money-input.stories.tsx
packages/components/inputs/multiline-text-input/src/multiline-text-input.readme.mdx
packages/components/inputs/multiline-text-input/src/multiline-text-input.stories.tsx
packages/components/inputs/multiline-text-input/src/multiline-text-input.tsx
packages/components/inputs/number-input/src/number-input.readme.mdx
packages/components/inputs/number-input/src/number-input.stories.tsx

Storybook v8 stories batch 5

---

packages/components/inputs/password-input/src/password-input.readme.mdx
packages/components/inputs/password-input/src/password-input.stories.tsx
packages/components/inputs/radio-input/src/radio-group.tsx
packages/components/inputs/radio-input/src/radio-input.readme.mdx
packages/components/inputs/radio-input/src/radio-input.stories.tsx
packages/components/inputs/rich-text-input/src/rich-text-input.readme.mdx
packages/components/inputs/rich-text-input/src/rich-text-input.stories.tsx
packages/components/inputs/search-select-input/src/search-select-input.readme.mdx
packages/components/inputs/search-select-input/src/search-select-input.stories.tsx
packages/components/inputs/search-text-input/src/search-text-input.readme.mdx
packages/components/inputs/search-text-input/src/search-text-input.stories.tsx
packages/components/inputs/select-input/src/select-input.readme.mdx
packages/components/inputs/select-input/src/select-input.stories.tsx
packages/components/inputs/selectable-search-input/src/selectable-search-input.readme.mdx
packages/components/inputs/selectable-search-input/src/selectable-search-input.stories.tsx
packages/components/inputs/text-input/src/text-input.readme.mdx
packages/components/inputs/text-input/src/text-input.stories.tsx
packages/components/inputs/time-input/src/time-input.readme.mdx
packages/components/inputs/time-input/src/time-input.stories.tsx
packages/components/inputs/time-input/src/time-input.tsx
packages/components/inputs/toggle-input/src/toggle.readme.mdx
packages/components/inputs/toggle-input/src/toggle.stories.tsx
packages/components/label/src/label.readme.mdx
packages/components/label/src/label.stories.tsx
packages/components/link/src/link.readme.mdx
packages/components/link/src/link.stories.tsx
storybook/.storybook/preview.tsx

Storybook v8 stories batch 6

---

.changeset/selfish-bottles-sip.md
packages/components/text/README.md
packages/components/text/src/text.story.js
packages/components/text/src/text.styles.ts
packages/components/text/src/text.tsx
packages/components/text/src/text.visualroute.jsx

Add the tone prop to Text.Headline component. Just like the other derivatives of the Text components, we want to be able to change the Text color of the Text.Headline through the tone property.
Closes https://github.com/commercetools/ui-kit/issues/2886

Add tone property to Text.Headline Component

---

packages/components/dropdowns/dropdown-menu/src/dropdown-menu.readme.mdx
packages/components/filters/filter-menu/src/filter-menu.readme.mdx
packages/components/filters/filter-menu/src/filter-menu.stories.tsx
packages/components/filters/filters-list/src/filters-list.readme.mdx
packages/components/filters/filters-list/src/filters-list.stories.tsx
storybook/.storybook/manager.ts
storybook/README.md
storybook/package.json

feat(local only storybook): add ability to only display a story in the sidebar when running storybook locally by adding a 'local-dev' tag to the story meta
this is a POC - feedback welcome

FCT-1112 | display story only when running storybook locally

---

.github/workflows/preview-release.yml

We still have some issues to take care of in order to achieve the branch-specific canary version. The version name should at least have the format `0.0.0-branch-name-date`.

Improve preview version naming

---

package.json
yarn.lock

Manually update webpack dependency as some CI processes got stuck in ~~dependabots~~ renovatebots' update attempt.

chore(deps): bump webpack from 5.92.1 to 5.94.0

---

.changeset/eighty-lizards-sing.md
packages/components/data-table-manager/package.json

The libraries `debounce-promise` and `react-beautiful-dnd` are used normally and therefore the type declaration packages should be declared as normal dependencies as well.

fix(data-table-manager): include type declarations for libraries

---

packages/components/filters/README.md
packages/components/filters/package.json
packages/components/filters/src/badge/badge.spec.tsx
packages/components/filters/src/badge/badge.tsx
packages/components/filters/src/filter-menu/trigger-button/trigger-button.tsx
packages/components/filters/src/filters.stories.tsx
packages/components/filters/src/filters.tsx
yarn.lock

This PR implements the `Badge` component in the `filters` package.  
It implements the styles and states [specified in figma](https://www.figma.com/design/b2S3GGpScVDuf15VAGEqeL/Filter-pattern?node-id=2339-6256&m=dev), along with the proper accessibility attributes for the `status` role, [as specified here](https://w3c.github.io/aria/#status).
* [`packages/components/filters/src/badge/badge.tsx`](diffhunk://#diff-3a3cc1bc670245d29b7b51e03ec6378bdee6231c14135a350bea94098e7edaddL1-R53): Fully implemented the `Badge` component with properties for `id`, `isDisabled`, `label`, and `aria-label`. Added styles using `@emotion/react` and `designTokens` from `@commercetools-uikit/design-system`.
* [`packages/components/filters/src/badge/badge.spec.tsx`](diffhunk://#diff-d7ea2b19bec24e727a07922300c73 …

FCT-1072 - implement filters `Badge` component

---

packages/components/filters/src/filter-menu/chip/chip.spec.tsx
packages/components/filters/src/filter-menu/chip/chip.tsx
packages/components/filters/src/filter-menu/trigger-button/trigger-button.tsx
packages/components/filters/src/filters.stories.tsx
packages/components/filters/src/filters.tsx

This PR implements the `Chip` component with necessary styles and state as [specified in figma](https://www.figma.com/design/b2S3GGpScVDuf15VAGEqeL/Filter-pattern?node-id=2339-6256&m=dev).  
The `Chip` is implemented as an `li`, and should be used as a child of a `ul` component, as it is meant to list the selected filter values in a `FilterMenu`.
* **Chip Component**: Refactored to accept `label` and `isDisabled` props, and styled using `@commercetools-uikit/design-system` and `@emotion/react`.
* **FilterMenu Chip Test**: Updated the test for the `Chip` component to check for the `label` prop and role attribute.
**PLEASE NOTE: The Filters storybook must be updated to have a local-dev tag before merging this PR to main so that the Filters docs do not get published to the prod site, these …

FCT 1079 - filters `Chip`

---

storybook/package.json
yarn.lock

We found that using chromatic/storybook for visual/e2e testing would not give us enough of a benefit over percy to switch, so we dont need this dep.

chore(deps): remove `@chromatic-com/storybook` dep as it is unused

---

packages/components/filters/src/badge/badge.spec.tsx
packages/components/filters/src/badge/badge.tsx
packages/components/filters/src/filter-menu/chip/chip.spec.tsx
packages/components/filters/src/filters.spec.tsx
packages/components/filters/src/filters.spec.utils.tsx
packages/components/filters/src/filters.stories.tsx
packages/components/filters/src/filters.tsx
packages/components/filters/src/fixtures/constants.tsx

added a few more unit tests and continued to expand on Filter int tests.

FCT-1187 - Filter Selection tests

---

.changeset/grumpy-nails-smash.md
packages/components/inputs/select-utils/package.json
yarn.lock

Regression from #2975 
Causes the error
```
Couldn't find any versions for "@commercetools-uikit/checkbox-input" that matches "workspace:^"
```

fix: dependency version reference

---

.github/workflows/preview-release.yml

This pull request includes a change to the `.github/workflows/preview-release.yml` file to improve the handling of branch-specific tags during the publishing process.
Improvements to branch-specific tags:
* [`.github/workflows/preview-release.yml`](diffhunk://#diff-8b0f7fca9f96bdfd89cc7ae042ef4932a5104af70fceb2b9b497fba2d6406ba3L84-R84): Changed the `yarn changeset publish` command to use `${BRANCH_NAME}` instead of the static `preview` tag, allowing for more dynamic and branch-specific tagging.

chore(uikit preview release): use branch name as preview tag

---

.github/workflows/preview-release.yml

This PR Validates branch name in the preview release workflow
This PR adds a step to validate the branch name. This will prevent attempts to exploit any possible security vulnerability on the preview release workflow.

Validate preview branch name in preview release workflow

---

.changeset/neat-mails-sleep.md
packages/components/filters/src/export-types.ts
packages/components/filters/src/filters.tsx
packages/components/filters/src/index.ts
packages/components/quick-filters/src/index.ts
presets/buttons/src/index.ts
presets/fields/src/index.ts
presets/inputs/src/index.ts
presets/spacings/src/index.ts
presets/spacings/src/spacings.ts
presets/ui-kit/src/index.ts

This pull request includes several updates to the `@commercetools-uikit` packages to bundle types with UI Kit preset packages, Filters package, and QuickFilters package. The primary changes involve exporting additional types alongside the default exports in various components and presets.
* Added type exports to the `filters` package (`TFilterConfiguration`, `TFilterGroupConfiguration`, `TAppliedFilter`) in `export-types.ts` and `filters.tsx` files. [[1]](diffhunk://#diff-99a157b3db59f4b9bf29c700c2dec8fcf18d6a39a73f44fb31d5699e5ddab72cL1-R6) [[2]](diffhunk://#diff-2c89551fd766ebeb1c64333f7b36ae736640275f3c9b920670ee8f00d6e66899L42-R42) [[3]](diffhunk://#diff-2c89551fd766ebeb1c64333f7b36ae736640275f3c9b920670ee8f00d6e66899L109-R109)
* Updated `index.ts` files in `filters` and …

FCT 1305 - Bundle types with preset packages

---

.changeset/curly-mirrors-eat.md
presets/ui-kit/src/index.ts

This pull request includes changes to the `@commercetools-frontend/ui-kit` preset to add types for various components. The most important changes include adding type definitions for Filters, QuickFilters, Spacings, DataTable, and DataTableManager components.
Type definitions added:
* [`.changeset/curly-mirrors-eat.md`](diffhunk://#diff-f09120dfc81040d161f631db4b445dd8c6b39e093865d74927eb7605d8aa4b94R1-R5): Added a patch note indicating the addition of types for Filters, QuickFilters, Spacings, DataTable, and DataTableManager components to the UI Kit preset.
* `presets/ui-kit/src/index.ts`: 
* Added type definitions for `Filters` including `TFiltersProps`, `TFilterConfiguration`, `TFilterGroupConfiguration`, and `TAppliedFilter`.
* Added type definitions for `QuickFilters` including …

FCT 1305 - add types bundled in child packages in previous release to preset

---

packages/components/dropdowns/dropdown-menu/src/dropdown-menu.spec.tsx
packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.spec.js
packages/components/fields/async-select-field/src/async-select-field.spec.js
packages/components/fields/creatable-select-field/src/creatable-select-field.spec.js
packages/components/fields/date-field/src/date-field.spec.js
packages/components/fields/date-range-field/src/date-range-field.spec.js
packages/components/fields/date-time-field/src/date-time-field.spec.js
packages/components/fields/localized-multiline-text-field/src/localized-multiline-text-field.spec.js
packages/components/fields/money-field/src/money-field.spec.js
packages/components/fields/multiline-text-field/src/multiline-text-field.spec.js
packages/components/fields/search-select-field/src/search-select-field.spec.js
packages/components/fields/select-field/src/select-field.spec.js
packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.spec.js
packages/components/inputs/async-select-input/src/async-select-input.spec.js
packages/components/inputs/creatable-select-input/src/creatable-select-input.spec.js
packages/components/inputs/date-input/src/date-input.spec.js
packages/components/inputs/date-range-input/src/date-range-input.spec.js
packages/components/inputs/date-time-input/src/date-time-input.spec.js
packages/components/inputs/localized-money-input/src/localized-money-input.spec.js
packages/components/inputs/localized-multiline-text-input/src/localized-multiline-text-input.spec.js
packages/components/inputs/localized-text-input/src/localized-text-input.spec.js
packages/components/inputs/money-input/src/money-input.spec.js
packages/components/inputs/multiline-text-input/src/multiline-text-input.spec.js
packages/components/inputs/search-select-input/src/search-select-input.spec.js
packages/components/inputs/select-input/src/select-input.spec.js
packages/components/inputs/selectable-search-input/src/selectable-search-input.spec.tsx
packages/components/pagination/src/pagination.spec.js
test/test-utils.js
test/test-utils.tsx

Proposal for keeping events simulation in tests clean
This PR is just to demonstrate a proposal I would like to make regarding the changes required in our tests because of React 19 being stricter with some events simulation (`blur`, `focus`).
This is the reasoning for the stricter rules:
* React 18 introduced automatic batching and stricter rules around state updates. Testing tools must ensure that any React state updates are wrapped in act() to simulate real-world behavior properly.
* When you call focus() on an element, it might trigger event listeners or React updates (e.g., onFocus) that could internally cause state updates. React now expects such state updates to be wrapped in act() during tests.
So now we need to use `act()` for handling those events but we haven't used that …

Proposal for keeping events simulation in tests clean

---

.github/workflows/preview-release.yml
CONTRIBUTING.md

feat(preview releases): update release workflow to mirror that of other repositories, preview releases will now be triggered with a PR comment that includes [preview_deployment] on a PR of a branch whose name is prefixed with preview/
UI kit has a different preview release workflow than app-kit, change-history, and operations.  This PR updates the preview release workflow to be consistent across repositories.

Update preview release workflow to be consistent across repositories

---

.changeset/fifty-hairs-hear.md
design-system/src/theme-provider.tsx
generators/readme/test/generate-readme.spec.ts
packages/components/data-table-manager/src/column-settings-manager/column-settings-manager.tsx
packages/components/data-table/src/cell.tsx
packages/components/data-table/src/header-cell.tsx
packages/components/inputs/date-time-input/src/date-time-input.spec.js
packages/components/loading-spinner/src/loading-spinner.tsx
packages/components/pagination/src/page-size-selector/page-size-selector.tsx
packages/components/pagination/src/pagination.tsx

In preparation for upgrading ui kit to react 19, it [was necessary](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops) to remove all `defaultProps` in favor of passing a default param to the prop.
This PR updates the types of any prop that has a default param to be optional so that it is not mandatory to pass the prop in consuming applications.  This reduces the amount of refactoring that consumers will have to do to satisfy typechecking.

Update types for former defaultProps to be optional

---

.github/workflows/merge-blocking-labels.yml

This GitHub Action, once merged and configured as a branch protection, prevents merging PRs with these labels.
We want to synchronize the use of these labels and the GitHub Action across repos for the FE Chapter which as long-running PRs across repos which must not be merged.
I've made sure that all labels exist on the repo. I'll also setup branch protection after merging this.

feat(ci): add github action to block merging by labels

---

.changeset/curvy-colts-brake.md
packages/components/buttons/flat-button/src/flat-button.tsx
packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.tsx
packages/components/inputs/async-select-input/src/async-select-input.tsx
packages/components/inputs/creatable-select-input/src/creatable-select-input.tsx
packages/components/inputs/select-input/src/select-input.tsx
tsconfig.json
yarn.lock

When upgrading to Emotion `v11.14.0`, we get some type errors from the generated declaration files about imports `import("@emotion/react/types/jsx-namespace").EmotionJSX.Element`.
I reported the issue: https://github.com/emotion-js/emotion/issues/3310.
Then I tried looking at using different options of the `moduleResolution` option. It seems that the "better" choice would be to use the `bundler` option, which actually might be more appropriate anyway for a component library.
I went ahead and asked Gemini for some clarification:
```
Q: For a component library, is it recommended to use `moduleResolution: bundler`?
A: For a component library, `moduleResolution: bundler` is generally a good choice and often recommended, especially if you're targeting modern JavaScript environments and want to …
```

fix: compat with emotion `v11.14`

---

.changeset/beige-wolves-tickle.md
.changeset/curvy-colts-brake.md
.changeset/small-jars-pay.md
packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.tsx
packages/components/inputs/async-select-input/src/async-select-input.tsx
packages/components/inputs/creatable-select-input/src/creatable-select-input.tsx
packages/components/inputs/select-input/src/select-input.tsx

Reduces the amount of typecasting and code in the `react-select` based components to what is necessary when using the `moduleResolution: bundler` TypeScript configuration setting.

Only update react-select child component types where necessary when using `moduleResolution: bundler` tsconfig setting

---

presets/ui-kit/package.json
presets/ui-kit/src/index.ts
yarn.lock

With the following diagram of dependencies
```mermaid
graph TD;
B("package-b")-->C("@commercetools-frontend/uikit");
A("app-a")-->C;
A-->B;
B-->react;
A--> react;
C-->react;
```
and as a maintainer of `package-b`, I want define all `ui-kit` related code used in `package-b` as a single `peerDependency` through `@commercetools-frontend/uikit` . The goal is to provide seamless upgrades of react.
My current issue is `DataTableManagerProvider`, `utils` and `selectUtils` are not exported through `@commercetools-frontend/uikit`. So, this PR tries to export these three to upgrade the react version (and provide backward compatibility) of `package-b`.

refactor(preset): export `DataTableManagerProvider`, `utils` and `selectUtils`

---

.changeset/pretty-walls-repeat.md
packages/components/inputs/money-input/src/money-input.tsx

- Added auto menu placement to money input to match select input
Without auto menu placement, the money select input is causing extra/infinite scrolling in various scenarios within Merchant Center. This change will resolve the issue with custom fields being unable to select a currency value within the stores modal.

fix(money-input): auto menu placement

---

.changeset/twenty-dots-kiss.md
packages/components/fields/select-field/src/select-field.tsx
packages/components/inputs/select-input/src/select-input.tsx

`TSelectInputProps` and `TSelectFieldProps` are using `unknown` as the option type for `ReactSelectProps` (the default value).
This PR switches to `ReactSelectProps<TOption>` to properly check the provided props downstream and avoid issues with TS errors.

fix(SelectInput): improve TSelectInputProps and TSelectFieldProps types

---

.changeset/afraid-mangos-count.md
packages/components/pagination/src/page-size-selector/page-size-selector.tsx
packages/components/pagination/src/pagination.spec.js
packages/components/pagination/src/pagination.stories.tsx
packages/components/pagination/src/pagination.tsx

This pull request enhances the `PageSizeSelector` component by introducing a new `xs` page range size option and updating related functionality and documentation. Additionally, it improves the `onPerPageChange` handler in the pagination story for better debugging.
* Added a new `xs` page range size to `TPageRangeSize`, with options `[5, 10, 15, 20]`, and updated its usage in `mapRangeToListOfOptions` and the error message for invalid ranges in `page-size-selector.tsx`. [[1]](diffhunk://#diff-7854cf71084bba076bcbad561f56760ab578b5e00844262b8bd7598e644534ccL10-R10) [[2]](diffhunk://#diff-7854cf71084bba076bcbad561f56760ab578b5e00844262b8bd7598e644534ccR44-R45) [[3]](diffhunk://#diff-7854cf71084bba076bcbad561f56760ab578b5e00844262b8bd7598e644534ccL50-R54)
* Updated the JSDoc comments for …

feat(pagination): add 'xs' range option for page size selector

---

.changeset/tangy-parents-sniff.md
packages/components/inputs/money-input/src/money-input.spec.js
packages/components/inputs/money-input/src/money-input.tsx
packages/utils/src/is-numberish.ts

This pull request enhances the `MoneyInput` component to handle additional locale-specific decimal separators, particularly for Swiss formatting, and improves the robustness of number parsing. The most important changes include updates to test cases, parsing logic, and validation to support right quotes and single quotes as decimal separators.
* [`packages/components/inputs/money-input/src/money-input.spec.js`](diffhunk://#diff-efc1fc60bf9753e7d636eddfcebe5f26c48050302a40097cdb7ece55b781e755R331-R359): Added test cases to verify that `MoneyInput.parseMoneyValue` correctly handles right quotes (0x2019) and single quotes as fraction separators for the `de-CH` locale.
* [`packages/components/inputs/money-input/src/money-input.tsx`](diffhunk://#diff-a0ac7e993a4e0160e1097806ed7499810cd4e6d55e89 …

SUPPORT-32352 fix(money input): add support for apostrophe as a fraction separator for money value input when locale is de-CH

---

package.json
yarn.lock

Following the recommendations from [here](https://github.com/commercetools/ui-kit/security/dependabot/180), I added a new entry to the resolutions object in the package.json.
---
Percy had issues with the v8 version of the package, so i limited the resolutions to the vulnerable version.

chore(deps): add path-to-regexp dependency and update yarn.lock

---

.changeset/thin-taxis-film.md
packages/components/filters/README.md
packages/components/filters/src/filter-menu/filter-menu.tsx
packages/components/filters/src/filters.stories.tsx
packages/components/filters/src/filters.tsx

This pull request introduces a new feature to control the width of filter menus dynamically and updates related components to accommodate this functionality. The changes primarily involve adding a new `allowAutoMenuWidth` property and modifying the `menuStyles` function to respect this property.
* `packages/components/filters/src/filter-menu/filter-menu.tsx`:
- Added a new `allowAutoMenuWidth` property to the `TFilterMenuProps` type, allowing the menu width to adjust automatically.
- Updated the `menuStyles` function to conditionally set the menu width to `auto` if `allowAutoMenuWidth` is true.
- Modified the `FilterMenu` component to pass the `props` object to the `menuStyles` function for dynamic styling.
* `packages/components/filters/src/filters.tsx`:
- Added the `allowAutoMenuWidth` …

feat(filters): allow auto menu width for filter menu

---

.github/renovate.json
.github/workflows/main.yml

_**NOTE: We'll also need to update the Repo>Branch settings to make Percy checks not required; Percy will still run for all PRs created by a human developer(or anything that isn't Renovate).**_
This pull request introduces improvements to the automation of dependency updates and the workflow for visual regression testing. The main focus is on making Renovate PRs more descriptive and enabling the ability to skip visual regression tests for specific PRs.
**Renovate automation enhancements:**
* Updated `.github/renovate.json` to set a custom PR title format for Renovate dependency updates, including `[skip percy]` in the title to indicate when visual regression tests should be skipped.
**Visual regression workflow improvements:**
* Modified `.github/workflows/main.yml` so that visual …

fix(deps): skip percy for renovate prs [skip percy]
