commercetools/ui-kit

.travis.yml
my bad, guys
merge upon approval.
=> chore(travis): nodejs 8 -> 10

.travis.yml
=> chore: limit jest max-workers

src/index.js
Let's export spacings and constraints so we can include them in our bundle ⭐️
=> chore: export spacings and constraints

package.json, rollup.config.js, yarn.lock
I believe it doesn't make sense to minify the CJS bundle as the consumer would minify the whole application anyways.
Feel free to teach me otherwise if you are more familiar with this!
=> Remove minifcation of cjs bundle

netlify.toml
https://www.netlify.com/blog/2016/11/01/yarn-support-on-netlify/
https://www.netlify.com/docs/netlify-toml-reference/#deploy-context
=> chore(netlify): assign yarn env vars

.travis.yml, package.json, yarn.lock
Let's make jest silent like we have it on mc.
I think this is all we need? Let me know if it's missing something.
Closes [49](https://github.com/commercetools/ui-kit/issues/49)
=> chore: CI silent jest reporting

.travis.yml, README.md
See https://twitter.com/emmenko/status/1040544486101856256
=> chore: disable docs publish script

CHANGELOG.md, package.json
Let's make Quique happy and give him his German translations for Channels.
=> chore: bump version to 2.0.0-rc5, update changelog

src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.mod.css, src/components/inputs/localized-text-input/localized-text-input.mod.css, src/components/inputs/money-input/money-input.mod.css, src/components/inputs/number-input/number-input.mod.css, src/components/inputs/password-input/password-input.mod.css, src/components/inputs/text-input/text-input.mod.css
To close [17](https://github.com/commercetools/ui-kit/issues/17), I applied the changes that were leftover from the earlier closed PR.
=> fix: use correct token for selected input background

src/components/inputs/number-input/number-input.spec.js, src/components/inputs/password-input/password-input.spec.js
Converts more tests to `react-testing-library`.
=> convert more tests

CONTRIBUTING.md, README.md
Mainly fixes the link to Travis, but also rewords some things.
=> docs: fix travis link

src/index.js
Adds `WarningMessage` to the exported components.
=> feat: export WarningMessage

README.md
Documents our translations workflow.
=> docs: add translation flow to README

examples/form-fields.story.js, src/components/fields/multiline-text-field/README.md, src/components/fields/multiline-text-field/index.js, src/components/fields/multiline-text-field/multiline-text-field.form.story.js, src/components/fields/multiline-text-field/multiline-text-field.js, src/components/fields/multiline-text-field/multiline-text-field.spec.js, src/components/fields/multiline-text-field/multiline-text-field.story.js, src/index.js
Adds the `MultilineTextField` component.
=> Add MultilineTextField

src/utils/filter-aria-attributes.js, src/utils/filter-aria-attributes.spec.js
This is already contained in the buttons branch. 
As we are covering accessibility in most of our components now, maybe its a good idea to get this merged before the branch `feature/new-buttons` gets merged in master
=> adds `filterAriaAttributes` util

CHANGELOG.md, package.json
Let's do a release, since it's been 14 days.
Don't mind also waiting until more PRs are resolved.
=> chore: bump version to 2.0.0-rc.7, update changelog

src/components/fields/money-field/money-field.js
=> fix: avoid circular dependency

src/components/fields/async-select-field/README.md, src/components/fields/async-select-field/async-select-field.form.story.js, src/components/fields/async-select-field/async-select-field.js, src/components/fields/async-select-field/async-select-field.spec.js, src/components/fields/async-select-field/async-select-field.story.js, src/components/fields/async-select-field/index.js, src/components/inputs/async-select-input/README.md, src/index.js
=> Add AsyncSelectField

src/components/fields/creatable-select-field/creatable-select-field.story.js
Uses the correct name for the story and the component in the story.
=> fix: rename CreatableSelectField story

CHANGELOG.md, package.json
Now that the Icons are fixed,
I'd like to release a new version so I can finish the UI-Kit update on the MC.
=> chore: update version, update changelog

CHANGELOG.md, package.json
Mainly to fix the broken checkboxes.
=> Release v2.0.0-rc.9

CHANGELOG.md, package.json
=> Release version 2.0.0-rc.10

CHANGELOG.md, package.json
Want to bump version so that I can fix some line break issues in the MC.
=> chore: bump version to 2.0.0-rc.11, update changelog

src/components/fields/money-field/money-field.form.story.js
In https://github.com/commercetools/ui-kit/pull/175#issuecomment-430995949 it occurred to me that we've so far only shown how to validate required `MoneyField`s.
This adds an example of how to validate an optional `MoneyField`. Notice that we do not error when this field is filled out partially, as it is not required. Supplying either only currency or only an amount will be treated as leaving the field blank. UX could want to show an error in this case, but then we'd also need a way to unset the currency, which is not possible now.
cc @filippobocik
=> Add optional MoneyField example

src/components/inputs/money-input/money-input.js, src/components/internals/create-select-styles.js
Imports css-vars properly and fixes `firstChild` exclusion.
=> fix: import vars correctly

README.md
Just some updates to the README.md to make it easier for consumers to get up and running with css variables.
=> chore: fixup docs

materials/media-queries.mod.css
Wrong media query format lead to incorrect media queries when built with webpack.
https://github.com/postcss/postcss-custom-media
=> fix: media queries

CHANGELOG.md, package.json
So that the Avatar is accessible.
=> chore: update changelog and bump version to `4.0.2`

src/components/inputs/time-input/time-input-body.js, src/components/internals/calendar-body/calendar-body.js, src/components/internals/calendar-calendar/calendar-calendar.js, src/components/internals/calendar-day/calendar-day.js, src/components/internals/calendar-header/calendar-header.js, src/components/internals/calendar-menu/calendar-menu.js
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1765075/49595440-41cac680-f978-11e8-948c-5d8c641a8f54.png) | ![image](https://user-images.githubusercontent.com/1765075/49595421-37a8c800-f978-11e8-924e-1da0b7567b5c.png) |
| ![image](https://user-images.githubusercontent.com/1765075/49595732-ed741680-f978-11e8-9efe-4c8cf90a5e3e.png) | ![image](https://user-images.githubusercontent.com/1765075/49595711-e1885480-f978-11e8-92fc-eca501095407.png) |
| ![image](https://user-images.githubusercontent.com/1765075/49595771-05e43100-f979-11e8-9447-9ff2ec2d5136.png) | ![image](https://user-images.githubusercontent.com/1765075/49595909-6a06f500-f979-11e8-98a3-78c6d6195304.png) |
Fixes `DateInput`, `DateTimeInput` and `TimeInput`.
=> Fix date input styling

.github/PULL_REQUEST_TEMPLATE/add-new-component.md
=> docs: enhance component checklist

i18n/core.json, i18n/de.json, i18n/en.json, i18n/es.json, src/components/inputs/date-range-input/README.md, src/components/inputs/date-range-input/date-range-input.form.story.js, src/components/inputs/date-range-input/date-range-input.js, src/components/inputs/date-range-input/date-range-input.spec.js, src/components/inputs/date-range-input/date-range-input.story.js, src/components/inputs/date-range-input/index.js, src/components/inputs/date-range-input/messages.js, src/index.js
Adds `DateRangeInput`
~I'm not sure whether we actually need this component at the moment. I initially built it because the old `DateInput`s were supporting ranges. But it seems like we were not using those ranges after checking again. We might want to use this component for e.g. the Dashboard though.~
*We decided to go with this component as it might eventually get used in the dashboard and other places.*
=> Add DateRangeInput component

src/components/fields/async-creatable-select-field/async-creatable-select-field.js, src/components/fields/async-select-field/async-select-field.js, src/components/fields/creatable-select-field/creatable-select-field.js, src/components/fields/localized-multiline-text-field/localized-multiline-text-field.js, src/components/fields/localized-text-field/localized-text-field.js, src/components/fields/money-field/money-field.js, src/components/fields/multiline-text-field/multiline-text-field.js, src/components/fields/number-field/number-field.js, src/components/fields/select-field/select-field.js
Fixes names of auto-generated ids.
=> fix: use prefix based on component for auto-generated ids

src/components/inputs/select-input/select-input.spec.js
Move select-input tests to use RTL.
=> chore: refactor select-input tests to use rtl

src/components/inputs/creatable-select-input/creatable-select-input.spec.js
=> chore: refactor creatable-select-input tests

CHANGELOG.md
this changes the changelog by adding changes to the changelog
=> chore: update changelog [skip-ci]

src/components/fields/number-field/number-field.spec.js, src/components/fields/text-field/text-field.spec.js
Converting tests from `enzyme` to `react-testing-library`
=> TextField: using react testing library

src/components/inputs/money-input/money-input.spec.js
An ESLint warning we can easily get rid off by just using the suggested name.
=> chore: to use toHaveBeenCalledTimes

src/components/fields/date-field/date-field.js, src/components/fields/date-field/date-field.spec.js, src/components/fields/date-range-field/date-range-field.spec.js, src/components/fields/date-time-field/date-time-field.spec.js
Converts `DateField`, `DateTimeField` and `DateRangeField`.
=> Convert date-fields

materials/internals/TOKENS.md, materials/internals/tokens.story.js
Adds an in-depth README to our tokens story.
=> Add tokens README

scripts/run-percy.sh, src/components/table/table.visualroute.js, src/components/table/table.visualspec.js, visual-testing-app/index.html, visual-testing-app/server.js, visual-testing-app/webpack.config.js
* Add a VRT test for the basic table example
* Improves the VRT app setup a bit by splitting node_modules and ui-kit.
* ~~Use webpack production mode for VRT app build~~
=> chore: improve vrt app and add table vrt test

.storybook/preview-head.html, playground/index.template.html, playground/src/index.js, playground/webpack.config.js, visual-testing-app/index.html
Adds Google font import to Storybook, Playground and the visual testing app.
All of the percy tests are failing because now we are rendering our components with the correct font 😆
=> feat: Add Google Font to `playground`, `visual-testing-app` and `storybook`.

philosophy/FIELDS.md, philosophy/INPUTS.md, philosophy/guide.story.js
Check out #385 first. This PR builds on top of that.
Adds more information about our inputs and fields.
=> Add inputs and fields philosophy

src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.story.js
=> docs(storybook): fix PrimaryActionDropdown story

i18n/core.json, i18n/de.json, i18n/en.json, i18n/es.json, src/components/inputs/date-input/date-input.js, src/components/inputs/time-input/messages.js, src/components/inputs/time-input/time-input.js
As requested by design, adds default placeholder to TimeInput if no placeholder is passed, similar to DateInput. Also fixes some proptype warnings.
=> feat(time-input): add default placeholder

CHANGELOG.md
Based on this diff: https://github.com/commercetools/ui-kit/compare/v5.0.0...master
=> docs(changelog): for release v6.0.0

.storybook/config.js, .storybook/welcome.story.js
Closes #407 
Inspiration from: https://egghead.io/lessons/react-add-a-welcome-page-with-sequential-stories-to-a-react-storybook
=> chore(storybook): render ui-kit readme as getting started page

CHANGELOG.md, package.json
This helps with updating MC-FE to ui-kit 6.
=> chore: bump package.json and update changelog

src/components/inputs/async-creatable-select-input/async-creatable-select-input-open.visualroute.js, src/components/inputs/async-creatable-select-input/async-creatable-select-input.visualspec.js, src/components/inputs/async-select-input/async-select-input-open.visualroute.js, src/components/inputs/async-select-input/async-select-input.visualspec.js, src/components/inputs/creatable-select-input/creatable-select-input-open.visualroute.js, src/components/inputs/creatable-select-input/creatable-select-input.visualspec.js, src/components/inputs/select-input/select-input-open.visualroute.js, src/components/inputs/select-input/select-input.visualspec.js
Continuing towards #400
Note that we already tested these components indirectly through the fields VRTs before. Now they have their own dedicated tests.
=> Add VRTs to SelectInputs

CHANGELOG.md, package.json
Updates changelog and package.json
=> chore: update changelog for version 7.0.0 

materials/custom-properties.js, scripts/generate-custom-properties.js, src/components/avatar/avatar.js, src/components/spacings/inline/inline.styles.js, src/components/spacings/inset-squish/inset-squish.js, src/components/spacings/inset/inset.js, src/components/spacings/stack/stack.styles.js, src/components/stamp/stamp.js, src/components/typography/text/text.styles.js
https://github.com/commercetools/ui-kit/pull/460#issuecomment-456734477
=> refactor: to use default export

README.md, materials/internals/definition.yaml, package.json, src/components/grid/grid.example.story.js, src/components/inputs/money-input/money-input.js, src/components/internals/create-select-styles.js, src/index.js, test/percy/spec.js
=> refactor: to import custom props as js object

src/components/tag/tag.js, src/components/typography/text/text.js
Fixes design of `Tag` component
=> chore: fix tag

materials/internals/tokens.story.js
Use correct `font family` and `color` for the tokens story.
=> Normalize `Tokens` Story

lint-staged.config.js, package.json
Doesn't really make sense to lint or format css anymore.
=> chore: remove lint/format css

CHANGELOG.md, package.json
PS: we also want to include #482 in the release
=> docs(changelog): for release v8.0.0 [skip ci]

materials/custom-properties.js, src/components/card/README.md, src/components/card/card.js, src/components/card/card.spec.js, src/components/card/card.story.js, src/components/card/card.visualroute.js, src/components/card/card.visualspec.js, src/components/card/index.js, src/index.js
Adds `Card` component from core.
=> Adds `Card` Component

src/components/fields/async-creatable-select-field/async-creatable-select-field.js, src/components/fields/async-select-field/async-select-field.js, src/components/fields/creatable-select-field/creatable-select-field.js, src/components/fields/date-field/date-field.js, src/components/fields/date-range-field/date-range-field.js, src/components/fields/date-time-field/date-time-field.js, src/components/fields/localized-multiline-text-field/localized-multiline-text-field.js, src/components/fields/localized-text-field/localized-text-field.js, src/components/fields/money-field/money-field.js, src/components/fields/multiline-text-field/multiline-text-field.js, src/components/fields/number-field/number-field.js, src/components/fields/password-field/password-field.js, src/components/fields/select-field/select-field.js, src/components/fields/text-field/text-field.js, src/components/fields/time-field/time-field.js, src/components/inputs/checkbox-input/checkbox-input.js, src/components/inputs/localized-money-input/localized-money-input.js, src/components/inputs/localized-text-input/localized-text-input.js, src/components/inputs/time-input/time-input.js, src/utils/get-field-id.js
Caused by #453
My bad, the `createSequentialId` is a factory function that has some state, so it can't be called inline 🤦‍♀️
=> fix: sequential field id generation

src/components/tag/tag.js, src/components/tag/tag.story.js
Fix <Tag /> component appearance.
=> fix(tag): wrong css is applied in case linkTo prop is provided

package.json, test/transform-babel-jest.js, yarn.lock
Thanks @tdeekens for bringing this up
=> chore: readds babel preset jest

src/components/card/card.js, src/components/card/card.spec.js
Card should support data attributes 😄
=> feat(card): support data attributes

CHANGELOG.md, package.json
Want to release new version to get @pa3 's bug fix out there.
=> chore: update changelog and bump package.json

src/components/icons/index.js, src/components/icons/svg/speech-bubble.react.svg
New icon for the welcome page
Adding Speech Bubble icon
=> Speech Bubble Icon: adding new icon for welcome page

scripts/get-babel-preset.js
Follow up to #519 
We need this as well for our css prop usage.
=> chore: also apply to css preset emotion

src/components/tooltip/tooltip.story.js
Just a leftover from Tooltip PR
=> chore: fix tooltip story

CHANGELOG.md, package.json
Updates changelog and package.json for imminent release
=> Update changelog for version `8.3.0`

CHANGELOG.md, package.json
Releasing new version to have the new `Tooltip` functionality in discounts.
=> chore: bump package.json and update changelog for version 8.4.0

materials/custom-properties.css, materials/custom-properties.js, materials/custom-properties.json, materials/internals/definition.yaml
As requested by the design team.
=> refactor: constraint L to be 496px

src/components/card/card.js
=> fix(card): do not apply padding to outer flex container

src/components/buttons/flat-button/flat-button.js, src/components/buttons/link-button/link-button.js, src/components/inputs/checkbox-input/checkbox-input.js, src/components/inputs/radio-input/radio-option.js, src/components/internals/calendar-header/calendar-header.js, src/components/spacings/inline/inline.styles.js, src/components/spacings/stack/stack.styles.js
=> fix(spacings): specificity of margin for children elements

CHANGELOG.md, package.json
Updates changelog for version `9.0.0` 🎉
=> chore: update changelog for v9.0.0

src/components/inputs/styles.js
During the refactoring to use emotion, this was lost. Now it's added back.
=> feat: use design tokens for input styling

CHANGELOG.md, package.json
Changelog for version `9.1.0`.
=> chore:  update changelog

package.json, src/components/inputs/localized-money-input/localized-money-input.js, src/utils/localized.js, yarn.lock
Remove a dep we can easily live without.
=> chore: remove lodash without

package.json, src/components/internals/calendar-day/calendar-day.js, src/components/internals/calendar-menu/calendar-menu.js, src/components/table/table.js, yarn.lock
=> chore: remove lodash.omit

src/components/inputs/money-input/money-input.js, src/components/inputs/money-input/money-input.styles.js
Most of our inputs already use design tokens, so it's not much effort to use them in the `MoneyInput` as well 👍
=> chore: use design tokens in money-input

src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.visualroute.js, src/components/inputs/localized-multiline-text-input/translation-input.js, src/components/inputs/localized-multiline-text-input/translation-input.styles.js
Use design tokens, and support theming for `LocalizedMultilineTextArea`
=> feat(localized-multiline-text-input): support theming / use design tokens

src/components/inputs/multiline-text-input/multiline-text-input.js, src/components/inputs/multiline-text-input/multiline-text-input.styles.js, src/components/inputs/multiline-text-input/multiline-text-input.visualroute.js
As part of making all of our inputs support custom theming, we come to the `MultilineTextInput`.
=> feat(multiline-text-input): support custom theming

src/components/inputs/number-input/number-input.js, src/components/inputs/number-input/number-input.visualroute.js
Support custom theming for `NumberInput`.
=> feat(number-input): support custom theming

.eslintrc.yaml, src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.visualroute.js, src/components/inputs/localized-text-input/localized-text-input.visualroute.js, src/components/inputs/multiline-text-input/multiline-text-input.visualroute.js, src/components/inputs/number-input/number-input.visualroute.js, src/components/label/label.visualroute.js, src/components/typography/text/text.visualroute.js, test/percy/spec.js, visual-testing-app/src/App.js
As suggested here: https://github.com/commercetools/ui-kit/pull/635#discussion_r272116681
=> refactor(vrt): define dark theme once and pass it as prop to tests

src/components/tag/tag.js, src/components/tag/tag.story.js
While working on implementing design tokens in the `Tag` component, I noticed some style *weirdness*. 
Design has provided the following image
I have made the changes to make the Tag follow these styles.
=> fix: css fixes for tag

src/components/typography/text/README.md, src/components/typography/text/text.js, src/components/typography/text/text.spec.js, src/components/typography/text/text.visualroute.js
=> feat(text): allow to pass intl message instead of children

CHANGELOG.md, package.json
=> chore: prepare changelog for 9.2.0

package.json, src/components/field-label/field-label.js, src/components/field-label/field-label.visualroute.js
Check the Percy diff for the fix.
Closes #660
=> fix: hint icon in field-label

src/components/label/label.visualroute.js, src/components/typography/text/text.js, src/components/typography/text/text.styles.js, src/components/typography/text/text.visualroute.js
Makes Text components themeable.
=> feat: allow theming for text

.storybook/decorators/intl/intl.js
Currently we can't select chinese or french on storybook. This fixes that.
=> fix(storybook): fix for choosing french and chinese locales

CHANGELOG.md, package.json
=> chore: update changelog for version `9.3.0`

.circleci/config.yml
This pull request aims to experiment a bit more with the release process.
=> fix: releasing from master and release/*

i18n/data/zh-CN.json
Got this new translation from the agency.
=> chore: chinese translations update

CHANGELOG.md, package.json
=> chore: changelog for `9.3.1`

CHANGELOG.md, package.json
I don't remember how the release works now 🙈 so I guess I'll have to see.
=> chore: update changelog for 9.4.0

src/components/spacings/inline/inline.story.js
This pull request improves the Spacings story to add a document but not added prop to the story.
=> chore(spacings/inline): add justify content select

src/components/inputs/checkbox-input/checkbox-input.js, src/components/inputs/checkbox-input/checkbox.js, src/components/inputs/money-input/money-input.js, src/components/inputs/radio-input/radio-option.js, src/components/inputs/radio-input/radio-option.styles.js, src/components/inputs/time-input/time-input-body.styles.js, src/components/internals/calendar-body/calendar-body.styles.js, src/components/internals/calendar-menu/calendar-menu.js
Use non deprecated tokens in our component styles in anticipation of ✂️ these.
=> refactor: use non deprecated tokens

src/components/inputs/radio-input/radio-option.js, src/components/inputs/radio-input/radio-option.styles.js, src/components/internals/calendar-body/calendar-body.styles.js, src/components/internals/calendar-day/calendar-day.js, src/components/label/required-indicator.js
Replace deprecated tokens with non deprecated custom props.
=> refactor: change custom props

src/components/internals/calendar-body/calendar-body.styles.js, src/components/internals/calendar-menu/calendar-menu.js
=> chore: use non deprecated prop

src/components/tag/tag.js
=> chore: use non deprecated token

src/components/card/card.js, src/components/panels/collapsible-panel/collapsible-panel.styles.js
Change to using shadow1 instead of shadow1Second.
Percy finds no VRT diff so it should be fine to merge.
=> refactor: shadow change

CHANGELOG.md, package.json
Updates changelog for release of version 9.5.0
=> chore: update changelog for version `9.5.0`

materials/custom-properties.css, materials/custom-properties.js, materials/custom-properties.json, materials/internals/definition.yaml, src/components/inputs/localized-multiline-text-input/translation-input.styles.js, src/components/inputs/localized-text-input/localized-text-input.styles.js, src/components/inputs/styles.js, src/components/inputs/time-input/time-input-body.styles.js, src/components/internals/calendar-body/calendar-body.styles.js, src/components/internals/create-select-styles.js, src/components/table/base-table/base-table.js
=> refactor: transition-standard to not use `all` as transition property

CHANGELOG.md, package.json
Updates CL for new version. Maybe our last before 10.0.0?
=> chore: update changelog for version `9.6.0`

CHANGELOG.md, package.json
Want to release new version to get this tooltip fix in.
=> chore: update changelog for new version 9.6.1

src/components/buttons/secondary-icon-button/secondary-icon-button.js, src/components/buttons/secondary-icon-button/secondary-icon-button.visualroute.js
* Remove withMouseOverState from `SecondaryIconButton`
* Add theming
=> feat(secondary-icon-button): refactor hover and add theming

src/components/inputs/time-input/time-input-body.styles.js
Fixes border radius problem.
* Closes #772
=> fix(time-input): border radius bug

src/components/inputs/time-input/time-input-body.js, src/components/inputs/time-input/time-input-body.styles.js, src/components/inputs/time-input/time-input.js
Changes the look of the hover / focus for the `TimeInput`
Please check the deploy link
=> refactoring(time-input):`TimeInput` improvements

src/components/buttons/icon-button/icon-button.js, src/components/buttons/icon-button/icon-button.styles.js
Adds border to disabled `IconButton` as requested by design
=> fix(icon-button): add border color

CHANGELOG.md, package.json
Updates changelog for release `9.7.0`
=> chore: update changelog for `9.7.0`

CHANGELOG.md, package.json
Update changelog for release 9.8.0
=> chore: update changelog for release 9.8.0

src/components/inputs/toggle-input/README.md, src/components/inputs/toggle-input/toggle-input.js, src/components/inputs/toggle-input/toggle-input.spec.js, src/components/inputs/toggle-input/toggle.story.js, src/components/inputs/toggle-input/toggle.visualroute.js
Following #771, this PR is a continuation to tackle #706, this time for the ToggleInput component.
=> refactor: Toggle inputs to spread attributes and improve a11y

i18n/data/core.json, i18n/data/de.json, i18n/data/en.json, i18n/data/es.json, i18n/data/fr-FR.json, i18n/data/zh-CN.json, scripts/extract-intl.js
Our build intl script was missing french and chinese.
=> fix(i18n): build all locales

CHANGELOG.md, package.json
Update changelog for new release `9.8.1`
=> chore: update changelog

.circleci/config.yml, lint-staged.config.js, src/components/buttons/flat-button/flat-button.js, src/components/buttons/icon-button/icon-button.styles.js, src/components/grid/grid.js, src/components/inputs/checkbox-input/checkbox-input.js, src/components/inputs/time-input/time-input-body.styles.js, src/components/inputs/toggle-input/toggle-input.js, src/components/internals/calendar-menu/calendar-menu.js, src/components/table/base-table/base-table.js, src/components/tag/tag.js
Fixes the CSS lint errors, and updates the CI config to run the linters.
=> chore: fix lint errors, add linting to ci

src/components/inputs/radio-input/radio-group.js, src/components/inputs/radio-input/radio-option.js
=> fix(radio-input): do not use htmlFor if no id is passed

.size-snapshot.json, src/components/buttons/icon-button/icon-button.js
=> fix(icon-button): centre icon

CHANGELOG.md, package.json
Updates changelog for next release.
=> chore: update changelog and package.json for 9.8.2

src/components/inputs/toggle-input/toggle-input.js
In #830 , I updated changelog for the new release. But I never pushed tags and created the release.
This reverts #832 so that I can release that forgotten version.
=> Revert "fix(toggle-input): toggle input disabled styles (#832)"

.storybook/config.js
It's too hot to think so look at the branch name.
=> chore: update brand image

CHANGELOG.md, package.json
Let's get that Toggle fix in 😄
=> chore: update changelog for 9.8.3

.size-snapshot.json, rollup.config.js, src/index.bundlespec.js, src/index.js, src/version.js
Like similar PRs in App Kit, we also add a version export 😄
=> feat: add version export

CHANGELOG.md, package.json
Let's get this release in and hope it fixes the emotion warning issue in the MC.
=> chore: update cl for release 9.9.0

src/components/inputs/select-input/select-input.spec.js, src/components/internals/create-select-styles.js, src/components/internals/tag-remove/tag-remove.js
Fix for disabled multi selects
Fixes #854
=> fix(select-inputs): multi select disabled bug

src/components/constraints/horizontal/README.md
=> chore: update readme for horizontal constraint

src/components/inputs/number-input/number-input.js, src/components/inputs/number-input/number-input.spec.js
=> fix(number-input): toFormValue should handle both undefined and null

src/components/buttons/secondary-button/secondary-button.js, src/components/buttons/secondary-button/secondary-button.styles.js, yarn.lock
Refactors `SecondaryButton` to remove the usage of the HOC.
=> refactor(secondary-button): remove usage of HOC

CHANGELOG.md, package.json
=> chore: update cl for 9.10.0

README.md, src/components/inputs/toggle-input/toggle-input.js, src/components/internals/tag-remove/tag-remove.js
Removes the usage of a deprecated custom property
=> refactor: use non deprecated custom properties

.circleci/config.yml, bundlesize.config.json, package.json, yarn.lock
Adds `bundlesize` to track our bundlesize in PRs
Closes #829
=> feat: setup bundlesize

src/components/inputs/date-range-input/date-range-input.js
=> fix(date-range-input): localize day names

CHANGELOG.md, package.json
(Draft) update of changelog for 10.0.0
=> chore: update changelog for 10.0.0 release

src/components/fields/date-time-field/date-time-field.story.js
Fixes selecting of dates in the story for date time field.
It was confusing design
=> chore(date-time-field): fix story

CHANGELOG.md, package.json
=> chore: update cl

src/components/inputs/select-input/select-input.visualroute.js, src/components/internals/create-select-styles.js
Fixes Jira Issue: [UKIT-85](https://jira.commercetools.com/browse/UKIT-85)
Before:
After:
=> [UKIT-85] fix: truncate select-input placeholder text is long

.kodiak.toml
This pull request suggests adding kodiak. A nice and working merge bot. This only adds the config. Later we would install the app.
https://github.com/chdsbd/kodiak#prior-art
=> chore(ci): add kodiak

src/components/inputs/time-input/time-input.js, src/components/inputs/time-input/time-input.story.js
Refactors the `TimeInput` component to use hooks
=> refactor(time-input): use hooks

jest.bundle.config.js, jest.test.config.js, package.json, vendors-to-transpile.js, yarn.lock
Updates to latest (beta) version of `react-intl`.
Thanks to @emmenko and his [PR](https://github.com/commercetools/merchant-center-application-kit/pull/897/files)
=> chore: update react-intl to latest

.eslintrc.yaml, package.json, src/components/inputs/time-input/time-input.js, yarn.lock
The only issue here is that the plugin will squak at you if you **don't** destructure props.
Any ideas @tdeekens @emmenko ?
=> chore: add eslint-plugin-react-hooks

src/components/inputs/radio-input/radio-group.js, src/components/inputs/toggle-input/toggle-input.js
Refactors `RadioGroup` and `ToggleInput` to functional components.
=> refactor: refactor more components to functional components / hooks

test/setup-tests.js
Shamelessly copied from [@emmenko](https://github.com/commercetools/merchant-center-application-kit/pull/818)
=> fix(jest/setup): to show actual error logs on CI when something is logged

src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.js, src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.spec.js, src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.story.js, src/components/inputs/localized-multiline-text-input/translation-input.js
Refactors the `LocalizedMultilineTextInput` to use hooks.
=> refactor(localized-multiline-text-input): to use hooks

src/components/internals/calendar-body/calendar-body.js
=> refactor(calendar-body): use hooks

src/components/tooltip/tooltip.js, src/components/tooltip/tooltip.spec.js
Refactors the `Tooltip` component to use hooks.
=> refactor(tooltip): use hooks

src/components/collapsible-motion/collapsible-motion.js, src/components/panels/collapsible-panel/collapsible-panel.spec.js, src/hooks/use-previous/index.js, src/hooks/use-previous/use-previous.js, src/hooks/use-previous/use-previous.spec.js
Refactors `CollapsibleMotion` to use hooks.
I think the code got quite a bit simpler.
A follow up could be to create a `useCollapsibleMotion` hook
=> refactor(collapsible-motion): use hooks

src/components/tooltip/tooltip.js, src/components/tooltip/tooltip.spec.js
Regression in the last release.
=> fix(tooltip): use defined variable

CHANGELOG.md, package.json
=> chore: update cl for release

jest.test.config.js
https://twitter.com/RobinDrexler/status/1164515151418142721
=> chore: enable clear mocks

src/components/fields/date-field/date-field.story.js, src/components/fields/multiline-text-field/multiline-text-field.story.js, src/components/fields/text-field/text-field.story.js, src/components/fields/time-field/time-field.story.js, src/components/inputs/checkbox-input/checkbox-input.story.js, src/components/inputs/password-input/password-input.story.js, src/components/inputs/text-input/text-input.story.js
Just makes storybook a bit nicer to use.
=> chore: make stories more consistent

src/components/tooltip/tooltip.js
Make sure we don't render tooltip when it's off.
=> fix(tooltip): prioritise off

src/components/tooltip/tooltip.js, src/components/tooltip/tooltip.story.js
#1044 didn't work as intended. This should fix the problem.
=> fix(tooltip): fix for off

.renovaterc.json
This pull request proposes to combine the renovate PRs (per dep) into three weekly PRs just as we started on app-kit. 
Feel free to drop if not interested in this. Merely wanted to propose.
=> chore(renovate): combine into weekly three prs

src/components/buttons/flat-button/flat-button.js
We were supporting theming, but not for the "neutral" state.
=> fix(flat-button): fully support theming

src/components/internals/create-select-styles.js, src/components/tooltip/tooltip.styles.js
Noticed this when changing font family in app kit 🤦‍♂
=> fix: use correct font family

CHANGELOG.md, package.json
Updates changelog for version `10.2.1`
=> chore: update changelog for release `10.2.1`

src/components/tooltip/README.md
Replace outdated `position` attribute by `placement`.
=> docs: position to placement

src/components/inputs/rich-text-input/editor.js, src/components/inputs/rich-text-input/rich-text-input.form.story.js, src/components/inputs/rich-text-input/rich-text-input.js, src/components/inputs/rich-text-input/rich-text-input.story.js, src/components/internals/rich-text-body/rich-text-body.js, src/components/internals/rich-text-body/rich-text-body.styles.js, src/components/internals/rich-text-plugins/plugins/mark.js, src/components/internals/rich-text-utils/has-block.js
We had some bugs to do with focus hijacking with the `RichTextInput`. This PR fixes though, and adds a new Formik example for the Rich Text Input
=> fix(rich-text-input): focus hijack prevention

src/components/inputs/rich-text-input/editor.js, src/components/inputs/rich-text-input/rich-text-input.js, src/components/inputs/rich-text-input/rich-text-input.story.js, src/components/inputs/rich-text-input/rich-text-input.visualroute.js, src/components/internals/rich-text-body/icons/index.js, src/components/internals/rich-text-body/messages.js, src/components/internals/rich-text-body/rich-text-body.js
Adds an option "expand" icon button to the toolbar of the `RichTextInput`.
=> feat(rich-text-input): add expand icon

src/components/internals/rich-text-plugins/rich-text-plugins.js
Current we are rendering multiple tooltips, which messes with the opacity
=> fix(rich-text-input): placeholder bug

src/components/tooltip/tooltip.js, vendors/package-lock.json
=> fix: use SafeHTMLElement

src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualroute.js, src/components/inputs/rich-text-input/rich-text-input.visualroute.js, src/components/internals/rich-text-body/dropdown.js, src/components/internals/rich-text-body/dropdown.styles.js, src/components/internals/rich-text-body/multi-dropdown.js, src/components/internals/rich-text-body/rich-text-body-button.js, src/components/internals/rich-text-body/rich-text-body.js, src/components/internals/rich-text-body/rich-text-body.styles.js
Visual fixes for `RichTextInput`'s disabled state.
Also adds visual specs.
=> fix(rich-text-input): visual disabled fixes

src/components/inputs/localized-rich-text-input/README.md, src/components/inputs/multiline-text-input/README.md, src/components/inputs/rich-text-input/README.md
Updates README for `RichTextInput` to be more complete
=> chore: update readme

package.json, yarn.lock
Have been having problems with Percy font rendering. Hopefully this helps.
=> chore: try reverting puppeteer upgrade

package.json, yarn.lock
I suspect the problem we have with CI and the dep update PRs is not related to the dep updates.
So I want to rebuild yarn lock and see if the problem was really introduced earlier.
=> chore: rebuild yarn lock

src/components/buttons/primary-button/README.md, src/components/buttons/primary-button/primary-button.js, src/components/buttons/primary-button/primary-button.spec.js, src/components/buttons/primary-button/primary-button.styles.js, src/components/buttons/primary-button/primary-button.visualroute.js
* Refactors the code for `PrimaryButton` (removes the wrapper 🤔)
* Adds support for as
* Adds more VRTs
* Adds more tests
=> feat(primary-button): support as

.yarnrc
Use latest stable release of yarn with UI-Kit.
=> chore: update yarn

CHANGELOG.md, package.json
=> chore: bump version to 10.9.0; update changelog

src/components/typography/text/text.js, src/components/typography/text/text.spec.js
Prevents the `Text` components crashing when children is null.
=> fix(text): fix for when text is null

src/components/inputs/localized-rich-text-input/editor.js, src/components/inputs/localized-rich-text-input/editor.styles.js, src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualspec.js
=> fix(localized-rich-text-input): dropdown fix

.eslintignore, CONTRIBUTING.md, jest.stylelint.config.js, jest.test.config.js, package.json
Now that we have a monorepo the release process changed a bit and is the same as the one in app-kit.
=> docs: update release process

packages/components/constraints/package.json, src/components/constraints/horizontal/horizontal.js, src/components/constraints/horizontal/horizontal.spec.js
Modify `Constraints.Horizontal` to pass down `data-*` props.
=> feat(contraints-horizontal): modify to pass down data props

CHANGELOG.md
=> docs(changelog): for release v10.15.0 [skip ci]

design-system/materials/internals/TOKENS.md
- remove superfluous `need`
- added some other adjustments to structure the doc
=> docs(tokens): remove superfluous word

presets/ui-kit/index.js
=> fix(presets): data-table export in presets/ui-kit

presets/ui-kit/index.js
Fixes another dumb re-export 🤦‍♂
=> fix(presets): hooks export

src/components/field-label/field-label.js
[UKIT-110](https://jira.commercetools.com/browse/UKIT-110)
A design decision.
=> [UKIT-110] fix(field-label): adjust hint text and icon alignment

packages/components/stamp/src/stamp.js
To make it easier to provide "custom" styles (e.g. https://github.com/commercetools/commercetools-docs-kit/pull/355).
=> refactor(stamp): to support theme styles

.changeset/weak-jobs-laugh.md, src/components/icons/components/right-triangle-filled.js, src/components/icons/components/right-triangle-linear.js, src/components/icons/index.js, src/components/icons/raw-components/right-triangle-filled.js, src/components/icons/raw-components/right-triangle-linear.js, src/components/icons/svg/right-triangle-filled.react.svg, src/components/icons/svg/right-triangle-linear.react.svg
- `src/components/icons` => add `RightTriangleFilledIcon` and `RightTriangleLinearIcon` to the available icons set
=> feat(icons): Update available icons set

.github/ISSUE_TEMPLATE/bug_report.md, README.md
This PR updates the existing CodeSandbox example and adds a line to the main Readme file to encourage its usage.
Check the example here:
https://codesandbox.io/s/commercetools-ui-kit-codesandbox-1vz7c
I'm open to suggestions to adjust it :)
=> docs: add updated codesandbox example

packages/components/data-table-manager/src/column-settings-manager/column-settings-manager.js, packages/components/data-table-manager/src/data-table-manager.spec.js
Just so that we don't forget to finish this topic
=> test(data-table-manager): improve tests

packages/components/inputs/time-input/README.md, packages/components/inputs/time-input/docs/additional-info.md, packages/components/inputs/time-input/src/time-input.js
=> chore(time-input): add documentation for toLocaleTime

.changeset/cuddly-beers-sit.md, packages/components/fields/search-select-field/src/search-select-field.js
-`SearchSelectField`: pass down the `optionType` prop
=> Mw fix search select field option type

.changeset/pretty-clocks-scream.md, presets/fields/index.js, presets/fields/package.json
- `presets`: Add `SearchSelectField` to the presets
=> Update uikit presets

.github/workflows/release.yml, generators/readme/package.json, generators/readme/src/index.ts, yarn.lock
Hopefully it speeds things up a bit.
=> refactor(generator): run things async

package.json, yarn.lock
=> fix: nohoist @storybook/theming

babel.config.js
Small leftover of emotion v11. We don't use `automatic` mode at the moment anyway.
=> fix(babel): use correct dep

.changeset/neat-experts-admire.md, packages/components/pagination/README.md, packages/components/pagination/docs/usage-example.js, packages/components/pagination/src/page-navigator/page-navigator.js, packages/components/pagination/src/page-size-selector/page-size-selector.js, packages/components/pagination/src/pagination.js, packages/components/pagination/src/pagination.spec.js, packages/components/pagination/src/pagination.story.js, packages/components/pagination/src/pagination.visualroute.js
**NB**
- rename `pageSize -> perPage`
- rename `currentPage -> page` (prefixing has no value)
Refer to FE chapter discussion thread.
=> pagination revert prop naming

.github/workflows/main.yml, jest-puppeteer.config.js, package.json
=> fix: to adjust executable path via percy v2

.changeset/sharp-games-joke.md, packages/components/link/src/link.tsx
=> fix(link): to show underline

.changeset/nine-oranges-yell.md, .changeset/plenty-mirrors-tell.md, packages/calendar-utils/src/calendar-body/calendar-body.tsx, packages/components/data-table/src/cell.tsx, packages/components/data-table/src/data-table.tsx
Another small leftover of #2019
=> fix: table columns type

.changeset/tender-elephants-turn.md, packages/components/tag/src/tag-body.tsx
=> Fix Tag component color when disabled

.changeset/many-ducks-juggle.md
This is a follow up of [this PR](https://github.com/commercetools/ui-kit/pull/2102) because I forgot to include the changeset 😞 
Sorry.
=> Added missing changeset for DataTableManager

.changeset/hip-rice-destroy.md, packages/components/inputs/time-input/src/time-input.spec.js, packages/components/inputs/time-input/src/time-input.tsx
Small regression caused by #2147
=> fix(time-input): regression of handling change events

.changeset/warm-rocks-add.md, packages/components/inputs/time-input/src/time-input.spec.js, packages/components/inputs/time-input/src/time-input.tsx
Follow up of #2160 
Caused by #2147
Another small regression. The only possible explanation why I refactored it that way is that I was drunk.
=> fix(time-input): pass `onChange` as-is

.github/workflows/main.yml
Small leftover from the Yarn v3 migration
=> ci: check yarn constraints

.changeset/green-donuts-cry.md, .changeset/rotten-pets-bow.md, packages/components/inputs/radio-input/src/radio-group.tsx, packages/components/spacings/spacings-inline/src/export-types.ts, packages/components/spacings/spacings-inline/src/index.ts, packages/components/spacings/spacings-inline/src/inline.tsx, packages/components/spacings/spacings-stack/src/stack.tsx
=> fix(radio-input): prop types

.changeset/funny-bananas-compare.md, packages/components/inputs/localized-rich-text-input/src/editor.tsx, packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.form.story.js, packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.tsx, packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.visualroute.jsx, packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.visualspec.js, packages/components/inputs/rich-text-input/src/rich-text-input.visualroute.jsx
=> fix: make `<LocalizedRichTextInput>` work with Formik

.changeset/fast-turtles-compare.md, packages/components/fields/radio-field/src/radio-field.story.js
The radio field was previously not added to story book. This PR fixes that by adding the radio field to storybook
=> Add radio field to story book

.github/ISSUE_TEMPLATE/bug_report.md
Add a message to discourage creating a duplicated issue.
=> chore(github-issue): Update template for bug issue

.changeset/serious-balloons-look.md, design-system/src/theme-provider.tsx, docs/.storybook/configs/contexts.js, docs/.storybook/configs/theme-context.js, docs/.storybook/webpack.config.js, docs/package.json, docs/yarn.lock
Extracting some fixes across different PRs around design tokens work.
=> fix(design-system): themes merging and default theme

.changeset/wicked-papayas-rest.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19kxy5ULfKB0OgPQ3dfhxDe8rm9uBZew%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=CQV4NAx)
I forgot to add the changeset file in a [previous PR](https://github.com/commercetools/ui-kit/pull/2333) 🤦
=> Add missing changeset

.changeset/selfish-glasses-knock.md, packages/components/pagination/src/page-navigator/page-navigator.tsx, packages/components/pagination/src/page-size-selector/page-size-selector.tsx
`Pagination` components updates for the new theme
Use `Label` component in all messages in the new theme.
=> `Pagination` components updates for the new theme

packages/components/stamp/package.json, packages/components/stamp/src/stamp.story.js, packages/components/stamp/src/stamp.tsx, yarn.lock
Refactor stamp component alternative
This is a refactor of the current `Stamp` component refactor PR (#2383) to have examples about some topics that are still opened.
=> Refactor stamp component alternative

.changeset/kind-plants-carry.md, packages/calendar-utils/src/calendar-body/calendar-body.styles.ts, packages/components/inputs/time-input/src/time-input-body.styles.ts
Date & time input components had some styling issues when the actual input element was hovered or focused.
Components that were affected:
* DateInput
* DateRangeInput
* DateTimeInput
* TimeInput
This PR closes #2407
=> Fix date inputs CSS issues

.changeset/sixty-turtles-dance.md, packages/components/inputs/checkbox-input/src/checkbox-input.tsx
Leftover of #2424 
See also https://github.com/commercetools/ui-kit/pull/2422#discussion_r1114057203
=> fix(checkbox-input): hover effect when hovering over the label

docs/.storybook/configs/theme-context.js
Refactor theme selector in Storybook
We change the theme selector to allow choosing between the current and the new design in all the environments.
=> Refactor theme selector in Storybook

.changeset/rude-moose-push.md, packages/components/inputs/search-text-input/src/search-text-input.spec.js, packages/components/inputs/search-text-input/src/search-text-input.tsx
=> Implement submit on keydown enter for SearchTextInput

.changeset/hungry-radios-confess.md, packages/components/inputs/search-text-input/src/search-text-input.story.js, packages/components/inputs/search-text-input/src/search-text-input.tsx
=> feat(search-text-input): add `forwardRef`

.changeset/afraid-eels-love.md, packages/components/inputs/toggle-input/src/toggle-input.styles.ts, packages/components/inputs/toggle-input/src/toggle.story.js
=> fix: `z-index` of the `<ToggleInput>`

docs/.storybook/configs/intl-context.js
`locales` name change to reference `supportedLocales`
=> Reference locales name change to point to supportedLocales

docs/.storybook/preview-head.html, visual-testing-app/index.html
Same as https://github.com/commercetools/merchant-center-application-kit/pull/3167
=> fix: font loading without slant

.changeset/tame-walls-sell.md, packages/components/inputs/select-input/src/select-input.story.js, packages/components/inputs/select-input/src/select-input.tsx
=> fix(SelectInput): set menu placement to `auto`

CONTRIBUTING.md
This adds a bit more information around testing I think could be useful for contributors.
=> docs(contributing): add testing section

.changeset/stale-radios-punch.md, packages/components/card/src/card.tsx, packages/components/card/src/card.visualroute.jsx, packages/components/spacings/spacings-inset-squish/README.md, packages/components/spacings/spacings-inset-squish/src/inset-squish.tsx, packages/components/spacings/spacings-inset/README.md, packages/components/spacings/spacings-inset/src/inset.tsx
Follow up of #2635 
As per discussion we move back to names which are more descriptive.
=> refactor: height prop values to be descriptive

.changeset/two-dragons-boil.md, packages/calendar-utils/src/calendar.spec.js, packages/calendar-utils/src/calendar.ts
Closes https://github.com/commercetools/ui-kit/issues/2632
Fixes a bug introduced [here](https://github.com/commercetools/ui-kit/pull/2598)
=> fix(calendar-utils): `getPaddingDayCount` helper function

packages/components/inputs/selectable-search-input/src/selectable-search-input.story.js, packages/components/inputs/selectable-search-input/src/selectable-search-input.tsx, packages/components/inputs/selectable-search-input/src/selectable-select.tsx
This PR implements a different approach than the one used in #2678 that I think could be simpler and fulfil the same requirement.
=> Data prop provision for select dropdown option [alternative proposal]

packages/components/progress-bar/src/progress-bar.story.js, packages/components/progress-bar/src/progress-bar.styles.tsx, packages/components/progress-bar/src/progress-bar.tsx, packages/components/progress-bar/src/progress-bar.visualroute.jsx
New ProgressBar component implementation alternative
In this PR I showcase a couple of changes to [the original one](https://github.com/commercetools/ui-kit/pull/2702) so we better manage styling and structure independently and I also try to suggest a cleaner rendering logic.
=> New ProgressBar component implementation alternative

.changeset/mean-crabs-perform.md, packages/components/icons/src/export-types.ts, packages/components/icons/src/inline-svg/export-types.ts, packages/components/icons/src/inline-svg/index.ts, packages/components/icons/src/inline-svg/inline-svg.tsx, packages/components/icons/src/leading-icon/export-types.ts, packages/components/icons/src/leading-icon/index.ts
Export leading icon types so it can be properly consumed the right way. 
For more context, see https://github.com/commercetools/merchant-center-frontend/pull/16448/files#r1525033953
=> Export leading icon types

packages/components/inputs/async-creatable-select-input/README.md, packages/components/inputs/async-creatable-select-input/docs/usage-example.js, packages/components/inputs/async-select-input/README.md, packages/components/inputs/async-select-input/docs/usage-example.js
It's been brought to our attention that the `AsyncSelectInput` documentation isn't accurate. This pull request addresses the issue by updating the READMEs of both `AsyncCreatableSelectInput` and `AsyncSelectInput` to ensure validity of usage examples. The examples have been adjusted by aligning them with the respective `*-Field` components.
=> fix(docs): async select components readmes

packages/components/tag/src/tag-body.tsx, packages/components/tag/src/tag.tsx
Simplify border styles management
This is a proposal for simplification in border related styles management in the Tag component as part of the work that's in progress on this #2767
=> Simplify border styles management

.github/ISSUE_TEMPLATE/bug_report.md
This PR improves the Github bug issue template by adding new fields to the bug report template.
This PR improves the Github bug issue template by adding new fields to the bug report template. The new fields include the UI Kit Version Number, Browser, and Priority. These fields will help the team gather more information about the bug and prioritise the issues effectively. The changes are essential for better bug tracking and resolution. The updated template will provide a more comprehensive overview of the bug and help the team address the issues more efficiently.
=> Update github bug issue template

.github/ISSUE_TEMPLATE/feature_request.md
Update github feature request template
Update github feature request template. 
This pull request updates the feature request template. The changes include adding a section for internal requests with the following information: Champion, Stakeholders, Required components, and Best practices. This update aims to provide a clear and concise structure for internal feature requests, ensuring that all necessary information is included for a successful contribution process. The changes are beneficial as they help streamline the request process, improve communication between teams, and ensure that all relevant stakeholders are involved in the development of new features.
**Screenshots**
=> Update github feature request template

.github/ISSUE_TEMPLATE/improve_documentation.md
Introduce a new Github issue type for documentation improvement
Introduce a new Github issue type for documentation improvement. This change adds a new issue type to the Github issue template for improving documentation. This change aims to streamline the process of suggesting updates to the project's documentation by providing a dedicated template for documentation improvement issues. The new issue type will help maintain consistency in the documentation improvement process and ensure that all necessary information is included when suggesting updates to the project's documentation.
=> Introduce a new Github issue type for documentation improvement

.github/workflows/preview-release.yml
bug fix gh action syntax error.
=> bug fix gh action syntax error

design-system/materials/custom-properties.css, design-system/materials/custom-properties.json, design-system/materials/custom-properties_default.css, design-system/materials/internals/definition.yaml, design-system/src/design-tokens.ts, packages/components/filters/package.json, packages/components/filters/src/filter-menu/filter-menu.spec.tsx, packages/components/filters/src/filter-menu/filter-menu.tsx, packages/components/filters/src/filter-menu/trigger-button/trigger-button.spec.tsx, packages/components/filters/src/filter-menu/trigger-button/trigger-button.styles.ts, packages/components/filters/src/filter-menu/trigger-button/trigger-button.tsx, packages/components/filters/src/filters.stories.tsx, packages/components/filters/src/filters.tsx, yarn.lock
This PR implements the initial styling/structure/states for `TriggerButton` and `TriggerMenu`.  It uses `@radix/react-popover` to handle displaying the `FilterMenu` body.
Most of the relevant changes here are to the `TriggerButton`, please see the [relevant figma](https://www.figma.com/design/b2S3GGpScVDuf15VAGEqeL/Filter-pattern?node-id=2339-6256&m=dev).
Most noticeably, this PR does not handle showing selected values in the `TriggerButton`. That will be handled in a subsequent PR.
The relevant states are currently displayed for ease of review [in storybook](https://ui-p5a3p6ad7-commercetools.vercel.app/?path=/docs/components-filters--props).  The storybook will be updated to be tagged with `local-dev` once the PR is approved so that the story is not published on prod.
* **Dependencies …
=> Fct 1119 - `TriggerButton` and `FilterMenu` base styles and states

packages/components/filters/src/filters.stories.tsx, packages/components/filters/src/filters.tsx
Accidentally didnt add `local-dev` tag to `filterMenu` PR, fixing that here
=> fix(storybook): make sure filters storybook isnt published in prod

.github/workflows/main.yml
=> Fct 1250 UI kit failing percy workflow

.changeset/plenty-lamps-drum.md, packages/components/filters/package.json, packages/components/filters/src/filter-menu/filter-menu.tsx, packages/components/filters/src/filters.spec.tsx, packages/components/filters/src/filters.stories.tsx, packages/components/filters/src/filters.tsx, packages/components/filters/src/messages.ts, packages/i18n/data/core.json, yarn.lock
[Ticket reference](https://commercetools.atlassian.net/browse/FCT-1182)
[Figma spec](https://www.figma.com/design/b2S3GGpScVDuf15VAGEqeL/Filter-pattern?m=auto&node-id=4236-125943)
Requirements Summary:
- Initial api/JSDocs constructed
- SearchBox placeholder
- Filters button that shows/hides the filters list.
- Basic styling of: `filters`, `add filter` & `clear all` buttons, horizontal & vertical divider
- The `Add Filter` button should use radix/popover to expand a SelectInput component to allow for selecting filters. 
- Tests added
** `['local-dev']` left for testing purposes & will be commented out prior to merging.
=> FCT-1182 - Filters - Implement initial `FiltersList` API and styling

packages/components/filters/src/filters.tsx, packages/components/filters/src/messages.ts, packages/i18n/data/core.json
updated ids to match existing format.. please merge on my behalf!
=> fix(messages): correct format

.github/workflows/preview-release.yml
=> fix(preview release): use yarn

.github/workflows/merge-blocking-labels.yml
Not that it's easy to miss but I did miss this label.
=> Add `🚨 🚨 🚨DO NOT MERGE🚨 🚨 🚨` label to GitHub Action

package.json, yarn.lock
- [Ticket](https://commercetools.atlassian.net/browse/FCT-1436)
- [Security-Issue](https://github.com/commercetools/ui-kit/security/dependabot/14)
I couldn't update remark-parse - the package making use of the `trim` package -  so it has to be another resolution field.
=> chore(deps): add resolution for trim dependency
